### ISSUE TITLE
Minecolonies testpack problem

### ISSUE THREAD

**Issue by Gunscrusader** [Minecolonies/minecolonies#102]
I have a problem while trying to start the test pack. I downloaded it on the curse client and tried to start it like any other modpack on it but it only starts the minecraft client and after i press play, it stops and gives the following:

2016-09-06 16:31:05,781 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:31:05] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:31:05] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

I might be missing something so please help!

**Comment by Kostronor** [comment]
This is no place for support on the modpack. 

I need more info to help you there. The whole log file at least...

**Comment by Gunscrusader** [comment]
Hi sorry if i posted on another thread. I only checked my emails just
now(sorry!). Anyways, the log files in the log directory says more or less
the same like my post. Not much info. Ill still attach it for reference
sake. Anyways, i think it might be a lack of software or something. Ive
been playing on 1.7.10 lately and i think i might be missing something to
play 1.8.9 forge. Any and all help will be appreciated :).

**Comment by Gunscrusader** [comment]
Here you go. i hope this helps

**Comment by Kostronor** [comment]
You attached nothing, I suggest you use the web interface

**Comment by Gunscrusader** [comment]
Ok this is getting annoying. Chrome is blocking me from uploading this file
for some reason. I compressed my minecolonies testpack folder and it doesnt
want to be attached. Its like this problem doesnt want to be solved. Im
going to try the technic launcher.

**Comment by Gunscrusader** [comment]
Sorry for being a real pain, but i want to know what is causing this
problem so that i can solve it in the future. I do have some knowledge of
java, but not enough knowledge of minecraft modding to be able to
understand whats going on. For some reason though, it feels like it has to
be an incomplete download or missing some sort of file from curse, or have
a file causing these problems. I did redownload the pack towards no
success. My curse client works fine with agrarian skies 2. Also, my main
problem with this error is that the game barely starts. It doesnt even load
the main menu or the loading screen. That is what causes the lack of enough
log to explain. Except for that, is forge installed? Do i need a special
java kit? What are the prerequisites to play this pack?

**Comment by Kostronor** [comment]
You need java 8,you need curse and you need to click install. 

Can you uninstall and install the pack again over the launcher

**Comment by Gunscrusader** [comment]
Ok i do have java 8 installed version 101. Is there another kit or sdk or
something i need to install? Except for that, does the forge for 1.8.9
require something? Ive been playing on 1.7.10 forge and havent really tried
1.8.9 forge before. Also, curse client doesnt really offer an uninstall
button, from what i saw. I basically deleted it from my root directory and
redownloaded it. I cant really check right now, considering that i am busy
running class at university and i am far away from my computer. When i have
an opening, ill download forge 1.8.9 and the latest minecolonies manually
and install it on my local non curse .minecraft file without the pack, just
to see if it works. If it does, then ill leave the pack on curse and setup
my own one.

Anyways, thanks for replying and trying to help. I really appreciate it
when the authors put so much effort into a mod, as well as going around
trying to help people, instead of just casting a cloud over things. My
studies at university revolves around programming, so all extra knowledge
from coding from external sources can help me understand how things are
done, so that i can write my own improved programs or even my very own mods.

Thanks again!

**Comment by Kostronor** [comment]
Java 8 v101 is fine. You maybe have to check if curse uses this version of java to start minecraft. But it should take the latest one...

Try the reinstall and report back :)

**Comment by Gunscrusader** [comment]
Ok will do!

**Comment by Gunscrusader** [comment]
Ok it seems to be running fine on my local .minecraft game. I think the
problem is with curse itself.

**Comment by Kostronor** [comment]
Can you message me on the minecolonies forum? I can try to fix it over TeamViewer

**Comment by Gunscrusader** [comment]
Should i post something on your wall at the website?

**Comment by Kostronor** [comment]
Write me a private message 

Am 07.09.2016 1:08 nachm. schrieb Gunscrusader <notifications@github.com>:

Should i post something on your wall at the website?

**Comment by Gunscrusader** [comment]
Hi my internet is very sluggish now. I had to reset my computer as well.
Ive sent a message if you are online. Sorry
