### ISSUE TITLE
Crash when changing styles folder

### ISSUE THREAD

**Issue by Raycoms** [Minecolonies/minecolonies#107]
### Minecolonies version
Current
### Expected behavior
Show the next Folder content.
### Actual behaviour
Crash.
### Steps to reproduce the problem
Create another style folder and try to switch styles.

---- Minecraft Crash Report ----
 
WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  BCModPlugin (zz-backpacks 1.8.9 - 3.1.0.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.2.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
Contact their authors BEFORE contacting forge
 
// My bad.
 
Time: 9/6/16 8:05 PM
Description: Updating screen events
 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at com.minecolonies.client.gui.WindowBuildTool.getStyles(WindowBuildTool.java:310)
    at com.minecolonies.client.gui.WindowBuildTool.styleClicked(WindowBuildTool.java:416)
    at com.minecolonies.client.gui.WindowBuildTool$$Lambda$62/189797326.accept(Unknown Source)
    at com.minecolonies.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:53)
    at com.blockout.controls.Button.handleClick(Button.java:110)
    at com.blockout.Pane.click(Pane.java:445)
    at com.blockout.View.click(View.java:223)
    at com.blockout.Screen.func_73864_a(Screen.java:80)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Stacktrace:
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at com.minecolonies.client.gui.WindowBuildTool.getStyles(WindowBuildTool.java:310)
    at com.minecolonies.client.gui.WindowBuildTool.styleClicked(WindowBuildTool.java:416)
    at com.minecolonies.client.gui.WindowBuildTool$$Lambda$62/189797326.accept(Unknown Source)
    at com.minecolonies.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:53)
    at com.blockout.controls.Button.handleClick(Button.java:110)
    at com.blockout.Pane.click(Pane.java:445)
    at com.blockout.View.click(View.java:223)
    at com.blockout.Screen.func_73864_a(Screen.java:80)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)
 
-- Affected screen --
Details:
    Screen name: com.blockout.Screen
 
-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['lil_kahann'/1692, l='MpServer', x=-651.85, y=4.00, z=-20.42]]
    Chunk stats: MultiplayerChunkCache: 625, 625
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options:
    Level spawn location: -633.00,4.00,-6.00 - World: (-633,4,-6), Chunk: (at 7,0,10 in -40,-1; contains blocks -640,0,-16 to -625,255,-1), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
    Level time: 63055 game time, 9474 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 91 total; [EntityCow['Cow'/58880, l='MpServer', x=-691.25, y=4.00, z=-34.00], EntityCow['Cow'/58881, l='MpServer', x=-692.50, y=4.00, z=-34.50], EntityPig['Pig'/58882, l='MpServer', x=-689.97, y=4.00, z=-34.03], EntityPig['Pig'/58883, l='MpServer', x=-681.50, y=4.00, z=-38.50], EntityPig['Pig'/58884, l='MpServer', x=-679.41, y=4.00, z=-40.91], EntityPig['Pig'/58885, l='MpServer', x=-682.50, y=4.00, z=-40.50], EntitySheep['Sheep'/58886, l='MpServer', x=-687.31, y=4.00, z=-36.75], EntitySheep['Sheep'/58887, l='MpServer', x=-686.50, y=4.00, z=-35.50], EntitySheep['Sheep'/58888, l='MpServer', x=-685.19, y=4.00, z=-40.50], EntitySheep['Sheep'/58889, l='MpServer', x=-680.50, y=4.00, z=-40.50], EntitySheep['Sheep'/58890, l='MpServer', x=-653.81, y=4.00, z=-85.22], EntitySheep['Sheep'/58891, l='MpServer', x=-653.72, y=4.00, z=-87.22], EntitySheep['Sheep'/58892, l='MpServer', x=-648.91, y=4.00, z=-88.69], EntitySheep['Sheep'/58765, l='MpServer', x=-573.50, y=4.00, z=-74.50], EntitySheep['Sheep'/58893, l='MpServer', x=-645.13, y=4.00, z=-85.75], EntityChicken['Chicken'/58894, l='MpServer', x=-650.50, y=4.00, z=-83.50], EntityChicken['Chicken'/58895, l='MpServer', x=-649.50, y=4.00, z=-84.50], EntitySheep['Sheep'/58768, l='MpServer', x=-572.50, y=4.00, z=-71.50], EntityChicken['Chicken'/58896, l='MpServer', x=-648.50, y=4.00, z=-85.50], EntityChicken['Chicken'/58897, l='MpServer', x=-650.50, y=4.00, z=-89.50], EntitySheep['Sheep'/58770, l='MpServer', x=-584.78, y=4.00, z=-76.47], EntityRabbit['Rabbit'/58898, l='MpServer', x=-652.50, y=4.00, z=-84.50], EntityRabbit['Rabbit'/58899, l='MpServer', x=-654.66, y=4.00, z=-84.66], EntityRabbit['Rabbit'/58900, l='MpServer', x=-652.19, y=4.00, z=-88.53], EntityRabbit['Rabbit'/58772, l='MpServer', x=-574.88, y=4.00, z=-76.47], EntityRabbit['Rabbit'/58901, l='MpServer', x=-654.69, y=4.00, z=-88.97], EntityRabbit['Rabbit'/58775, l='MpServer', x=-575.09, y=4.00, z=-77.84], EntityHorse['Horse'/58776, l='MpServer', x=-610.63, y=4.00, z=-0.34], EntityHorse['Horse'/58777, l='MpServer', x=-603.50, y=4.00, z=-8.50], EntityHorse['Horse'/58778, l='MpServer', x=-601.50, y=4.00, z=-7.50], EntityCitizen['Betty B. Williams'/1691, l='MpServer', x=-647.63, y=4.00, z=26.44], EntityChicken['Chicken'/58779, l='MpServer', x=-573.56, y=4.00, z=-93.38], EntityCitizen['Lisa F. Allen'/20638, l='MpServer', x=-649.53, y=4.00, z=-0.53], EntityChicken['Chicken'/58783, l='MpServer', x=-572.19, y=4.00, z=-92.34], EntityCitizen['Henrik U. Williams'/20640, l='MpServer', x=-634.78, y=4.91, z=1.16], EntityCitizen['Christopher U. Taylor'/20641, l='MpServer', x=-639.53, y=4.91, z=2.94], EntityPig['Pig'/58790, l='MpServer', x=-575.50, y=4.00, z=-81.50], EntityPig['Pig'/58792, l='MpServer', x=-574.50, y=4.00, z=-84.50], EntityRabbit['Rabbit'/58800, l='MpServer', x=-617.50, y=4.00, z=-81.50], EntityRabbit['Rabbit'/58801, l='MpServer', x=-619.84, y=4.00, z=-83.59], EntityRabbit['Rabbit'/58804, l='MpServer', x=-620.75, y=4.00, z=-84.41], EntityRabbit['Rabbit'/58810, l='MpServer', x=-619.84, y=4.00, z=-84.47], EntitySheep['Sheep'/58812, l='MpServer', x=-611.97, y=4.00, z=-94.97], EntitySheep['Sheep'/58817, l='MpServer', x=-621.81, y=4.00, z=-86.81], EntitySheep['Sheep'/58819, l='MpServer', x=-620.28, y=4.00, z=-76.22], EntityCow['Cow'/58822, l='MpServer', x=-620.59, y=4.00, z=-85.34], EntityCow['Cow'/58824, l='MpServer', x=-625.25, y=4.00, z=-97.84], EntityCow['Cow'/58826, l='MpServer', x=-626.50, y=4.00, z=-89.50], EntityCow['Cow'/58828, l='MpServer', x=-623.84, y=4.00, z=-88.19], EntityPig['Pig'/58829, l='MpServer', x=-693.50, y=4.00, z=-9.50], EntityPig['Pig'/58830, l='MpServer', x=-692.50, y=4.00, z=-7.50], EntityPig['Pig'/58831, l='MpServer', x=-703.13, y=4.00, z=-16.97], EntityPig['Pig'/58832, l='MpServer', x=-697.25, y=4.00, z=-9.84], EntityCow['Cow'/58833, l='MpServer', x=-686.81, y=4.00, z=-3.63], EntityCow['Cow'/58834, l='MpServer', x=-685.19, y=4.00, z=-4.84], EntityCow['Cow'/58835, l='MpServer', x=-686.50, y=4.00, z=-2.03], EntityCow['Cow'/58836, l='MpServer', x=-684.50, y=4.00, z=-2.50], EntitySheep['Sheep'/58837, l='MpServer', x=-690.50, y=4.00, z=-7.50], EntitySheep['Sheep'/58838, l='MpServer', x=-691.22, y=4.00, z=-2.81], EntitySheep['Sheep'/58839, l='MpServer', x=-692.84, y=4.00, z=-1.19], EntitySheep['Sheep'/58840, l='MpServer', x=-694.50, y=4.00, z=-1.50], EntitySheep['Sheep'/58841, l='MpServer', x=-659.09, y=4.00, z=58.91], EntityPlayerSP['lil_kahann'/1692, l='MpServer', x=-651.85, y=4.00, z=-20.42], EntityChicken['Chicken'/58854, l='MpServer', x=-647.50, y=4.00, z=-55.50], EntityChicken['Chicken'/58855, l='MpServer', x=-649.50, y=4.00, z=-56.50], EntityChicken['Chicken'/58856, l='MpServer', x=-650.50, y=4.00, z=-59.50], EntityChicken['Chicken'/58857, l='MpServer', x=-647.50, y=4.00, z=-58.50], EntitySheep['Sheep'/58858, l='MpServer', x=-641.03, y=4.00, z=-55.97], EntitySheep['Sheep'/58859, l='MpServer', x=-646.53, y=4.00, z=-47.63], EntitySheep['Sheep'/58860, l='MpServer', x=-639.81, y=4.00, z=-40.88], EntitySheep['Sheep'/58861, l='MpServer', x=-641.19, y=4.00, z=-49.50], EntitySheep['Sheep'/58862, l='MpServer', x=-649.88, y=4.00, z=-53.13], EntitySheep['Sheep'/58863, l='MpServer', x=-647.19, y=4.00, z=-53.84], EntitySheep['Sheep'/58864, l='MpServer', x=-644.19, y=4.00, z=-50.84], EntitySheep['Sheep'/58865, l='MpServer', x=-648.50, y=4.00, z=-49.50], EntityRabbit['Rabbit'/58738, l='MpServer', x=-573.50, y=4.00, z=5.50], EntityChicken['Chicken'/58739, l='MpServer', x=-580.50, y=4.00, z=-94.50], EntityChicken['Chicken'/58740, l='MpServer', x=-576.50, y=4.00, z=-94.50], EntityChicken['Chicken'/58741, l='MpServer', x=-577.50, y=4.00, z=-91.50], EntityChicken['Chicken'/58869, l='MpServer', x=-690.41, y=4.00, z=-89.63], EntityChicken['Chicken'/58742, l='MpServer', x=-577.50, y=4.00, z=-89.50], EntityHorse['Horse'/58743, l='MpServer', x=-583.81, y=4.00, z=-92.22], EntityHorse['Horse'/58744, l='MpServer', x=-586.50, y=4.00, z=-89.50], EntityHorse['Horse'/58745, l='MpServer', x=-590.50, y=4.00, z=-85.50], EntityHorse['Horse'/58746, l='MpServer', x=-586.50, y=4.00, z=-81.50], EntityChicken['Chicken'/58747, l='MpServer', x=-583.50, y=4.00, z=-93.84], EntityChicken['Chicken'/58748, l='MpServer', x=-582.19, y=4.00, z=-92.50], EntityChicken['Chicken'/58749, l='MpServer', x=-584.50, y=4.00, z=-88.50], EntityChicken['Chicken'/58750, l='MpServer', x=-583.50, y=4.00, z=-85.50], EntityCow['Cow'/58878, l='MpServer', x=-693.50, y=4.00, z=-36.50], EntityCow['Cow'/58879, l='MpServer', x=-688.03, y=4.00, z=-35.31]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 992881672 bytes (946 MB) / 1726480384 bytes (1646 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1855 32 mods loaded, 32 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAAAA  mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
    UCHIJAAAAAAAAA  FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1855.jar)
    UCHIJAAAAAAAAA  Forge{11.15.1.1855} [Minecraft Forge] (forge-1.8.9-11.15.1.1855.jar)
    UCHIJAAAAAAAAA  backpacks16840{3.1.0} [Backpacks!] (zz-backpacks 1.8.9 - 3.1.0.jar)
    UCHIJAAAAAAAAA  JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar)
    UCHIJAAAAAAAAA  AppleCore{1.3.2} [AppleCore] (AppleCore-mc1.8.9-1.3.2.jar)
    UCHIJAAAAAAAAA  Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar)
    UCHIJAAAAAAAAA  BaublesHud{2.2.1} [Baubles-Hud] (BaublesHud-2.2.1.jar)
    UCHIJAAAAAAAAA  BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar)
    UCHIJAAAAAAAAA  Chameleon{1.8.9-1.1.5} [Chameleon] (Chameleon-1.8.9-1.1.5.jar)
    UCHIJAAAAAAAAA  CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar)
    UCHIJAAAAAAAAA  Ding{MC1.8.9v2} [Ding] (Ding-MC1.8.9v2.jar)
    UCHIJAAAAAAAAA  fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar)
    UCHIJAAAAAAAAA  hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar)
    UCHIJAAAAAAAAA  inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar)
    UCHIJAAAAAAAAA  IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar)
    UCHIJAAAAAAAAA  journeymap{1.8.9-5.2.4} [JourneyMap] (journeymap-1.8.9-5.2.4-unlimited.jar)
    UCHIJAAAAAAAAA  jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.23.jar)
    UCHIJAAAAAAAAA  mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar)
    UCHIJAAAAAAAAA  minecolonies{1.8.9-0.3.613} [MineColonies] (minecolonies-universal-1.8.9-0.3.613.jar)
    UCHIJAAAAAAAAA  Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar)
    UCHIJAAAAAAAAA  Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.5.0.jar)
    UCHIJAAAAAAAAA  RTG{1.8.9} [Realistic Terrain Generation] (RTG-1.8.9-1.0.0-snapshot-2.jar)
    UCHIJAAAAAAAAA  StorageDrawers{1.8.9-2.7.0} [Storage Drawers] (StorageDrawers-1.8.9-2.7.0.jar)
    UCHIJAAAAAAAAA  tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.jar)
    UCHIJAAAAAAAAA  VeinMiner{0.34.1_1.8.9-9901a41} [Vein Miner] (VeinMiner-0.34.1-1.8.9r552+9901a41.jar)
    UCHIJAAAAAAAAA  VeinMinerModSupport{0.34.1_1.8.9-9901a41} [Mod Support] (VeinMiner-0.34.1-1.8.9r552+9901a41.jar)
    UCHIJAAAAAAAAA  Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar)
    UCHIJAAAAAAAAA  WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.7.jar)
    UCHIJAAAAAAAAA  wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar)
    UCHIJAAAAAAAAA  xprings{1.2.0} [Experience Rings] (xprings-1.2.0.jar)
    UCHIJAAAAAAAAA  denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.3.jar)
    Loaded coremods (and transformers):
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
BCModPlugin (zz-backpacks 1.8.9 - 3.1.0.jar)
  brad16840.common.asm.ClassTransformer
AppleCore (AppleCore-mc1.8.9-1.3.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.54' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses:
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
 
    Launched Version: forge-11.15.1.1855
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.54, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
 
    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs:
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 4x Intel(R) Xeon(R) CPU E5620 @ 2.40GHz

**Comment by Kostronor** [comment]
Is fixed I think
