### ISSUE TITLE
Builder indicator lights

### ISSUE THREAD

**Issue by Raycoms** [Minecolonies/minecolonies#114]
I just watched Peters video about the decoration placement and thought it would be nice if there would be like a visible effect showing that there will be something built soon.

So, I thought about the following system:

We render stuff like the beacon light from the point where the object will be built.
- Green light may be built
- Yellow light: in progress
- Red light: Not meeting prerequisites.

**Comment by pmardle** [comment]
Not entirely sure what you are thinking of here..

I would love something to show where a build order has been placed.  Perhaps the wire frame of the overall bounds of the schematic could remain in world until the building is built?

**Comment by DarVillous** [comment]
Long ago I played a game where they covered the construction area with a tarp.  That seems excessive; but what about Construction tape around the area?

**Comment by pmardle** [comment]
Works for me

**Comment by Raycoms** [comment]
Honestly I once had the idea of a wooden structure around the building with
fences, ladders, planks xD.

But I'm okay with a construction tape thing.

2016-09-21 12:18 GMT-03:00 pmardle <notifications@github.com>:
