### ISSUE TITLE
Game Crash before Minecraft Opens

### ISSUE THREAD

**Issue by nictheman123** [Minecolonies/minecolonies#118]
### Minecolonies version
1.8.9 - 0.4.737
### Expected behavior
Game runs and I can create awesome villages and kingdoms and such
### Actual behaviour
Game crashes instantly upon clicking play in MultiMC
### Steps to reproduce the problem
Create 1.8.9 instance in MultiMC
Download Required Forge Version
Install Mod
Click Play
Get crashlog.

### Note
I tried it with an older version of forge because it was recommended and it opened the minecraft window before telling me I did not have the required Forge, after installing that version and any newer version the game window refuses to open. This mod is amazing and I can't wait to play with it so please help ASAP

**Comment by Raycoms** [comment]
If possible, could you please upload the crash log?
It should be situated inside your folders called "logs".

Are you using java 8?

2016-09-11 16:19 GMT-03:00 nictheman123 <notifications@github.com>:

**Comment by nictheman123** [comment]
Thanks for the timely response. I updated my java to the latest version on their website in an attempt to avoid java issues just today. Linked my latest log to the comment. Thank you again for the help
[latest.zip](https://github.com/Minecolonies/minecolonies/files/466208/latest.zip)

**Comment by Raycoms** [comment]
Your problem might be just this:

[16:06:22] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version
1.7.0_45, running on Windows 8:amd64:6.2, installed at C:\Program
Files\Java\jdk1.7.0_45\jre

It seems like it is still using your java 7.
If you're using the technic launcher just set it to use the java 8 version.

Else let your java home point to the 1.8 jdk or simply remove java 7 and
only use java 8.

2016-09-11 17:10 GMT-03:00 nictheman123 <notifications@github.com>:

**Comment by nictheman123** [comment]
I still have several older modpacks that need older versions of java. I clicked auto detect on the java select screen but I guess it just did not register to the machine to use the shiny recommended version. Thank you for the help
