### ISSUE TITLE
SMP crash on TownHall-placement

### ISSUE THREAD

**Issue by MrVirtualis** [Minecolonies/minecolonies#122]
### Minecolonies version
0.4.3 for 1.10.2

### Expected behavior
Placing the Town Hall.

[crash-2016-09-13_23.43.42-server.txt](https://github.com/Minecolonies/minecolonies/files/470863/crash-2016-09-13_23.43.42-server.txt)

### Actual behaviour
Server crashes.

### Steps to reproduce the problem
Place Town Hall.

[update]
Fyi, I tried it without any other mods installed and the issue stays the same.

**Comment by Kostronor** [comment]
@Raycoms seems like we are using client only stuff there

**Comment by MrVirtualis** [comment]
[crash-2016-09-14_16.04.47-server.txt](https://github.com/Minecolonies/minecolonies/files/472266/crash-2016-09-14_16.04.47-server.txt)

Sry, I don't see where I can reopen the issue. Not sure if I'm allowed to.

**Comment by Raycoms** [comment]
We will reopen it, and I will take a look at it later today. Very strange
error.

2016-09-14 11:24 GMT-03:00 MrVirtualis <notifications@github.com>:
