### ISSUE TITLE
Loading Crash-1.10.2

### ISSUE THREAD

**Issue by WenXin20** [Minecolonies/minecolonies#123]
### Minecolonies version
0.4.3-1.10.2 Forge 2080
### Expected behavior
Loading Properly
### Actual behavior
Crashed when loading the game
[Crash Report](http://pastebin.com/FXsPixwi)
### Steps to reproduce the problem
Luanch minecraft

**Comment by Kostronor** [comment]
Can you give us the exact list of mods you are using? And can you try again (and post a second crash log)? 

This seems pretty interesting...

**Comment by WenXin20** [comment]
I am using the curse launcher, and a list of mods I use is at this site: http://modlister.com/user/WenXin2

**Comment by WenXin20** [comment]
It still crashed me
[Crash Report](http://pastebin.com/QzsgULS9)

**Comment by Raycoms** [comment]
Can yo try it with forge 2077?

2016-09-14 14:32 GMT-03:00 WenXin20 <notifications@github.com>:

**Comment by WenXin20** [comment]
It still crashes w/ forge 2077
[Crash Report](http://pastebin.com/DhV9hEWA)

**Comment by Raycoms** [comment]
It is possible that one of the core mods you added does change methods our
mods use. Please try to find out which one.


2016-09-15 14:50 GMT-03:00 WenXin20 <notifications@github.com>:

**Comment by Raycoms** [comment]
It also seems like you have some 1.9.4 coremods installed, this make break
it as well.

2016-09-15 16:01 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by WenXin20** [comment]
I found out it is caused by the [X-ray Mod](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292688-xray-mod-1-6-4-1-10-vanilla-forge-liteloader).

**Comment by WenXin20** [comment]
It's fixed with xray now.
