### ISSUE TITLE
exception getting thrown while buildings getting made 1.10.2

### ISSUE THREAD

**Issue by SDUBZ** [Minecolonies/minecolonies#124]
### Minecolonies version
Minecolonies v0.4.3
### Expected behavior
to build and upgrade without a exception getting thrown and causing minor lagg to client
### Steps to reproduce the problem
when making certain buildings and upgrading the town hall and builders hut

exceptioned logged:http: //pastebin.com/4j0KZhSJ

**Comment by SDUBZ** [comment]
also one of my colonist died and crashed the game 
crash report:
[crash-2016-09-14_15.36.41-server.txt](https://github.com/Minecolonies/minecolonies/files/471351/crash-2016-09-14_15.36.41-server.txt)

**Comment by Kostronor** [comment]
Thanks a lot for the report! 

It seems the citizen dieing is related to #121
