### ISSUE TITLE
[bug] Crafting and giving Items not possible

### ISSUE THREAD

**Issue by MrVirtualis** [Minecolonies/minecolonies#127]
### Minecolonies version
v0.4.3.2 // MC 1.10.2 // Forge 2086

### Expected behavior
Craft / Give / See Blocks

### Actual behaviour
Blocks don't show up in JEI or Creative and can't be crafted (although the icon for the SupplyShip is beeing shown in the CraftingTable).

[update]
This only occurs in SMP. SSP seems to work.

**Comment by Kostronor** [comment]
Another new forge version? 

Is it the same with 2077 and 2080?

@Raycoms may know more

**Comment by MrVirtualis** [comment]
I haven't tried with other forge version, but can do so.
Forge updates pretty much daily, but I didn't run into other problems with the new version so far, so I guess no big changes.

**Comment by Raycoms** [comment]
Could you please try it, these errors may be caused by mapping changes
(which seems to happen a lot through forge versions)

2016-09-15 11:02 GMT-03:00 MrVirtualis <notifications@github.com>:

**Comment by MrVirtualis** [comment]
Well, in SSP it works with Forge 2086, but not in SMP. I tested it with an existing and a new world.

**Comment by MrVirtualis** [comment]
I'll have a look. We have a lot of mods installed, so finding the right log will take a while.

**Comment by MrVirtualis** [comment]
[log.txt](https://github.com/Minecolonies/minecolonies/files/474889/log.txt)

I extracted everything related to the mod. If you need any more infos, let me know.

**Comment by Raycoms** [comment]
can you put the jar inside a zip and call it minecolonies-universal-1.10.2.zip
?

2016-09-15 11:35 GMT-03:00 MrVirtualis <notifications@github.com>:

**Comment by MrVirtualis** [comment]
I did so. But that doesn't change anything.

**Comment by Raycoms** [comment]
In the log you sent me he tried to open a zip but we only have a jar. Can
you send us the new log?

2016-09-15 12:05 GMT-03:00 MrVirtualis <notifications@github.com>:

**Comment by MrVirtualis** [comment]
[log.txt](https://github.com/Minecolonies/minecolonies/files/474974/log.txt)

**Comment by Raycoms** [comment]
Can you send us a screenshot of your mods folder and try to use forge 2077
(only with the jar inside the mods folder)

Thank you for testing

2016-09-15 12:18 GMT-03:00 MrVirtualis <notifications@github.com>:

**Comment by MrVirtualis** [comment]
Changing the server to 2077 is quite some work. Have you tried to start it on a local server? (not SSP, but starting a server on your local machine).

**Comment by Kostronor** [comment]
The most recent log seems to result from the minecolonies file to be named .zip and not .jar

`minecolonies-universal-1.10.2.zip` needs to be `minecolonies-universal-1.10.2.jar`

**Comment by Raycoms** [comment]
Yeah I researched it and it has to be a jar but it has to be in a zip
format. We're currently researching why the jar hasn't been recognized
correctly. May you try to download it again, maybe something went wrong
downloading it.

2016-09-15 13:07 GMT-03:00 Marvin Hofmann <notifications@github.com>:

**Comment by MrVirtualis** [comment]
I'll try when I'm back in a few hours. But when I start it on SSP it works. And I uploaded my local file to the server.

**Comment by MrVirtualis** [comment]
Well. I don't know what went wrong, but reuploading the file to the server did the trick.
Thanks for the help. I'll keep you updated if I run into any other problems :)

**Comment by Kostronor** [comment]
Alright, closing this then

**Comment by Raycoms** [comment]
Error located, will probably upload a fix today.

2016-09-15 18:08 GMT-03:00 Marvin Hofmann <notifications@github.com>:
