### ISSUE TITLE
[bug] TownHall_block disappearing

### ISSUE THREAD

**Issue by MrVirtualis** [Minecolonies/minecolonies#130]
### Minecolonies version
SMP v0.4.3.2 // MC 1.10.2 // Forge 2086

### Expected behavior
Rightclicking on TownHall_block after placing it should open a GUI.

### Actual behaviour
TownHall_block disappearing. Trying to place another TownHall results in a msg: Too close to existing TownHall.

### Notes
1. In SSP this issue does not exist.
2. I created a new world with only one mod: minecolonies.

**Comment by Kostronor** [comment]
Can you post client and server logs for when the block disappeared?

**Comment by MrVirtualis** [comment]
[logs.zip](https://github.com/Minecolonies/minecolonies/files/475591/logs.zip)

**Comment by Raycoms** [comment]
Fixed the problem, will upload the fix in a moment.

**Comment by MrVirtualis** [comment]
Now the server crashes as soon as I place the TownHall_block.

[crash-2016-09-16_01.07.54-server.txt](https://github.com/Minecolonies/minecolonies/files/475778/crash-2016-09-16_01.07.54-server.txt)

**Comment by Towsty** [comment]
Problem exists again in the latest version [0.4.4.2].

Error @ line 26332 in attached log.
[fml-server-latest.txt](https://github.com/Minecolonies/minecolonies/files/478268/fml-server-latest.txt)

**Comment by Kostronor** [comment]
@Towsty try Minecolonies v0.4.4.5

**Comment by Towsty** [comment]
Thanks @Kostronor, works great now.
