### ISSUE TITLE
Supply ship not working

### ISSUE THREAD

**Issue by damew** [Minecolonies/minecolonies#134]
### Minecolonies version
v0.4.4.1

### Expected behavior
let me place the first ship in a new world(creative changed to survival, bonus chest, default, re-created).

### Actual behaviour
It said i had place one already

### Steps to reproduce the problem
Create new world craft or spawn supply ship, try place in water or land, and it will said that you have place one already.

**Comment by Raycoms** [comment]
Can you give us more details?
- Do you use any additional mods?
- Are you running it on the server or client?

2016-09-16 18:51 GMT-03:00 damew <notifications@github.com>:

**Comment by Raycoms** [comment]
Localized the problem, can you please turn in your config "infinite
supplychests" to true as a workaround.

2016-09-16 19:07 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:
