### ISSUE TITLE
Warehouse level 3 orientation bug

### ISSUE THREAD

**Issue by Sirius708** [Minecolonies/minecolonies#136]
### Minecolonies version
1.8.9-0.4.805 (Minecolonies Testpack v0.4.7)

### Expected behavior
Updgrading the Warehouse from level 2 to 3 should keep the orientation of the building.

### Actual behaviour
Upgrading the Warehouse from level 2 to 3 rotates the building by 90 degrees and upgrading from 3 to 4 rotates the building back to its original orientation.

Seems to be a problem with the schematic, because when using the building tool, each orientation of the Warehouse level 3 is oriented 90 degrees further.

### Steps to reproduce the problem
Upgrading the Warehouse from level 2 to level 3.

![2016-09-17_22 03 45](https://cloud.githubusercontent.com/assets/10850094/18610738/eb08b2f8-7d23-11e6-8359-b4ad7431fffd.png)
![2016-09-17_22 04 49](https://cloud.githubusercontent.com/assets/10850094/18610739/eb279e5c-7d23-11e6-8e74-ff4964a82175.png)
![2016-09-17_22 07 12](https://cloud.githubusercontent.com/assets/10850094/18610740/eb31c062-7d23-11e6-8e61-fcb584d78a60.png)
![2016-09-17_22 09 32](https://cloud.githubusercontent.com/assets/10850094/18610741/eb371652-7d23-11e6-9b5f-db9eeffe6a8a.png)

**Comment by Raycoms** [comment]
Thank you for reporting this bug.
Unfortunately the warehouse hasn't been implemented fully yet.
Please don't build it.
