### ISSUE TITLE
Crash with 0.4.821 (Models issue)

### ISSUE THREAD

**Issue by m31317015** [Minecolonies/minecolonies#138]
### Minecolonies version
0.4.821
### Expected behavior
Open normally
### Actual behaviour
Crashed along with this crash log:
[Click me](http://pastebin.com/swUCg3dX)
### Steps to reproduce the problem
Open minecraft.

**Comment by SDUBZ** [comment]
also got crash with this version:
crashlog:
[crash-2016-09-18_17.00.56-client.txt](https://github.com/Minecolonies/minecolonies/files/478573/crash-2016-09-18_17.00.56-client.txt)
