### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by NutBurger** [Minecolonies/minecolonies#139]
### Minecolonies version
Minecolonies v0.4.4.4
[crash-2016-09-18_16.57.56-server.txt](https://github.com/Minecolonies/minecolonies/files/478809/crash-2016-09-18_16.57.56-server.txt)

### Expected behavior
Town hall spawn citizens.

### Actual behaviour
Forge server v1.10.2-12.18.1.2092 crashes instead of spawning.

### Steps to reproduce the problem
Place town hall and wait for citizens to spawn which then crashes the server.

**Comment by Kostronor** [comment]
@Raycoms did we fix this already?

```
java.lang.NoSuchMethodError: com.minecolonies.entity.EntityCitizen.func_184227_b(D)V
	at com.minecolonies.entity.EntityCitizen.<init>(EntityCitizen.java:155)
```

**Comment by Raycoms** [comment]
yeah that's when you mix up world.isRemote.

Fix will be online within an hour

2016-09-18 13:14 GMT-03:00 Marvin Hofmann <notifications@github.com>:
