### ISSUE TITLE
Build Tool rework [$5]

### ISSUE THREAD

**Issue by Raycoms** [Minecolonies/minecolonies#145]
The build tool should need a rework.

The current folder handling is pretty complicated, players have to put new schematics inside the jar.

The enhancement:

We deliver a certain amount of schematics with the mod inside the jar.
On installation, these will be extracted into the root folder of the game. (Next to the resource pack folder).

There will be the following folders (More folders may be added dynamically, the build tool has to work with this): "BuildingThemes" and  "Decorations"

The BuildingThemes folder will contain all kinds of themes for the colonies - More may be added, and folders may contain 0 - all buildings to work.

The Decoration folders also has subFolders for the type of decorations. More may be added so that the player doesn't have to click through all the decorations to get to the ones he wants.

Standard ones should be: "Buildings", "Fields", "Walls", "Infrastructure", "Misc"

When a player scans in a decoration (Recognized by the missing buildingBlock) it will be added to the Misc folder.

When we then send the buildOrder for the builder, we should be able to select the schematics out of these folders to get him going.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41624377)](https://www.bountysource.com/issues/41624377-build-tool-rework?utm_source=41624377&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by cltnschlosser** [comment]
You can't make a resource pack?

**Comment by Raycoms** [comment]
I didn't understand the question.

**Comment by pmardle** [comment]
Yes to folders for decorations,

I'm not sure things like Fields should be classed as a decoration really, as they effectively have a hut block (scarecrow).

I would like somehow, decorations, defences (walls, towers), infrastructure (roads & bridges) and Huts (Colony Buildings) - to somehow all be on the same level.

So when you open the build tool GUI, you are just presented with a nice list of all these possible groups (Plus any player made directories of groups) - without any preselection based on your inventory.  Then when you click on the relevant button it takes you to that directory (Or sub directory List) - So style pack level in the case of colony buildings, or player made sub folders for decorations and such.

Then when you are in the style or decorations folder with schematics it then shows you a list of those schematics to chose from (except for huts which just gives the basic options based on chest in inventory.)

So Build Tool -> Main directory list -> Sub directory List --> Schematics.

Obviously There should be a "Scans" folder there as well so all scannned schematics appear in 

Build Tool - Scans

And the player can out of game re-name and save them in whatever folder they choose. (assuming it's not located in the .jar here)

**Comment by Kostronor** [comment]
The farm has to be a decoration or its own type but not a hut. Huts have limited levels, so if we don't want to have farm lvl1-4 we should use decorations for different farm styles. And the Scarecrow is not exactly a hut block 😜

**Comment by pmardle** [comment]
Have a fields folder like decorations then :)  - this can also have the "animal Fields" when we get to that too

**Comment by pmardle** [comment]
BTW Instead of a scarecrow in the animal fields we should use a water trough

**Comment by xavierh** [comment]
Should we close that ?

**Comment by Raycoms** [comment]
yeah please

2017-05-01 7:46 GMT-03:00 xavierh <notifications@github.com>:

**Comment by xavierh** [comment]
Sort of done
