### ISSUE TITLE
Let citizens avoid water.

### ISSUE THREAD

**Issue by Raycoms** [Minecolonies/minecolonies#147]
Improve PathJobMoveToLocation and PathJobMoveAwayFromLocation to recognize when they're in water and then allow swimming, else avoid pathing into water.

Create a new pathJob for idling:
- DomputeHeuristic() -> return 0 if not a swimming node, otherwise return a largish value (like 1000)
- isAtDestination should never return true if it is a water node
- isAtDestination -> check if distance greater than desired minimum, do random roll, if success then return true.

Use the setAllowedSwimming and isAllowedSwimming inside the AbstractPathJob.

**Comment by marvin-bitterlich** [comment]
@Raycoms are we already doing this?

**Comment by Raycoms** [comment]
No

**Comment by Raycoms** [comment]
I think we're doing that with @cltnschlosser latest pr now as well.
