### ISSUE TITLE
Add ingame books [$5]

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#15]
Use ingame books to explain workers and add documentation

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=36918856)](https://www.bountysource.com/issues/36918856-add-ingame-books?utm_source=36918856&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Kostronor** [comment]
https://github.com/SlimeKnights/Mantle could help us as a book library

**Comment by Kostronor** [comment]
codemill$10

**Comment by asiekierka** [comment]
Have you looked into https://minecraft.curseforge.com/projects/guide-api ? It might be an easy way to solve your issue.

**Comment by marvin-bitterlich** [comment]
That is also a good idea!

**Comment by Wissi** [comment]
@Kostronor Well I think the book I made is working seemlesly with 1.11 thanx to Asherslab. 
And with 1.10.2 if distributed thru config folder. 
Is that enough to close this issue?

**Comment by marvin-bitterlich** [comment]
yes that is perfect!
