### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#153]
We need some serious profiling feature to detect lag spikes.

Everything that runs on the server thread should be profilable.

We need:
- [ ] Easy static helper functions that allow profiling everywhere
- [ ] Nested profiling for depending functions
- [ ] Different log files generated automatically for spikes
- [ ] Average file for everything on request

**Comment by cltnschlosser** [comment]
Use the built in minecraft profiler

**Comment by Kostronor** [comment]
@cltnschlosser 

1. how do we do that?
2. I checked it and it does not do what I need it to 😆

**Comment by Kostronor** [comment]
We can use a jvm profiler for now
