### ISSUE TITLE
Builder asking for "Wooden Slab" which does not exists anymore in 1.10.x (which exist is "XXXXXX wood slab"...

### ISSUE THREAD

**Issue by jonabrv1965** [Minecolonies/minecolonies#154]
Where XXXXX could be any vanilla wood type, such as oak, birch,  etc.)

I'm trying to finish the 3rd tier of the TownHall, the builder asked me for slabs in the past with no issues (as a matter of fact in the past he asked specifically for "oak wood slabs"), but now he asks for a "Wooden Slab" and does not recognize the available wood slabs as such (I provided him with oak wood slab, birch wood slab, spruce wood slab, dark oak wood slab, jungle wood slab and acacia wood slab, not to avail)
### Steps to reproduce the problem : I'm playing in survival, have not the resources to reproduce this creating another colony... :-(

Nevertheless amazing Mod, very nice concept!!

**Comment by Raycoms** [comment]
You are probably building the townHall level 2.
It seems like there is one of these wooden slabs inside the supplyship (As
a workaround)
We have to rescan some of the buildings and will soon update them also for
1.10.

2016-09-20 17:05 GMT-03:00 jonabrv1965 <notifications@github.com>:

**Comment by jonabrv1965** [comment]
Hi Ray,you are right, it was 2 tier. I "destroyed" the entire colony, recover the materials, and recreate the town hall, same problem, but yes, at tier 2. I will look for this at the supplyship, but I do not think this work. As I mention 1.10.x does not have a block named "Wooden Slab" in its dictionaries... (so when  pick a slab it will be converted automatically to its equivalent in the new version AFAIK) Ah.. thank yuo for the promptly answer... 

By the way how big should be the "fields" for the farmer begins to work? (I already have it in a middle of a 32x32 of totally plain grass but keeps yelling for more "fields" :-)

**Comment by Raycoms** [comment]
PickBlock actually used the wrong block from the previous versions (I
tested it).

You have to place the fieldBlock (It's a scarecrow) and place it inside
this field you created.

2016-09-20 19:40 GMT-03:00 jonabrv1965 <notifications@github.com>:

**Comment by jonabrv1965** [comment]
It works! now I've my tier 3 town hall, beautiful design! thx!!

**Comment by jonabrv1965** [comment]
when demolished the boat I got 7 wooden slabs (without texture)...

**Comment by Kostronor** [comment]
we have new schematics now
