### ISSUE TITLE
Powerful/Enchanted tools seems not being used at full potential by workers 

### ISSUE THREAD

**Issue by jonabrv1965** [Minecolonies/minecolonies#155]
I gave a powerful axe (faster than diamond, efficiency 5, silk touch, unbreakable) to the builder and the chopping is comparable to a vanilla iron axe (when I use this very same axe, can remove an entire house in less than a minute)... is this intended? Same for the miner....

**Comment by Kostronor** [comment]
He is using the tool with all enchanting and stuff. Try a normal iron axe instead, it will be way slower. 

Your citizens have to level up to fully utilize the power of your tools
