### ISSUE TITLE
Warehouse upgrade not removing old blocks

### ISSUE THREAD

**Issue by tipilu** [Minecolonies/minecolonies#156]
### Minecolonies version
1.10.2-0.4.828

### Expected behavior
Upgrade warehouse to max level, deleting old blocks when building upgraded warehouse

### Actual behaviour
Final, upgraded warehouse is built, but some part of unupgraded warehouse is still there.

### Steps to reproduce the problem
Upgrade warehouse to max level.

Also it seems like somehow 2nd or 3rd upgrade wrongly recognizes directions, because it changed my door position to side, and after final upgrade, those doors were filled with stone and original doors appeared in front again.
![2016-09-22_17 35 28](https://cloud.githubusercontent.com/assets/21001212/18755268/d7c0deca-80eb-11e6-9cea-a5ff9b452377.png)

**Comment by Kostronor** [comment]
The same as #136 warehouse is *not supported*
