### ISSUE TITLE
Miner bug when building mineshaft

### ISSUE THREAD

**Issue by tipilu** [Minecolonies/minecolonies#157]
### Minecolonies version
1.10.2-0.4.828

### Expected behavior
Miner should use oak wood slabs to build next level of mineshaft. He should take oak wood slabs from his chest.
### Actual behaviour
Miner doesn't recognize oak wood slabs in his chest, making him unable to continue mining.
### Steps to reproduce the problem
Build miner, wait for him to clear 1st level of ground forcing him to start building mineshaft.
![2016-09-22_17 47 31](https://cloud.githubusercontent.com/assets/21001212/18755601/27a730b4-80ed-11e6-9f7f-fa2785e7ce05.png)

Edit: Right after giving him oak wood slabs, he got stuck on Oak Fence. This time even fence gaven him directly to his inventory doesnt make him using it, causing him to get stuck.

**Comment by Kostronor** [comment]
Thanks for submitting this bug report.

We are currently reworking our inventory handling code. Can you try this version: http://mc.kk-sc.de/branches/150/minecolonies-universal-1.10.2-0.4.907.jar and report back if the issue still exists?

**Comment by tipilu** [comment]
With updated mod he started to use his inv items and torches/cobblestones from chest. Will report again if he gets stuck on taking items from chest again.

**Comment by Raycoms** [comment]
Should be fixed with the update I made to the building synch.
