### ISSUE TITLE
Various townhall interactions may found a colony

### ISSUE THREAD

**Issue by Raycoms** [Minecolonies/minecolonies#159]
### Minecolonies version

Any
### Expected behavior

Found the colony only if the townhall has been placed.
### Actual behaviour

Colony may be founded by accidental clicks.
### Steps to reproduce the problem

Right click a chest with a townhall, or set a townhall in an itemRack.

**Comment by Isfirs** [comment]
Shall I?

**Comment by Raycoms** [comment]
I already analyzed that once, and it's not that easy as it seems.
Because our whole colony founding code is in the on place and not in the
"afterPlace". Because it has to check first if it can found the colony and
then may found it.

There are several ways to go imo.
- The colonyManager will save it as a "founding attempt" and will check
after a delay if the block has been placed. If yes found the colony if not
don't.
- Somehow return "can colony be founded" back to the placingCode. Store it
there and hand it somehow to the "afterPlacement".

2016-11-09 14:25 GMT-02:00 Isfirs <notifications@github.com>:

**Comment by neadlak** [comment]
Raycoms asked me to test this, was given a link to version ending 0.6.2010

1) Set townhall in itemrack: Did not create colony.
2) Rightclick chest with town hall: Did not create colony.
3) Placed townhall (rightclick in world): Created a colony. Could not interact with town hall block. No citizen spawns, but colony entry in minecolonies.dat was initialized
4) Broke townhall block
5) Placed townhall (using builder's wand): Could interact properly. Citizens started spawning.

6) Fresh world, placed townhall with builder's wand: Colony created, proper interaction etc.

Tested in SSP, minecolonies testpack 0.484 with minecolonies 0.6.2010.

**Comment by Raycoms** [comment]
thanks I have to check the rightclick yet.

2016-12-11 22:58 GMT-02:00 neadlak <notifications@github.com>:

**Comment by neadlak** [comment]
Right click only creates a colony if it places the TH block. It will create without using build tool, but not be functional.

Just repeated tests on my SMP (forge 2099, testpack 0.484 minecolonies 0.6.2010) and same results.

Also tried with bed: Rightclicking (with TH in hand) on bed did not trigger the achievement.

Using build wand to look at a template: Did not trigger achievement.

Confirming placement in build wand: Places TH block, achievement fires.

**Comment by Raycoms** [comment]
fixed that.

2016-12-11 23:28 GMT-02:00 neadlak <notifications@github.com>:
