### ISSUE TITLE
Warehouse lvl 3 schematic fault

### ISSUE THREAD

**Issue by Cheef83** [Minecolonies/minecolonies#162]
0.4.907 Minecolonies version

During upgrade from lvl 2 warehouse to lvl 3 the building undergoes a 90 degree rotation, causing the front door to be on the wrong side, on a further upgrade to lvl 4 warehouse it rotates back to its original orientation. This causes some chests inside to break and all items thrown out as well as some ugly leftover building each time its upgraded.

![2016-09-25_22 02 14](https://cloud.githubusercontent.com/assets/22434230/18818241/84bd43d4-836c-11e6-874b-b36e76beb89d.png)
![2016-09-25_22 06 04](https://cloud.githubusercontent.com/assets/22434230/18818243/8d132148-836c-11e6-84a3-28514452a101.png)

These are the results from the upgrades and what is left behind.

I have been unsuccessful in editing the schematics myself (most likely due to a lack of understanding of how they are implemented into minecolonies.

**Comment by Kostronor** [comment]
Duplicate #136 #156
