### ISSUE TITLE
Deliveryman stuck in idle stage

### ISSUE THREAD

**Issue by Tufda** [Minecolonies/minecolonies#172]
### Minecolonies version
0.4.18

### Expected behavior
Deliveryman storing resources, and giving workers resources

### Actual behaviour
Stands around doing nothing and being stuck in the (WORKING) (IDLE) stage.

### Steps to reproduce the problem
Build a warehouse. That's what I did.

I tried recalling the worker, but that doesn't seem to fix the problem.

Image:
![Image](http://tufda.net/downloads/explore/helpminecolonyteam.png)

[Download map file](http://tufda.net/downloads/explore/MineColony.zip)

**Comment by Kostronor** [comment]
Deliveryman is not implemented, please don't use him.

Related: #162 #156 #136
