### ISSUE TITLE
/rtp command on server not teleporting

### ISSUE THREAD

**Issue by LeviGage** [Minecolonies/minecolonies#175]

**Comment by Kostronor** [comment]
Any info? Also this is not support for the server.

**Comment by LeviGage** [comment]
Oh, sorry. In the server it said to got to Minecolonies.com to report a bug. I went to Bug Reports and here we are... :/ 

Just got into the server and get off spawn.

**Comment by Kostronor** [comment]
/rtp is not the minecolonies mod. It is from nucleus. But try again some more till it finds a suitable place. You may be just unlucky

**Comment by LeviGage** [comment]
ok. Thanks.
