### ISSUE TITLE
Citizen stuck on fence

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#177]
### Minecolonies version
develop
### Expected behavior
Citizen walks down from fence
### Actual behaviour
Citizen spins on the fence and goes nowhere
### Steps to reproduce the problem
Place fences with stairs on one side and watch citizens get trapped

**Comment by cltnschlosser** [comment]
This is a bug with minecraft locomotion

**Comment by Kostronor** [comment]
Then we have to stop our citizens from even going on top of fences, we can consider their top block solid

**Comment by Raycoms** [comment]
Calm down lads, fix is coming in.

2016-10-07 9:44 GMT-03:00 Marvin Hofmann <notifications@github.com>:
