### ISSUE TITLE
Teleport to Colony [$5]

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#184]
Admins and Members of a colony should be able to teleport to their townhall.

We should make this configurable for server admins to allow it or not. 

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41624375)](https://www.bountysource.com/issues/41624375-teleport-to-colony?utm_source=41624375&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Dimentive** [comment]
How do you teleport to a colony?
