### ISSUE TITLE
Delete Colony

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#185]
Admins and Colony owners should be able to delete their colony.

This should be a command. It may be added to the townhall gui in a danger zone.

**Comment by Isfirs** [comment]
Can't we display a tab in Townhall GUI **only** for `>= Owner`?

**Comment by Kostronor** [comment]
That would be the danger zone then?

**Comment by Raycoms** [comment]
I'd do it with commands, owner or admin can use the command.

**Comment by Kostronor** [comment]
A gui for players would be really nice imo still

**Comment by Raycoms** [comment]
We can render a owner only button without any problems

Am 14.10.2016 07:29 schrieb "Marvin Hofmann" <notifications@github.com>:
