### ISSUE TITLE
Miner voiding items?

### ISSUE THREAD

**Issue by jengeld4** [Minecolonies/minecolonies#188]
### Minecolonies version
universal-1.10.2-0.4.1033
### Expected behavior
I think the Miner should be mining everything and returning it to the chest. 
### Actual behaviour
Miner seems to keep the important things (iron), but seems to be voiding cobble (and possible other items). Occasionally sends out message requesting more cobble to patch holes. 
### Steps to reproduce the problem
Not sure if this is intentional or not, but it seems to happen with any miner I hire.

**Comment by Kostronor** [comment]
The miner has to use cobble to patch holes. I think you answered yourself where all the cobble goes ;)
