### ISSUE TITLE
Can't access the villagers "boxes" after leaving game and rejoining.

### ISSUE THREAD

**Issue by Makin91** [Minecolonies/minecolonies#190]
### Minecolonies version

2-0.4.1042
### Expected behavior

Can access my the boxes
### Actual behaviour

Can't access the boxes
### Steps to reproduce the problem

i have quite a large amount of mods in my list

the village seems to work like normal i just loose access to it. by the boxes i mean like the town hall, miner and saw mill etc.

**Comment by Kostronor** [comment]
Did you change your username?

**Comment by Makin91** [comment]
No, but i could recreate this bug everytime i started a new world and left the client

**Comment by Kostronor** [comment]
We would need the full forge log of both starts then.

**Comment by Makin91** [comment]
i went trough them and this happened ALOT 
"[04:38:48] [Netty Local Client IO #0/ERROR] [minecolonies/]: Colony view does not exist for ID #1"

**Comment by therealericbj** [comment]
[latest.zip](https://github.com/Minecolonies/minecolonies/files/530741/latest.zip)
I am experiencing the same issue, from time to time.

To reproduce the issue...  ...just start my single-player game as usual.

The error happens about 40% of the time.

Mod version - 1.10.2 - 0.4.1042, but has happened in a few previous versions.  I don't have the version numbers, Sorry!

Here is my complete log.  I just stated the game, loaded the world, saw that I had the problem, then turned off the game.

**Comment by Kostronor** [comment]
Closing as not being able to reproduce it

**Comment by midorlo** [comment]
I am experiencing this exact bug right now. Started SMP, 2 players. Played a while and closed the server. Started the server and wasnt able to access any colony frontend or talk to any colony NPC. I'm getting tons and tons of netty entries:

     [18:39:20] [Netty Local Client IO #0/ERROR]: Colony view does not exist for ID #1

**Comment by Raycoms** [comment]
Have you used the /mc colony delete command during the game?

2017-03-25 14:41 GMT-03:00 netzgeist <notifications@github.com>:

**Comment by midorlo** [comment]
No. I just played the mod with default configs and build a single colony with (yet) 3 buildings). The game context is LAN-SMP with 2 players connected. The other player has the officer rank assigned and is still able to use the colony features.

**Comment by Raycoms** [comment]
okay then execute /mc colony refresh 1

2017-03-25 14:46 GMT-03:00 netzgeist <notifications@github.com>:

**Comment by midorlo** [comment]
Just did. It says "Refresh succesfull!". I am still unable to interact with the content and get the same netty msg back.

**Comment by Raycoms** [comment]
OKay your friend is able to interact? /mc colonies list and /mc colony info
does what?

2017-03-25 14:49 GMT-03:00 netzgeist <notifications@github.com>:

**Comment by midorlo** [comment]
Yes, she is still able to interact. 

list:

    [19:01:18] [Client thread/INFO]: [CHAT] ǲ   ------------------ page 1 of 1 ------------------
    [19:01:18] [Client thread/INFO]: [CHAT] ǲID: Ȧ1 ǲ Name: ȦNetzgeist's Kolonie
    [19:01:18] [Client thread/INFO]: [CHAT] ǲCoordinates: ȦǴx=Ȧ-485 Ǵy=Ȧ63 Ǵz=Ȧ-29
    [19:01:18] [Client thread/INFO]: [CHAT] ǲ ---------------- <- prevǲ | next -> ǲ ----------------

info:

    [19:03:45] [Client thread/INFO]: [CHAT] ǲID: Ȧ1ǲ Name: ȦNetzgeist's Kolonie
    [19:03:45] [Client thread/INFO]: [CHAT] ǲMayor: ȦNetzgeist
    [19:03:45] [Client thread/INFO]: [CHAT] ǲCitizens: Ȧ4/4
    [19:03:45] [Client thread/INFO]: [CHAT] ǲCoordinates: ȦǴx=Ȧ-485 Ǵy=Ȧ63 Ǵz=Ȧ-29

edit: note that the charset artifacts are only logwise. The ingame formatting is valid.

**Comment by Raycoms** [comment]
Have you tried restarting?

2017-03-25 15:04 GMT-03:00 netzgeist <notifications@github.com>:

**Comment by midorlo** [comment]
Ehm no >_<. /refresh'ing AND restarting just solved the issue. My humble thanks to you for taking the time. If I can provide you with any useful data for future debugging, please instruct me. Else I wish you a nice weekend!

**Comment by Raycoms** [comment]
Sorry for the inconvenience, sometimes when closing the game or leaving the chunk data is getting lost about the colony owner. We don't now yet what causes this.
Refreshing often solves that. Else refreshing and restarting usually does it for sure.

Have fun playing.

**Comment by VOiDProXy** [comment]
I'm sad to report that this happens 2 out of 3 times on my server. It's very unreliable and doesn't make sense to me. Even though the minecolonies folder data is identical and seemingly uncorrupted, the server just simply seems to forget it all.

Sometimes, the colonies have vanished. Sometimes they're available. if they're still in the world they often have no citizens or people can't open the interfaces. A colony refresh used to fix it but now it seems like it doesn't work anymore. It's a fun mod however and I hope we can squish this bug eventually.

**Comment by LordOfDaVoid** [comment]
This just happened to me on the 1.10.2 version, however I was able to access the mine but not the Town Hall and the house closest to it, so I think that it is chunk based. The current method of fixing it still worked though.
