### ISSUE TITLE
Can place supply boats close to each other, now stuck not being able to place townhall

### ISSUE THREAD

**Issue by dmb1881** [Minecolonies/minecolonies#192]

**Comment by Raycoms** [comment]
You can place your townhall far away from your supplyship. I don't get the
problem =D

2016-10-10 21:09 GMT-03:00 dmb1881 <notifications@github.com>:

**Comment by dmb1881** [comment]
The issue comes in where i have to place it really far away... I think this could be easily fixed if there was some sort of re-package system or if the game prohibited you from placing the supply boats close to one another...

**Comment by Raycoms** [comment]
Sometimes you want to have your supplyship close to your friends one.
In F3 you can see if there is a colony close and if you can place it.

2016-10-10 21:15 GMT-03:00 dmb1881 <notifications@github.com>:

**Comment by dmb1881** [comment]
Then just add a simple way to re-package the supply ship, so people who make this mistake can move the ship.

**Comment by Kostronor** [comment]
The thing with repackaging is ensuring that the ship was not modified or people could cheat resources. What should we do if someone took a bed and forgot where to put it back?

**Comment by dmb1881** [comment]
Why not just have an update system where if the player breaks/places a certain block, it updates anything within the radius of the ship to package with it? Or have a system where you have to abandon ship instead of being able to repackage it?

**Comment by Kostronor** [comment]
Because we then would have to store each players ship on the server for him. 

Abandon would still suffer from the same problem of removing blocks later.

**Comment by dmb1881** [comment]
There needs to be some way to do it... Its really annoying because I want to be able to move my ship because I placed it way to close to another settlement.

**Comment by Kostronor** [comment]
We are too looking for a way to realize this but all ways we thought of are not working out

**Comment by dmb1881** [comment]
Perhaps a system where you have like a friendslist, and make it where only your friends can place supply boats and other extraneous items close by?

**Comment by Kostronor** [comment]
That would be a good idea @Raycoms we could block it in range and allow it for players who are at least friendly to the colony

**Comment by Raycoms** [comment]
You'll be able to place the ship as a decoration now.
Just mine your ship and use the resources to have your builder place it again.
