### ISSUE TITLE
List citizens

### ISSUE THREAD

**Issue by Raycoms** [Minecolonies/minecolonies#196]
We should have a way to list the citizen.

**Comment by Isfirs** [comment]
May do it by subcommands to prevent an overflow of commands

`/mcolonies` as our scope.

`/mcolonies citizens [<Colony ID>]` should deliver citizen list of nearest colony with **Officer** permission OR own Colony.

`/colonies citizen <ID>` should print detailed information of 1 citizen.

`/mcolonies citizen kill <ID>` speaks for itself.

`/mcolonies colonies [<Page>]` prints like 5 or 6 colony names, plus a `<Current Page>/<Max Pages>` pagination (prevent overflooding).

Do we want leak information about location?

So, maybe `/mcolonies colony direction <Colony ID>` can print `Colony ABCDEF is to the <Direction>`, where `Direction` is something like `N`, `S`, `E`, `W`, `NE`, `SE`, etc.

`[]` means optional.

**Comment by Kostronor** [comment]
I suggest `/mc` its not used and short.

**Comment by Isfirs** [comment]
I wouldn't use it, as it is an abbreviation of `minecraft` already.

**Comment by Kostronor** [comment]
Then we use:
`/mc -> /mcolonies -> /minecolonies`

**Comment by Isfirs** [comment]
You mean aliases?

**Comment by Kostronor** [comment]
Yeah

**Comment by Kostronor** [comment]
Splitting this into multiple issues
