### ISSUE TITLE
Limiting the colony name to 25 characters

### ISSUE THREAD

**Issue by nojo121** [Minecolonies/minecolonies#204]
We should set a limit of 25 chracters for colony names.
This would be useful to prevent bugs from happening.

![](https://cloud.githubusercontent.com/assets/17111591/19408421/cefc1592-92bc-11e6-8a3e-8a3f097c48e6.PNG)

**Comment by Kostronor** [comment]
Malicious users could lag the server by making their colony name huge and therefore require all players to download it.

**Comment by nojo121** [comment]
we should limit it to 28 characters because in the colony GUI there only fit 28.
![colony gui](https://cloud.githubusercontent.com/assets/17111591/19408421/cefc1592-92bc-11e6-8a3e-8a3f097c48e6.PNG)

**Comment by Kostronor** [comment]
I'd say 30 because mc font is not monospaced and an i or ' will be enough to pull the two extra characters back.
