### ISSUE TITLE
I keep getting already placed town hall when I've already destroyed it

### ISSUE THREAD

**Issue by Madnessfan** [Minecolonies/minecolonies#206]
### Minecolonies version
minecolonies-universal-1.7.10-0.0.15.jar 
2016-01-25
	
### Expected behavior
I tried to move my town hall by placing it by destroying it and playing it elsewhere.
### Actual behaviour
The game wouldn't allow me to place the town hall again, so I can't build up my village. I'd love for the mod to be fixed for 1.7.10 since there are many mods that have been discontinued since version 1.7.10.
### Steps to reproduce the problem
Destroy the town hall and try placing it again.
![2016-10-15_14 38 21](https://cloud.githubusercontent.com/assets/22861151/19413543/12777adc-92e5-11e6-8e60-274679b8ba2c.png)

**Comment by Raycoms** [comment]
That's not a problem. You can't remove your colony yet, you only may move
the townhall position. (In all versions)

2016-10-15 18:47 GMT-03:00 Madnessfan <notifications@github.com>:

**Comment by Madnessfan** [comment]
I can't get anything to work without a town hall since I already destroyed it

**Comment by Raycoms** [comment]
You can place it again inside the area you first placed it.

2016-10-15 20:03 GMT-03:00 Madnessfan <notifications@github.com>:

**Comment by Madnessfan** [comment]
I can't place it in the same spot, and I can't place a new one even in a new world

**Comment by Kostronor** [comment]
That feature was implemented in a future version. We discontinued 1.7.10 a long time ago, sorry.
