### ISSUE TITLE
Little bugs with the Farmer

### ISSUE THREAD

**Issue by Nezraddin** [Minecolonies/minecolonies#207]
### Minecolonies version
- Minecolonies-universal-1.10.2-0.4.1080

Actually two little bugs:

First Bug
### Expected behavior
- Torches in Tier 1 Farmer-Building
### Actual behaviour
- Builder places no torches in tier 1 farmer building (guess they were forgotten in the building)

Second Bug:
### Expected behavior
- Farmer should take seeds from the farmer-building's inventory
### Actual behaviour
- At the moment it seems the farmer ignores all slots of the building's inventory but the first.
  I did put 2 stacks of seeds into the inventory, but the farmer only took the stack in the first slot and completly ignored the second slot, even he still had lots of space to plant them.

**Comment by Kostronor** [comment]
Can you show us a Screenshot of your farmer building at night? Have you tried upgrading/reparing it? 

Did the farmer used the extra free space after harvesting more seeds? Or did he ignored it even after gathering more?

**Comment by Raycoms** [comment]
He only plants one stack of seeds per time, so that he isn't too op.
And yeah I think the level 1 torches were forgotten

2016-10-16 11:46 GMT-02:00 Marvin Hofmann <notifications@github.com>:

**Comment by Nezraddin** [comment]
The wanted screenshot:

![farmer night](https://cloud.githubusercontent.com/assets/10656694/19418020/bca68c74-93bb-11e6-9dfa-2680047dc399.png)

The little light which can be seen inside comes from the field (where i placed torches myself), the tier 1 farmer building itself has no torches, unless you place them yourself.
And it's only the tier 1, when upgrading to tier 2 the torches are placed by the builder.


About the seeds:
He took 1 stack and planted then all, but it was a 11x11 farm (minus 4 watersources and the scarecrow) so he had 52 places left which he tilled but didn't plant anything.
I tested now and took half the field away and spread the seeds in the entire inventory of the farm-building (so that slot 1 to 27 all had 1 seed to take) but he really only took the seed in slot 1 and ignored all others.

**Comment by Raycoms** [comment]
And yeah he only takes one stack of seeds but that's on purpose. The farmer is very very powerful and creates a huge amount of food already.

**Comment by marvin-bitterlich** [comment]
@Oggal @Raycoms is this still relevant?

**Comment by Raycoms** [comment]
Yes, Waiting for @Oggal still

**Comment by Raycoms** [comment]
I think that should be fixed already
