### ISSUE TITLE
Worker suddenly stop working

### ISSUE THREAD

**Issue by Nezraddin** [Minecolonies/minecolonies#215]
### Minecolonies version
- minecolonies-universal-1.10.2-0.4.1213 (modtest-modpack)

### Expected behavior
- Worker (in this case Lumberjack, fisher and Farmer) go back to work after visiting their buildings.

### Actual behaviour
- It seems the lumberjack, fisher and the farmer stop working after they visit their buildings.
- Miner seems to be fine (he still keeps digging down for creating more plattforms for me). 
- Builder only tested with infinite ressources yet, will edit when I tried it without that.

### Steps to reproduce the problem
- I tried firing and re-hiring both (lumberjack and farmer) and they go back to work, but as soon as they go back to visit their building they stop again and just stand around near their building.
- When starting the map (so going back to playing after cloing the map) it works for one time, too.

Kinda looks like the "go back to work"-command seems bugged. For the miner at least the platform-building down a y-level works. if he has problem with his actual mining-work then I don't know.

**Comment by Raycoms** [comment]
Is there maybe something that doesn't let them enter their buildings or is
there any monster close?

2016-10-19 19:40 GMT-02:00 Nezraddin <notifications@github.com>:

**Comment by Nezraddin** [comment]
No monster nearby and nothing that stops them from reaching their building-block.
Recalling them doesn't fix them, too.

Trying a new map now, maybe it's just the old map with updated minecolonies that got bugged. (will report as soon as I build the farmer)

**Comment by Kostronor** [comment]
We would need the forge logs of when that happens

**Comment by therealericbj** [comment]
[latest.zip](https://github.com/Minecolonies/minecolonies/files/541582/latest.zip)
I am experiencing just about the exact same problem.

The only difference I have seen is when I first discovered the problem, left the world, then came back, the workers, except the farmer, went through their routine once, then stopped.  They ended up just standing beside their box/chest.  The was it.

The lumberjack seems to leave me a lot of floating trees, but I doubt that is the same problem.

Anyway, here is my logs, hope it helps.

**Comment by Nezraddin** [comment]
Is that just the txt-file that is created in the "log"-folder or any special of whatever ends there?
(first time I'm asked for this kind of log ^^")

**Comment by Raycoms** [comment]
You could zip the most recent ones.

2016-10-20 12:00 GMT-02:00 Nezraddin <notifications@github.com>:

**Comment by Raycoms** [comment]
Okay I found the problem in "therealericbj" log. We have fixed that already
and will upload the fix in the next 24h!

2016-10-20 12:13 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by Nezraddin** [comment]
Alright, next time I try to remember about these logs :)

Thanks for your fast work, really love the mod so far! :D
