### ISSUE TITLE
{Server Issue} Some chunks not saving properly

### ISSUE THREAD

**Issue by UncleJimb0** [Minecolonies/minecolonies#216]
### Minecolonies version
Minecolonies Testpack v0.4.36 (release) 
### Expected behavior
Chunks should be saved, whereas buildings built by the builder NPC, should be saved from the point I leave the server, and continue as normal when I re-enter the server.
### Actual behaviour
Sometimes, random chunks don't save properly; where the building is missing but the placed Minecolonies block to represent a specific building, still exists. However, the block will not activate when right clicked on, and simply does nothing. The NPC that worked at that station also appears to be missing, but is still a citizen in the town hall. Ex: ![2016-10-19_22 02 32](https://cloud.githubusercontent.com/assets/22948748/19544000/824c17a2-9649-11e6-94bb-67165e3e2af9.png)
You can still see part of the mine on the right side built into the ground, but the other large portion is missing, but the block to represent a mine is still there, but does not work. This appears to only be an issue with minecolonies built buildings, and does not seem to affect, from my experience, user built buildings.
### Steps to reproduce the problem
This behaviour happens randomly, and it seems there is no way to reproduce this problem as a user.

**Comment by Dadadah** [comment]
I believe this is an issue caused by an external plugin and not Minecolonies itself (I hope).

**Comment by Kostronor** [comment]
This is not a minecolonies issue.

**Comment by UncleJimb0** [comment]
Was this issue already addresed? If so, what plugin do you suspect might be affecting this? This is just strange how this only happens with minecolony built buildings.

**Comment by Raycoms** [comment]
It happens with everything, you only notice it with the minecolonies
buildings. We suspect redprotect.

2016-10-20 9:41 GMT-02:00 UncleJimb0 <notifications@github.com>:
