### ISSUE TITLE
Miner destroys broken Tinker Construct tools when they run out of durability

### ISSUE THREAD

**Issue by LordHellscream** [Minecolonies/minecolonies#219]
### Minecolonies version
0.4.1080
### Expected behavior
Tinker construct tools do not get destroyed when they run out of durability, they simply become "broken" and can be repaired
### Actual behaviour
However when given a tinker construct pickaxe to the miner, when the durability rans out, it gets destroyed,
### Steps to reproduce the problem
give tinker construct pickaxe to the miner when they ask for it, and wait until it rans out of durability.

**Comment by Kostronor** [comment]
Thanks for reporting this.

While it is currently no high priority it is good to track mod support. We simply didn't found a way yet to tell Tinkers Construct that their tool is about to loose the last durability.

**Comment by LordHellscream** [comment]
May be just have the miner keep track of the tool and stop using the tool before it breaks?
You bet a lot of players r going to give miner the tinker tools (because its so popular), and would be really disappointed when they see its destroyed!
thanks!

**Comment by Kostronor** [comment]
We are investigating this and found out that Tinkers is just not telling us that the broken tool can't be used. We may check if it is a tinkers tool and then not use it but that feels like a bad hack...

So while we fix it for this one case, I'm actually not sure if we calculate tinkers mining speed stuff correctly 😆

**Comment by LordHellscream** [comment]
are you saying the miner will use the broken tool and that destroy it?

**Comment by Dadadah** [comment]
That was the case, but it will be fixed in the next update.
