### ISSUE TITLE
Slower than dirt digging, minning even with tools 

### ISSUE THREAD

**Issue by tiarnia** [Minecolonies/minecolonies#222]
### Minecolonies version
1.10.2-0.4.1358
### Expected behavior
tools making digging mining faster than with bare hand 
### Actual behaviour
the builder hits a piece of dirt 30 times with a diamond shovel to break it 
the miner hits cobble with iron pickaxe 30 times or more to break stone 
### Steps to reproduce the problem
happens constantly took 12 minecraft days for builder to dig hole for town hall 
the tool in hand seems to not matter at all as long as they have one they can break it slower than i can with my fist

**Comment by Kostronor** [comment]
That is intended behavior. 

Tools improve speed. Speed is slow at first. Wait for it to level up. If you are that impatient help him out.

**Comment by Raycoms** [comment]
The workers work pretty slow at the start and get faster over time.
We're still tweaking them every update to see how it's combining with the
other tasks.
Let him work for a while, help him at the beginning. (Don't let him build
the townhall as the first building).
And everything will be okay =)

2016-10-23 23:07 GMT-02:00 tiarnia <notifications@github.com>:
