### ISSUE TITLE
Renaming Town Hall/Colony will kick player from server

### ISSUE THREAD

**Issue by BSKCorp** [Minecolonies/minecolonies#223]
### Steps to reproduce the problem - not entirely sure. 

- Error from Server log: http://pastebin.com/hKEQyjB9

**Comment by Kostronor** [comment]
Damn sorry, seems my fixes brought that into life. 

Will be fixed next version, maybe @Raycoms knows what to do :-D

**Comment by BSKCorp** [comment]
All good, I love testing out the mods. My entire server is pretty much alpha and beta mods for 1.10.2. Keep up the good work.

**Comment by Raycoms** [comment]
Shouldn't happen anymore.
