### ISSUE TITLE
Crashing minecraft

### ISSUE THREAD

**Issue by Exchy** [Minecolonies/minecolonies#224]
###Minecolonies v0.4.7.5 

###At least launching minecraft

###Crashing after Forge scan on 5/7 Phase "Initializing mods". Fml marks the mod as UCHE (errored)
[fml-client-latest.txt](https://github.com/Minecolonies/minecolonies/files/551448/fml-client-latest.txt)

###For me is just launch minecraft. I dunno what causing that, I deleted everything from log file except error report, could you try to define what's wrong pls? This mod is also didn't work on me about a half-month ago

P.S. My server is launching with that mod, can't say if it's properly work due to I can't even launch my client to check it :D

**Comment by Raycoms** [comment]
Could you try to remove the coremods and then start it again? (coremods
often interfere with the libraries and may change a library our mod is
using - the schematica mod is using)

2016-10-25 16:26 GMT-02:00 Exchy <notifications@github.com>:

**Comment by Exchy** [comment]
Well. . . I found a problem you can close the thread, no core/mods are guilty for that, my fault, good day)

**Comment by Raycoms** [comment]
Would be good to know what the problem was if someone asks again =)

2016-10-25 17:08 GMT-02:00 Exchy <notifications@github.com>:
