### ISSUE TITLE
NPC Behavior - Builders

### ISSUE THREAD

**Issue by Captaindub242** [Minecolonies/minecolonies#230]
### Minecolonies version
Newest to date (1.10.2)
### Expected behavior
Building/Crafting
### Actual behaviour
I don't know if this is an actual bug (If so its a really small insignificant one) or if I just have to wait or something but, in the old version of mine colonies, the builders, if the resources are present, would craft and create the blocks/items they need (eg. signs,wooden/stone slabs,etc), though now they just seem to stand in their hut/building and  and wait until they get the item, instead of, well, crafting it. Again, don't know if this is a bug or just something that im not doing or hasn't been implemented yet, though I thought I would point it out.
### Steps to reproduce the problem
1. Just give them a build order (eg. Town-hall works best with all its different blocks and parts)
2. Wait until they need something of that nature, it'll happen at some point during the build.

**Comment by Kostronor** [comment]
Crafters are not implemented yet.

**Comment by Captaindub242** [comment]
I understand that, I just mean that in the old version of mine colonies (before the overhaul - which btw is looking pretty good), the builders on their own would craft the things that they require, say if they need sign, they would craft it on their own without any prompt or anything of that nature.

**Comment by Kostronor** [comment]
Yeah still a part of the material system and not implemented yet

**Comment by Captaindub242** [comment]
Oh OK, makes sence, well thanks for the help anyways.
