### ISSUE TITLE
Farm more things

### ISSUE THREAD

**Issue by Dadadah** [Minecolonies/minecolonies#235]
Farmer should be able to farm additional plant types.

IE. Pumpkins, melons, netherwart.

**Comment by AndrewTru** [comment]
if we do add this in we will need to make a new farm pathing class to account for it.
Pumpkins and Melons will need to have [dirt][grass] combo so as to account for the fact the crop itself is not on the dirt block but any block around said block.
the nertherwart however will need to have a farm area that is soul sand plus is light level 6 or lower
a building to block off the light but still allow the farmer to work inside it.
may have to add some kind of passable block that will not allow light in but allow mobs (farmer) and the player in.

**Comment by Raycoms** [comment]
Done
