### ISSUE TITLE
Hut's Contents

### ISSUE THREAD

**Issue by BoneyMC** [Minecolonies/minecolonies#241]
### Minecolonies version

4.61
### Expected behavior

To drop the contents in the hut when it is broken
### Actual behaviour

When the hut is broken the contents are forever gone
### Steps to reproduce the problem

Destroy a hut that has items inside

**Comment by Isfirs** [comment]
Kk, I will do that if possible.

Should be enough to have the same behavior as normal chests, right?

**Comment by Raycoms** [comment]
just have to edit the "onDestroyed" code. We have a method which removes it
from the colony if destroyed. Just "copy" the drop code in there as well.

2016-11-09 14:20 GMT-02:00 Isfirs <notifications@github.com>:
