### ISSUE TITLE
Mines disturbing each other

### ISSUE THREAD

**Issue by tomorrow4268** [Minecolonies/minecolonies#243]
### Minecolonies version

newest
### Expected behavior

Miner recognizing other mineshafts/mines and not filling them up with cobblestone when working/building tunnelsystems
### Actual behaviour

Cobblestone is filled everywhere in range (which is to large)
### Steps to reproduce the problem

mine-recognition, cobblestone replacement-radius decreased, maybe adding special blocks to block miners from working in certain directions/through defined ways.

**Comment by Kostronor** [comment]
Placing two miners is currently not expected to work well. Keeping this for later reference

**Comment by tomorrow4268** [comment]
maybe implementing the possibility to add more workers/per mine-level(maybe ever 2 levels) to  the same mine so you don't need to build multiple mines and they will work all in the same mine.

**Comment by Raycoms** [comment]
We were already planning similar things.

If you want your miners not to disturb each other let them work on different levels for now. Or place them far away from each other.
