### ISSUE TITLE
Woodcutter started gathering eggs and later froze

### ISSUE THREAD

**Issue by MoonCutter2B** [Minecolonies/minecolonies#244]
### Minecolonies version

1.10.2-0.4.1500, SSP
### Expected behavior

continue cutting down trees etc
### Actual behaviour

suddenly started running around gathering eggs, dirt, seed actually anything loose. He went far away from nearest tree. Then some time later he just stopped and refused to move at all. Recall didn't help. Restarting MC helped though. 
### Steps to reproduce the problem
- no idea, possible play for a many hours with out reloading MC.

**Comment by Raycoms** [comment]
Can you post us the log?

2016-10-30 9:51 GMT-02:00 MoonCutter2B <notifications@github.com>:

**Comment by Kostronor** [comment]
The Lumberjack (if he has no sapling available) will wait for the leaves to decay to get a sapling. He will run around trying to collect them. After some time he will stop trying and go to the next tree.

Once he has spare saplings he won't need to do that anymore.

**Comment by MoonCutter2B** [comment]
He had sapplings both in his inventory and in the chest in the sawmill. I even tried to give him some extra.
I'v put the three lastest logs here:
https://dl.dropboxusercontent.com/u/58751759/MiCo-logs.rar
Could be valid for the farmer problem also.

**Comment by Kostronor** [comment]
Are you sure he has the correct sapling type of the last tree he felled?

**Comment by MoonCutter2B** [comment]
nope, I was not close to him when he stopped cutting trees and started running around looking for stuff. He had 9 eggs in his inventory. I killed all chickens in the area just as a test to see if that helped.
And there was no sapplings in area where he was running around. 
I had a feeling he was lost and that he didn't detect any trees.

**Comment by Kostronor** [comment]
Did he have all types of saplings in his inventory where there are trees of that type from?

**Comment by Kostronor** [comment]
One related issue is #247 but your issue seems to be something extra

**Comment by MoonCutter2B** [comment]
He might have been out of Dark Oak Sapplings, All other are there at least right now. Oak, Spruce, Jungle and Birch. But I cannot be sure how it was.
And yes #247 could be relevant in the case but I'm not sure that was the only problem. I could test and see what happen if I steal all his sapplings.

**Comment by MoonCutter2B** [comment]
if he is out of sapplings he should give a shout?

**Comment by MoonCutter2B** [comment]
hm, he replanted a 2x2 dark oak tree with normal oak sapplings :(

**Comment by Raycoms** [comment]
No when he is out of saplings he will get him himself isn't that better?

And that shouldn't happen, that's a bug for real.

2016-10-30 11:26 GMT-02:00 MoonCutter2B <notifications@github.com>:

**Comment by MoonCutter2B** [comment]
Normally he should never run out of sapplings, most trees drop at least one. 
But if they are standing very close or have a specifik shape e.g. spruce and jungle there is a small risk that they don't drop any.
So then he should first go back to the sawmill and check his chest.
But if there are none there, what then; hope that I will cut down a tree leaving the correct sapplings on the ground or that there are more than one woodcutter in the colony? 
I wouldn't mind a message informing me that he is missing a specific type of sappling.

**Comment by Raycoms** [comment]
But is it a real problem when once in a while he doesn't replant a tree?

2016-10-31 14:50 GMT-02:00 MoonCutter2B <notifications@github.com>:

**Comment by MoonCutter2B** [comment]
Ofc not. The problem is that he doesn't cut any more trees until I restart MC.
Its ok if he gives up looking for saplings after a minute or so or even an MC day and then goes on cutting down another tree.

**Comment by Raycoms** [comment]
He usually gives up after around a minute. (He should)

2016-10-31 18:23 GMT-02:00 MoonCutter2B <notifications@github.com>:

**Comment by MoonCutter2B** [comment]
After the latest updates my woodcutter has behaved better, but it still happens that she sometimes  skips part of a tree, I think it happens when I sleep during night and/or if I teleport away from the colony and then later teleport back. Or it could be happening when I exit the game. Not sure.

**Comment by Kostronor** [comment]
We don't save the Tree on game exit, so that could be the case. We are looking for a solution but for now, building a line of logs up works perfectly fine ;)

**Comment by Raycoms** [comment]
I just gave it a test and the lumberjack really waits a long while before he places it.
I changed the number a bit down. He shouldn't wait that long anymore now.
