### ISSUE TITLE
Farmer stays in indoor

### ISSUE THREAD

**Issue by MoonCutter2B** [Minecolonies/minecolonies#245]
### Minecolonies version

1.10.2-0.4.1500 SSP
### Expected behavior
- go tend fields and harvest the mature wheat
### Actual behaviour
- after harvesting one single wheat she stopped doing anything and stayed indoors. Not sure if the direction of the door v.s. the fields is significant. Recall didn't help. Not sure if restart MC helps (yet)
### Steps to reproduce the problem
- no idea, maybe play for hours without reloading/restarting.

**Comment by Kostronor** [comment]
@MoonCutter2B please don't write on the header lines, that looks ugly 😆 

We are currently working on the farmer and will soon push out some updates to fix him. @Oggal and @Dadadah are working on this :)

**Comment by Oggal** [comment]
Was the farmer or field existing before the latest update?
Does he/she have both a hoe and seeds?

**Comment by MoonCutter2B** [comment]
New farm, added today.
Had hoe, but was lacking some seeds. I found some extra seeds and that helped. Looks like she was tuck waiting for more seeds. But that shouldn't be a problem for the farmer, at least hasn't been before.

**Comment by Raycoms** [comment]
Normally should continue trying to harvest even if she has no more seeds.

2016-10-30 10:56 GMT-02:00 MoonCutter2B <notifications@github.com>:

**Comment by MoonCutter2B** [comment]
Looks like it happens when she is in the house during night. This "morning" she was frozen again. I gave her 6 potatoes and off she went. Now she i happily farming even though one of the fields isn't fully planted.

**Comment by Oggal** [comment]
this is an issue with the farmer's new code and I am working on a fix as we speak

**Comment by MoonCutter2B** [comment]
cool

**Comment by marvin-bitterlich** [comment]
closing as inactive
