### ISSUE TITLE
Builder error upgrading citizen hut 4 to 5

### ISSUE THREAD

**Issue by xannor** [Minecolonies/minecolonies#248]
### Minecolonies version

1.10.2: 0.4.8
### Expected behavior

Builder upgrades citizen hut 4 to hut 5
### Actual behaviour

Intense error logging and lag, no builder action until work order cancelled.
### Steps to reproduce the problem

Upgrade citizen hut 4.

Server Logs:
https://gist.github.com/xannor/494f80d215bbddc70c28db119781bc67

**Comment by Raycoms** [comment]
Do you have another log for us?
That log doesn't contain any errors regarding minecolonies.

2016-10-30 11:46 GMT-02:00 xannor <notifications@github.com>:

**Comment by xannor** [comment]
Make sure you view the full file, github is truncating the main link, look for:

[13:01:28] [Server thread/WARN] [minecolonies/]: Action for target com.minecolonies.entity.ai.util.AITarget@370d8361 threw an exception:
java.lang.NullPointerException

**Comment by Raycoms** [comment]
Ah. Now.

We're working on this error currently.
One of our devs added additional buildings up to level 5 and when you now
try to upgrade the classic ones this may cause this error.
We will soon fix this.

2016-10-30 11:54 GMT-02:00 xannor <notifications@github.com>:

**Comment by xannor** [comment]
I am now getting the following error when trying to repair my townhall:

https://gist.github.com/xannor/23d78f1660c6c81af762c69fd9a3a2ea

I am assuming this is related, but I wonder if my townhall is having issues. I cannot upgrade from lvl 1 to 2 nor repair it. Repair will cause the error above to repeat until I cancel the workorder, and I have no upgrade option, just a build town hall entry, which also causes the above error. My colony is stuck at 8 and it looks like to get more I need to upgrade the town hall as adding citizen huts is not increasing the limit.

**Comment by Raycoms** [comment]
We will update the schematics in the next 2 days. Until that please use the
version before. Sorry for the disturbance.

2016-10-30 20:57 GMT-02:00 xannor <notifications@github.com>:

**Comment by xannor** [comment]
My town stills seems to be functioning and I am not in a hurry, so Ill leave things as is and wait for the update. I just want to make sure you guys get any issues so they can be fixed, if new.

**Comment by Kostronor** [comment]
@xannor Adding citizens huts (that are finished building) will increase the limit.

**Comment by Kostronor** [comment]
Schematics are updated

**Comment by xannor** [comment]
I thinks things may have gone from bad to worse in my world. I updated to 1550, and any repair or upgrade on any building causes a bunch of errors, though they do not flood like before, but it seems no workorder is ever created and the build does not do any work.

I waited till night, and told the builder to do a repair on the builders hut. I saw the work order so I marked the logs, slept till day. The workorder disappeared and this is what was in my logs.

https://gist.github.com/xannor/095f2f016a29b7995be9fbbc950a34b4

**Comment by Raycoms** [comment]
Yeah I noticed that as well.
@Kostronor can you solve this please so we can fix that until thursday?

2016-11-01 22:18 GMT-02:00 xannor <notifications@github.com>:

**Comment by xannor** [comment]
Latest updated seems to work sofar, upgrading buildings from classic to default seems to work.

**Comment by Kostronor** [comment]
Awesome! Tell us if the problem comes back again!
