### ISSUE TITLE
Builder and Building tool does not send block updates to client

### ISSUE THREAD

**Issue by zlainsama** [Minecolonies/minecolonies#252]
### Minecolonies version

version 0.4.1540

### Expected behavior

- issue a building with building tool, the box for that building is placed, and client can see it.
- let a builder build, he starts clearing terrain, terrain is removed and client can see those changes.

### Actual behaviour

- issue a building with building tool, the box for that building is placed on server side, but client can't see it.
- let a builder build, he starts clearing terrain, terrain is removed on server side, but client can't see those changes.

### Steps to reproduce the problem

1. Join a server, use the building tool to issue a building.
2. Join a server, let a builder build.

### Other notable things

1. I was playing on the official server. I did not test in a single player world.
2. The building tool caused my game to crash several times, the crash report says the game has run out of memory.

**Comment by Raycoms** [comment]
Hello, this is a problem when the server uses a lot of resources (close to
100%).
The client does only update when you log off and back in. That's a
minecraft and not a minecolony problem.
The buildTool crash happens when you don't assign enough main memory to
minecraft. We will improve it in the next months though.

Closed.

2016-11-01 6:19 GMT-02:00 Lain MultipleInstances <notifications@github.com>:

**Comment by zlainsama** [comment]
I'm a modder myself, I have encountered this problem before, with my own mod.
I believe this is a problem with the flags set to the setBlock(), which does not tell the game to send block updates to client.
Could you consider checking mod codes again? or tell me where to help you check, I'm not going to find it by myself.

**Comment by Kostronor** [comment]
We normally set the flags to 3 that should post updates to the client. And build tool f.e. works perfectly fine, as long as you are near it. Once you are somewhat far, it stops. 
It could be that sponge is interfering with it...

**Comment by zlainsama** [comment]
I have tested this in a single player world, they worked perfectly fine. Sorry.
Might be sponge then...

**Comment by Kostronor** [comment]
Well, we have to tweak the sponge config then >.>

@zlainsama Would you be interested in helping the mod out? :)

**Comment by zlainsama** [comment]
I would like to, but I do not have any experience in contributing a large project.
I have only worked on some small projects.

**Comment by Kostronor** [comment]
@zlainsama that will be no problem. Most tasks don't need the whole codebase to work with.

If you are interested: http://minecolonies.com/recruitment

**Comment by zlainsama** [comment]
After some consideration, I decided not to apply.
But I think I can help when the mod decides to support other languages.

**Comment by Kostronor** [comment]
@zlainsama Well, we already support multiple languages. We are translated into I think about 10 or so and are always looking for more translators.

**Comment by zlainsama** [comment]
Where can I help translations?

**Comment by Kostronor** [comment]
http://minecolonies.com/publicforum/m/18051739/viewthread/27149805-translations-wanted

**Comment by zlainsama** [comment]
There are multiple entries for a single key in the en_US file, and some of them have different lines written. I will try to translate those different lines and submit the file, have you and others to decide which one to stay.

**Comment by Kostronor** [comment]
@zlainsama Please tell us what language you are translating to. We have a website where the translation will happen. But we would need to invite you with email and preferred language.

**Comment by Raycoms** [comment]
Could you give us your email and the languages you speak fluently?
We actually have a program where we enter these strings which protects us
from multiple entries.

I could invite you there to update the values

2016-11-01 9:19 GMT-02:00 Lain MultipleInstances <notifications@github.com>:

**Comment by zlainsama** [comment]
zlainsama@163.com
Thats my email, I am a native Chinese speaker.

**Comment by zlainsama** [comment]
I mean zh_CN

**Comment by Raycoms** [comment]
There is Chinese simplified, sp, traditional and hong kong I invited you to
the program.

Tell me if I have to adjust anything.

2016-11-01 9:23 GMT-02:00 Lain MultipleInstances <notifications@github.com>:

**Comment by zlainsama** [comment]
You should assign me to Chinese simplified. traditional and simplified are not same, but most time they are same.

**Comment by Raycoms** [comment]
Done =D

2016-11-01 9:35 GMT-02:00 Lain MultipleInstances <notifications@github.com>:

**Comment by zlainsama** [comment]
It's done.
Do I need to press anything?

**Comment by Raycoms** [comment]
No, it persists automatically. Thank you for your contribution. When we add
new terms you should be notified automatically.
If you're interested anyway in joining our coding team to gain some
experience just fill in the application on the forums.

2016-11-01 11:10 GMT-02:00 Lain MultipleInstances <notifications@github.com>
:

**Comment by zlainsama** [comment]
Okay.
