### ISSUE TITLE
Miner stops mining...

### ISSUE THREAD

**Issue by therealericbj** [Minecolonies/minecolonies#254]
### Minecolonies version

version X.X.XXXX or curse X.X.XX   ...1.10.2-0.4.1550

### Expected behavior

Miner to dig mineshaft and then dig mine.

### Actual behaviour

Miner used axe to remove planks that support fence on top level of mineshaft, then went and stood by chest, while requesting that hut be upgraded to dig deeper.  Upgraded hut one level at a time, all the way to top level.  Miner continued to request hut upgrade no matter what level hut was already at.

### Steps to reproduce the problem

1. place miner's chest
2. have builder build miner's hut
3. hire miner
4. give tools

[latest-2016-11-01a.zip](https://github.com/Minecolonies/minecolonies/files/565321/latest-2016-11-01a.zip)

**Comment by Raycoms** [comment]
Yeah, the miner schematic is not fully functional yet.
We will have to rescan it.
As a workaround:
After building it.
Dig one level down at the ladder and place one more ladder.
That should solve it.

2016-11-01 21:47 GMT-02:00 therealericbj <notifications@github.com>:

**Comment by therealericbj** [comment]
![2016-11-01_20 05 32](https://cloud.githubusercontent.com/assets/8407817/19914426/2f19a85c-a070-11e6-9469-f30fb0a95e15.png)
Attempted suggested workaround.

Then things got weird...

It created what you see in the picture and according to the second screen in the miner's hut chest interface, it was already working on level 9 and going down.

**Comment by Kostronor** [comment]
We are working on it :-)

**Comment by Raycoms** [comment]
Should be fixed with the newest structures.
