### ISSUE TITLE
Tinker's Construct

### ISSUE THREAD

**Issue by oddrobbia** [Minecolonies/minecolonies#258]
the tinker's Construct Smeltery controler is not working i build a Smeltery station and i craft all block for the station and the Smeltery controler not have invertory and i cant use them please cheak the mod i seen this bug from the 1.10.2 test server 

By:OddRobbia

**Comment by Kostronor** [comment]
Please report this to Tinkers Construct and not us.

**Comment by Raycoms** [comment]
I think you did something wrong with the smeltery, my smeltery works great.
But please beware, this github is for problems with the mod and not
problems with other mods on our server.

2016-11-02 17:53 GMT-02:00 oddrobbia <notifications@github.com>:
