### ISSUE TITLE
Splash Potions of Healing a Regeneration do not effect Citizens

### ISSUE THREAD

**Issue by Oggal** [Minecolonies/minecolonies#260]
### Minecolonies version

curse 4.1594

### Expected behavior

Splash Potions of healing should heal citizens

### Actual behaviour

Splash Potions of healing and Regenration have no effect on Citizens

### Steps to reproduce the problem

Harm a Citizen and check the GUI, then hammer down some splash potions. Their health goes unchanged.

**Comment by Raycoms** [comment]
I tried healing before and I think they worked, regeneration do not work,
regeneration of citizen is fixed.

2016-11-03 11:30 GMT-02:00 Oggal <notifications@github.com>:

**Comment by Raycoms** [comment]
I just checked it, instant health affects citizens, regeneration doesn't.
(Just wait a moment to see the health difference in the GUI, doesn't update as quickly)
