### ISSUE TITLE
Upgraded fishermans hut to lvl 2 and it looks very strange

### ISSUE THREAD

**Issue by MoonCutter2B** [Minecolonies/minecolonies#263]
### Minecolonies version

version 0.4.1611

### Expected behavior

Lvl 2 hut placed facing in same direction and on the same spot as the lvl 1 hut

### Actual behaviour

Looks like the lvl 2 hut is placed 2 or 3 blocks to the north and/or rotated 90 degrees.
Some stuff was placed outside the plot, the gate that I think replaces the door was placed on the north side instead of the west side and parts of the south wall was still there.

I also asked the builder to repair the hut but is just standing there looking confused, maybe there is nothing to repair?

### Steps to reproduce the problem

1. build fishermans hut facing west (built with some 0.4.14xx version)
2. upgrade to lvl 2
3. see screenshot at https://dl.dropboxusercontent.com/u/58751759/2016-11-05_10.26.21.png

**Comment by Kostronor** [comment]
We updated all schematics, can you try it with a new lvl1 hut and upgrade that to lvl 2?
If the problem still exists, we have to rescan again :D

**Comment by MoonCutter2B** [comment]
well, yes I can see that...
Had some very negative inpact on my town planning. 
Looks like I have to rebuild it all
