### ISSUE TITLE
No More xp/level

### ISSUE THREAD

**Issue by MoonCutter2B** [Minecolonies/minecolonies#264]
### Minecolonies version

minecolonies-universal-1.10.2-0.4.1611

### Expected behavior

Workers earn XP and level up.

### Actual behaviour

Looks like they have stopped earning any XP after last update (or two).
Both my miner and my woodcutter has not made any progress regarding XP for a long time now.
same with builder, fisherman, farmer

### Steps to reproduce the problem

1. Let your workers work...

**Comment by Raycoms** [comment]
We already made a fix ready for this and are testing it atm to push it out
in the next days

2016-11-05 13:56 GMT-02:00 MoonCutter2B <notifications@github.com>:

**Comment by Kostronor** [comment]
Read the discord there I post our current development progress. We changed exp generation and are testing it out. 

Since we now have a test server it won't be instantly uploaded to the main server but tested first.

**Comment by MoonCutter2B** [comment]
ok

**Comment by MoonCutter2B** [comment]
i close this
