### ISSUE TITLE
Lumberjack to recognize Tinkers Contruct Slime Trees. [$10]

### ISSUE THREAD

**Issue by Wissi** [Minecolonies/minecolonies#265]
Can we have the Lumberjack recognize the Tinkers Slime Trees?

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=39025120)](https://www.bountysource.com/issues/39025120-lumberjack-to-recognize-tinkers-contruct-slime-trees?utm_source=39025120&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Kostronor** [comment]
These trees do not extend `Log` and therefore need special handling.

**Comment by Wissi** [comment]
Can we add a bounty on this one, pls...

**Comment by Wissi** [comment]
Can it also chop down/harvest the leaves and not just the "trunk"?

**Comment by nojo121** [comment]
@Wissi  The Leaves decay by themselves.
The Lumberjack collects the items.

**Comment by Wissi** [comment]
@nojo121 they do and drop slime balls and saplings (only way to get purple slime balls) but LJ doesn't always come back to pickup the drops and if he actually harvests the leaves he will 100% of the time harvest the slime balls and saplings.

**Comment by Wissi** [comment]
Can the "leaves" be added to the chopping down? It will also make the axe wear down faster and take longer to harvest 1 of those trees, which would be a good trade-off/drawback for having him harvest slime trees.

**Comment by Raycoms** [comment]
Would require to completely change the code for all trees?

2017-02-25 17:13 GMT-03:00 Wissi <notifications@github.com>:

**Comment by nojo121** [comment]
@Raycoms @Wissi That would be so much work O.O

**Comment by Raycoms** [comment]
Yeah we would have to require that for all trees then.

2017-02-25 17:15 GMT-03:00 nojo121 <notifications@github.com>:

**Comment by Wissi** [comment]
For all trees? Can the block type for slime leaves be added to the type of block that will be chopped down when recognizing/chopping down the slime trees? Slime trees don't have a "log" type it's "block slime". When they are "recognized" as trees I imagine it looks for "leaves" on it, would it be too much to have it chop the leaves when it recognizes it?

**Comment by Raycoms** [comment]
we would have to add all the leafes to it's "cut down this" list. But we're
checking only for logs in this list.
Slime leaves are not really different from normal leaves which makes it
difficult to say when he should and when he shouldn't.

2017-02-25 17:32 GMT-03:00 Wissi <notifications@github.com>:

**Comment by Wissi** [comment]
When "block slime" is present cut?  When log is present don't cut?  LOL
It would be a nice trade-off and more efficient for that specific case.

**Comment by Raycoms** [comment]
The problem is that we store the logs in a list "should be cut" which
contains the position. And before he cuts he again checks if it is a log
and not something he can't cut or air.
At that moment we don't have information anymore which kind of tree he is
cutting.

**Comment by Wissi** [comment]
Hhhmm.. I guess having the LJ cut down the leaves of all the trees he's harvesting can be a good trade-off?
After a short while it's chests full of logs regardless. It will look like a much more cleaner job and less ticks on the server (?) than having the leaves left behind and tick tick tick away until they finally fully decay? Will also ensure that LJ collects all the apples, saplings, slime balls, etc that he might and might not pickup if he walks back through there again or not.

**Comment by marvin-bitterlich** [comment]
We now have tinkers integration so having a check for tinkers slime leaves is no problem

**Comment by nojo121** [comment]
@Wissi Lumberjack breaking the leaves would be too OP cause it's fast.
How about he waits after breaking one leaf block?
1sec
2sec
3sec
4sec
or 5sec?

**Comment by Wissi** [comment]
Well... let me do the math. The slime trees have an average 76 leaves (they all have the same design just vary in height of trunk). (I counted them.)

Breaking each leaf with an Iron axe takes a player approx. 1:15 - 1:30 mins per Tree so 1- 1.5 sec. per leaf for leaves alone. (Timed it in SSP w/entire tree)
Waiting 1 sec. more per leaf would take the LJ 2:30 - 3:00 mins (plus time to chop the trunk down) to take down 1 slime tree. 

We can also reduce the time the LJ starts his day from the Citizen hut back to work, the time to chop the trunks (from 3 to 6 Blocks each tree and takes longer to chop down than leaves) and time from tree to tree. All these small factors can reduce the amount of trees he can harvest in one day.
Since the Minecraft day lasts 10 mins. that would be a Max of 3-4 Slime trees per Minecraft day (normally w/o delay) or 1-3 max with a 1 sec delay. 

The LJ alone in one Minecraft day brings back at least 2-4 "Stacks" of 64 logs normally. If at all it would reduce the amount of harvest the LJ will be bringing back if/when he harvests Slime trees as well. Only bringing back approx 10 - 25 slime blocks per Minecraft day if dedicated to only slime trees.

It seems to me that even w/o delay it's still a slowing down the LJ harvest in general. It's a good tradeoff for taking down slime trees as is w/o a delay in leaves.

Much appreciated the time for you guys to discuss this here as well.
Thanks for all your hard work and dedication.

**Comment by Wissi** [comment]
Closed? Kk.. so it has been coded?
What is the status of how it will work?  (Ppl need to know in game and for WIKI)
Leaves will be cut down? 
Will there be a delay per leaf? (even though it takes: 1:21 - 1:42 mins per tree w/o delay?)

Thanks.

**Comment by Raycoms** [comment]
Yes, Next update, yes, yes

2017-03-06 17:55 GMT-03:00 Wissi <notifications@github.com>:

**Comment by Wissi** [comment]
There is an additional wait time between leaves? How much?

**Comment by nojo121** [comment]
No there's no additional wait time. He just harvests the Blocks like normal.

Wissi <notifications@github.com> schrieb am Mo., 6. März 2017, 22:03:
