### ISSUE TITLE
Bug using bed with town hall in hand

### ISSUE THREAD

**Issue by BerenOneHand** [Minecolonies/minecolonies#266]
### Minecolonies version

version 0.4.1699

### Expected behavior

- No colony creation when using the bed with a town hall in hand

### Actual behaviour

- Creates colony when using bed with town hall in hand

### Steps to reproduce the problem

1. Get town hall from supply chest
2. Right click a bed to sleep in while having it in hand
3. Colony gets created without town hall with bed as center

**Comment by Kostronor** [comment]
Sounds like a new case of #159

**Comment by Raycoms** [comment]
It's a duplicate of #159 actually.
