### ISSUE TITLE
Town hall construction

### ISSUE THREAD

**Issue by BerenOneHand** [Minecolonies/minecolonies#267]
### Minecolonies version

version 0.4.1699

### Expected behavior

- Builder continues construction of town hall after server restart

### Actual behaviour

- Builder restarted construction of town hall after server restarted

### Steps to reproduce the problem

1. Instruct builder to build town hall
2. Partial construction of town hall
3. Restart server
4. Town hall build area recleared, even facing a different direction, construction started from scratch

**Comment by Kostronor** [comment]
It could be there was our build tool change in between that? We changed the whole system.

**Comment by BerenOneHand** [comment]
No, started a new map this morning to check things out. Had to stop the server when i restarted the computer for other reasons.

**Comment by BerenOneHand** [comment]
not sure if it is relevant but the builder was waiting for spruce door before the server restart and the town hall was being built. The builder's hut building was not built yet.

**Comment by Kostronor** [comment]
Well, it should not be possible to build the townhall without the builders hut first, so that's a bug for sure. Can you try to reproduce it once you have the builders hut at least lvl 1?

**Comment by BerenOneHand** [comment]
This is exactly how i did it:

I built the supply chest and took the builder tool as well as the town hall.
I placed the town hall, pressed build town hall which put it to the top of the work queue. 
built the builder's hut and placed it. Pressed the build button on the builders hut which put it to the bottom of the queue.
the builder then started on the town hall rather than the builder's hut.

**Comment by Raycoms** [comment]
Yeah because the builder already had started on the townhall. The builder
doesn't switch building anymore after starting to build one.

2016-11-10 8:07 GMT-02:00 BerenOneHand <notifications@github.com>:

**Comment by Raycoms** [comment]
If it happens again please report it to us.
