### ISSUE TITLE
Guard tower schematic turned 180 degrees...

### ISSUE THREAD

**Issue by therealericbj** [Minecolonies/minecolonies#268]
### Minecolonies version

minecolonies-universal-1.10.2-0.4.16

### Expected behaviour

- guard tower expected to be facing south

### Actual behaviour

- guard tower is facing north

### Steps to reproduce the problem

1. in an existing colony, remove a guard tower and then replace it, or just repair the existing tower.
2. you'll find the tower has turned 180 degrees.

**Comment by Raycoms** [comment]
The problem we have is that manual placement and build tool placement works
different. So if you replace your building, take care you use the build
tool if you have placed it using the build tool already.

2016-11-09 20:25 GMT-02:00 therealericbj <notifications@github.com>:

**Comment by therealericbj** [comment]
Sorry, I should have explained better.

What I meant by "replace" was that I just used "worldedit" to replace the tower with "air", then I used the build tool to place another tower.  I didn't build my own tower or anything like that.  All the Minecolonies buildings were placed with the build tool.

**Comment by Raycoms** [comment]
Yeah and after removing it with worldedit, you used the buildTool to place
the tower the exact position you wanted, you confirmed, and after building
it it was wrong?

2016-11-09 21:01 GMT-02:00 therealericbj <notifications@github.com>:

**Comment by therealericbj** [comment]
I first discovered that the building was wrong, when after accidentally breaking several blocks on the tower, I hit the Repair Building button, the builder went and did her thing, I looked at the building again and saw that the tower was built over again, turned 180 degrees and half overlapping the original tower.

Please see enclosed screenshots the same process on another tower...

![2016-11-09_18 36 11](https://cloud.githubusercontent.com/assets/8407817/20160457/a22d6148-a6ac-11e6-80c2-b1f9c7464e0a.png)
...existing tower, with a few broken blocks...

![2016-11-09_18 37 15](https://cloud.githubusercontent.com/assets/8407817/20160467/b4d47d22-a6ac-11e6-9317-82b7937bf192.png)
...tower after "repair" button has been pressed...

![2016-11-09_18 38 02](https://cloud.githubusercontent.com/assets/8407817/20160476/c6d8c870-a6ac-11e6-9912-c292c96930fb.png)
...added a waypoint to mark where the building's chest was...

![2016-11-09_18 39 39](https://cloud.githubusercontent.com/assets/8407817/20160482/d8966360-a6ac-11e6-9249-9b6cdd533ed1.png)
...selected and removed building with Worldedit, by replacing it with "air"...

![2016-11-09_18 43 11](https://cloud.githubusercontent.com/assets/8407817/20160493/e8354aa2-a6ac-11e6-86ed-9e1f238c910b.png)
...attempted to place a new building in the same position as original building (I should have taken a screenshot showing the preview, oops)...

I hope the pictures will help.  Sorry that my attempts at explaining it are so bad.

I can try the whole process again and show the "preview" before building the new building if you wish it.
Let me know...

**Comment by Raycoms** [comment]
I pushed a commit yesterday, which we will update to the pack today even I
think. Which may fix all that problems.
After using the new version, please tell us if the problems is still there.

2016-11-09 23:03 GMT-02:00 therealericbj <notifications@github.com>:

**Comment by therealericbj** [comment]
minecolonies-universal-1.10.2-0.4.1704

Attempted to rebuild the tower again and the same problem still existed.

The position was the same, the preview was even correct.  The point where the tower was rotated 180 degrees, was when the builder started the building.

Just in case it makes a difference, this colony and builder were created with
minecolonies-universal-1.10.2-04.1500.

...Happy Hunting Guys.

**Comment by Raycoms** [comment]
Shouldn't make a difference.

I will test it later again. I wasn't able to reproduce it yet.



2016-11-10 13:02 GMT-02:00 therealericbj <notifications@github.com>:

**Comment by Megistus** [comment]
I can confirm the same issue with me, with minecolonies-universal-1.10.2-0.4.1704, however the issue is not just with the tower, but at least in my case with the citizen hut. Placed block with builder tool, but the house was built 180 degrees from what was intended. Same occurs when attempting to upgrade the building.

**Comment by MoonCutter2B** [comment]
my tower also - turned 180 degrees when I ask builder to repair it.

**Comment by Raycoms** [comment]
Does this happen especially when you do not rotate the block with the build tool?

**Comment by MoonCutter2B** [comment]
I think I just placed the tower. I remember being confused of the fact that only the top was visible with the tool so I hit "+" a number of times and then just accepted it. I could try to place another one and see what happens.

**Comment by Raycoms** [comment]
I uploaded the changes on curse and will also update the curse modpack in
just a moment. Please tell me if you're able to reproduce it in the newest
version.

Minecolonies Testpack v0.4.74

Minecolonies v0.5 Release candidate v7

2016-11-11 14:13 GMT-02:00 MoonCutter2B <notifications@github.com>:

**Comment by MoonCutter2B** [comment]
with the last update rc7 my builder aborted the incorrect repair and finished the existing one instead = yes looks like the problem is solved :)

**Comment by therealericbj** [comment]
With update rc7, existing buildings still had problem.  Removed and replaced existing buildings, had no more problems.

Did discover a new problem when trying to place building with building tool.  Will report separately.
Removed mod in question, problem was gone.

**Comment by Raycoms** [comment]
would still be interesting to know which mod clashed with ours.
