### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by Leavaris** [Minecolonies/minecolonies#269]
### Minecolonies version

curse universal-1.10.2-0.4.1699

### Expected behavior

- permissions seemed to work in prior versions

### Actual behaviour

- permission system, owner can access inventories, others added, even if officer, cannot interact. the window pops up but nothign happens on button presses/cant open inventories.

### Steps to reproduce the problem

in case its an issue with other mods the pack used is "the Colonies" on curse launcher

**Comment by Raycoms** [comment]
@Kostronor.

I also noticed that. We're working on that.

2016-11-09 23:10 GMT-02:00 Leavaris <notifications@github.com>:

**Comment by Raycoms** [comment]
Should be fixed with the most recent version.
