### ISSUE TITLE
TileEntityColonyBuilding at :[x,y,z] had no colony.  It could be a previewed building.

### ISSUE THREAD

**Issue by tomorrow4268** [Minecolonies/minecolonies#270]
### Minecolonies version

version 1.10.2-0.4.1403

### Expected behavior

- active buildings + citizen respawned

### Actual behaviour

- buildingblocks deactivated, no spawning of citizens

### Steps to reproduce the problem

1. moving further than 10k block away from city several times.
2. Teleporting/spawning back

**Comment by tomorrow4268** [comment]
i got
TileEntityColonyBuilding at :[360,64,281] had no colony.  It could be a previewed building. for each entity and building i had when i came back by teleport to my city-centre, so in other words, i lost everything. Haven't tried to place a new ship yet

**Comment by Kostronor** [comment]
Can you try placing a new colony? (cheat your townhall and try placing it).
It seems like your world got corrupted and minecraft lost minecolonies data.

**Comment by Raycoms** [comment]
I bet it's one of these minecraft problems. Never noticed that villages die out after a while?
I guess that all our colony data has been lost by minecraft itself.

**Comment by tomorrow4268** [comment]
i'm sorry, i didnt check it, i updloaded the newest experimental-version and used the command to delete my old colony to get rid off all  and started a new one with all new buildings.
Seems like the colony-data was all lost after the bug appeared

**Comment by Raycoms** [comment]
Yeah I guess the problem is at minecraft because it seems that they have
some data leaks.

2016-11-11 12:30 GMT-02:00 tomorrow4268 <notifications@github.com>:
