### ISSUE TITLE
Guard Tower block location

### ISSUE THREAD

**Issue by tomorrow4268** [Minecolonies/minecolonies#271]
### Minecolonies version

all/newest 1.10.2

### Expected behavior

- Guardtowerblock is at the top floor

### Actual behaviour

- would be more practical if it was on the gound floor in order to place the tower

### Steps to reproduce the problem

placing it or visualizing it

**Comment by Kostronor** [comment]
For placing yeah, but then guards would never climb their tower

**Comment by Raycoms** [comment]
We're actually planning some more advanced patrolling and guarding options in further updates and may then change the block location on the ground floor.
For the time being it's gonna stay as it is so that the guards really go up and down.
