### ISSUE TITLE
planning: not able to go from decoration back to standard buildings

### ISSUE THREAD

**Issue by tomorrow4268** [Minecolonies/minecolonies#272]
### Minecolonies version

newest version

### Expected behavior

- in planning mode: pushing the button of template-types should switch between decoration and standard buildings.

### Actual behaviour

-  in planning mode: pushing the button of decoration templates will block returning back to town-buildings

### Steps to reproduce the problem

1. can be reset by using the "decline" button  in the planning mode.

**Comment by Kostronor** [comment]
What? 
You can toggle between hutblocks and decorations. 

Can you elaborate your problem? Maybe with Screenshots?

**Comment by Raycoms** [comment]
Will be fixed in the next upload.
