### ISSUE TITLE
Buildings rotating after loading save

### ISSUE THREAD

**Issue by iceluigi13** [Minecolonies/minecolonies#273]
### Minecolonies version

Version 0.4.1704

### Expected behavior

- Buildings should not rotate on loading a save file

### Actual behaviour

- The first time a building block is loaded from a save file it will rotate. Repairing or upgrading a building after a load will cause the builder to reconstruct the entire building at a different angle relative to the main block for that building. Work orders in progress will start over and build at a different angle than when they started. Saving and loading additional times will not cause the blocks to rotate any more.

### Steps to reproduce the problem

1. Place down desired building block
![2016-11-11_09 18 07](https://cloud.githubusercontent.com/assets/23402283/20220717/363a9b4c-a7f4-11e6-886a-91a6365c1d81.png)

2. Start work order (you don't have to let him complete it)
![2016-11-11_09 19 32](https://cloud.githubusercontent.com/assets/23402283/20220720/364c6dae-a7f4-11e6-906b-a48b4409bda6.png)

3. Save, quit, and reload the save. You can see that the Builder's Hut block has rotated
![2016-11-11_09 19 49](https://cloud.githubusercontent.com/assets/23402283/20220719/364c2916-a7f4-11e6-9bb2-964327a64811.png)

4. If the building was completed start a repair order and watch the builder rebuild the building
![2016-11-11_09 20 38](https://cloud.githubusercontent.com/assets/23402283/20220718/364a9862-a7f4-11e6-91f7-1854dc932656.png)

The same thing happens with the Guard Tower
![2016-11-11_09 28 54](https://cloud.githubusercontent.com/assets/23402283/20221064/86739860-a7f5-11e6-9134-4a418bc5c6d7.png)

I've also had the town hall rotate and I know other players who have had similar problems with other buildings after a server restart.

**Comment by Raycoms** [comment]
I changed some of the code today and will upload the fix in the next hour.
Please test it then again with the new version.

(Minecolonies v0.5 Release candidate v7 then)

2016-11-11 14:06 GMT-02:00 iceluigi13 <notifications@github.com>:

**Comment by iceluigi13** [comment]
The same thing happens in 0.4.1710. Built the hut, relogged, the block was facing a different direction.

Thanks for responding so quickly; my friends and I are loving the mod so far!

**Comment by Raycoms** [comment]
Does this only happen while the builder is upgrading or also when you
relog without starting the workorder?

2016-11-11 14:43 GMT-02:00 iceluigi13 <notifications@github.com>:

**Comment by iceluigi13** [comment]
It's both. Starting the work order before or after relogging doesn't make a difference.

**Comment by Raycoms** [comment]
That's strange behavior, I will look into it.

2016-11-11 14:51 GMT-02:00 iceluigi13 <notifications@github.com>:

**Comment by Raycoms** [comment]
Smp, ssp or both?

2016-11-11 16:11 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by Raycoms** [comment]
Nvm, I was able to reproduce it. Very strange.

2016-11-11 16:11 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by Raycoms** [comment]
Found it, fixed it. Will upload it in the next hour.
