### ISSUE TITLE
Attempting to place building with building tool...

### ISSUE THREAD

**Issue by therealericbj** [Minecolonies/minecolonies#274]
### Minecolonies version

minecolonies-universal-1.10.2-0.4.1710

### Expected behavior

Place and position building...

### Actual behaviour

Client crashed in Single Player World.

### Steps to reproduce the problem

Attempt to place building with building tool.

See Screenshot of building preview...

This could be why Malisis Doors was having a problem...
![2016-11-11_13 45 16](https://cloud.githubusercontent.com/assets/8407817/20228927/51e781e6-a819-11e6-9143-09a50ff553f4.png)

[crash-2016-11-11_13.02.21-client.txt](https://github.com/Minecolonies/minecolonies/files/586676/crash-2016-11-11_13.02.21-client.txt)

**Comment by Raycoms** [comment]
Thanks for reporting this error.
It seems like the render method has some compatibility problems
with malisis.doors mod.

The render method we use it a minecraft intern method. I will report the
error to malisis.

2016-11-11 18:12 GMT-02:00 therealericbj <notifications@github.com>:

**Comment by Raycoms** [comment]
Should be fixed with the most recent version.
