### ISSUE TITLE
plan-mode problem placing lumberjack correctly

### ISSUE THREAD

**Issue by tomorrow4268** [Minecolonies/minecolonies#275]
### Minecolonies version

newest official version

### Expected behavior

- rotating the building(lumberjack) in the planning mode should rotate the box

### Actual behaviour

- when turning it , it will still be built in a certain direction
first i wasn't sure if it was always turning by 180, but when i turned it to the wrong direction (as it was doing when i was trying the one i wanted), it stayed like that. so maybe it's a rotation-bug and the main-block can't be rotated even after planning-mode

### Steps to reproduce the problem

1. restarting the game
2. reloading the map
3. when in planning-mode: always puts the main-block in the direction you are looking at, even if you rotate it with the Visualizer

**Comment by Raycoms** [comment]
Didn't really understand.

When you're using the buildToor with the sawmill the structure doesn't
correctly in the preview?

2016-11-11 18:59 GMT-02:00 tomorrow4268 <notifications@github.com>:

**Comment by tomorrow4268** [comment]
![2016-11-12_13 41 48](https://cloud.githubusercontent.com/assets/23143040/20237848/013bf02c-a8de-11e6-8d75-a558d3fe634b.png)

This picture shows the problem: when i built it, it was rotated correctly, but after reloading the map, all Main blocks were tilt in the same direction again, so upgrading will now destroy the old building and also the ones positioned next to it.

**Comment by Raycoms** [comment]
You're sure that's happening with the version I uploaded yesterday? (That
should'Ve fixed it)

2016-11-12 10:45 GMT-02:00 tomorrow4268 <notifications@github.com>:

**Comment by tomorrow4268** [comment]
i have the 1704, so maybe i was late ;D

**Comment by Raycoms** [comment]
Probably fixed it then =D

2016-11-12 14:35 GMT-02:00 tomorrow4268 <notifications@github.com>:
