### ISSUE TITLE
[1704]Citizen Hut did not add  more citizen

### ISSUE THREAD

**Issue by tomorrow4268** [Minecolonies/minecolonies#278]
### Minecolonies version

version X.X.1704

### Expected behavior

- after bulding the citizen Hut, normally the max is lifted by 2 Citizen

### Actual behaviour

- After the hut was built, it was still max:4 citizen

### Steps to reproduce the problem

1. building Hut
2. Completing Hut

**Comment by Raycoms** [comment]
When you build the first citizenHut, your citizens, which currently life in
the townhall, will change their home to the newly build citizenHuts.
Therefore, you'll have to place citizenHuts for the current citizens +
ciitzenHuts for the new ones you'd like.

2016-11-12 9:59 GMT-02:00 tomorrow4268 <notifications@github.com>:

**Comment by tomorrow4268** [comment]
ok thx good 2 know :) so i need to build 2 huts to cover the first 4 citizens

**Comment by Raycoms** [comment]
Exactly, or upgrade the hut because more citizens may move into one hut
each level.

2016-11-12 10:04 GMT-02:00 tomorrow4268 <notifications@github.com>:

**Comment by tomorrow4268** [comment]
ok thx so you already implemented  more citizens the more levels

so is the initial level(1) already housing 2 or only 1 citizen?

**Comment by Kostronor** [comment]
One citizen per level
