### ISSUE TITLE
Add Tinkers Construct Weaponry to Guards [$15]

### ISSUE THREAD

**Issue by kedamono** [Minecolonies/minecolonies#279]
### Minecolonies version

version 0.4.1710

### Expected behavior

- The Guards colonists would use Tinkers Construct Weapons

### Actual behaviour

- They ignore them when placed into their inventory.

### Steps to reproduce the problem

1. Create a Tinkers Flint Sword
2. Recall a Guard and remove his current weapon from his inventory.
3. Add the Tinkers Flint Sword to his inventory
4. Result: He requests a weapon and doesn't specify what kind.

**Comment by Raycoms** [comment]
That's very strange. I guess Tinker construct didn't define their swords as
weapons following minecraft classes.

2016-11-12 14:13 GMT-02:00 kedamono <notifications@github.com>:

**Comment by Wissi** [comment]
Yep, can their weapon classes be added to the Guards "acceptable weapons" list as well?
I was gonna suggest it too. The Longsword, Broadsword, Rapier and Cleaver?

**Comment by jrgryph** [comment]
How about tools too?

**Comment by kedamono** [comment]
I just had one of my Miner characters not recognize the flint pickaxe that she had been using just a moment before. I think it's just a glitch, but...

**Comment by neadlak** [comment]
Maybe the materials are confusing them? Did they request a certain mining level and flint isn't up to that mining level?

I definitely had a team of citizens using bronze TiCon tools (bronze because I had forestry running with the testpack and it adds that alloy) and they accepted the tools as valid.

**Comment by Wissi** [comment]
As Kostronor stated in another issue: "We now have tinkers integration so having a check for tinkers slime leaves is no problem"

Would this also make it possible now for the guards to recognize and use the Tinkers weapons?
Longbow, Crossbow, Longsword, Broadsword, Rapier and Cleaver?

**Comment by nojo121** [comment]
will add it to my pr.
