### ISSUE TITLE
Guard 2° Job selection

### ISSUE THREAD

**Issue by Raycoms** [Minecolonies/minecolonies#281]
You right click his chest, in the chest you select what you want like "Stand still" "Follow me"  and Patrolling: "Manual - automatic"

- When the player clicks follow me (easiest option) the guard stores a player object and follows around the player until he dies or until the player changes it in its gui.

- When the player clicks "Stand still" an item is given into his held item slot and the player is asked to select a spot which should be guarded

- And when the player clicks "Patrolling manual" this item is also rendered and he is asked to select a route with left click and finish the selection with right click"

- The task is stored in the building but on new hire or death the follow me task will be reset.

**Comment by Raycoms** [comment]
Guards should notice the player about their low health.
Guards should notify their location on death.
GUI option which lets guards retrieve on low health -> make him retrieve slowly.

**Comment by pmardle** [comment]
What happens when Player dies outside the colony with a guard following.. do they warp back to the colony (preferred?)

**Comment by Raycoms** [comment]
guard doesn't follow outside of the colony, he currently stops at 40* guard
tower level.

2016-11-30 8:43 GMT-02:00 pmardle <notifications@github.com>:

**Comment by pmardle** [comment]
were going to have to make him follow outside of the colony boundary at some point..

Personally I would make it an indefinite distance, and he never tries to return to his chest if he is outside the colony boundary..

**Comment by Raycoms** [comment]
Yeah that's the plan. But for the time being if he gets stuck out there he
might crash the server because he can't find the way back home.
I will have to create a more sophisticated system which teleports the guard
back home when the player is out of range/offline.

2016-12-05 13:46 GMT-02:00 pmardle <notifications@github.com>:
