### ISSUE TITLE
Citizen Hut won't increase maximum citizens?

### ISSUE THREAD

**Issue by CodySpirits** [Minecolonies/minecolonies#282]
### Minecolonies version

version 0.4.1692 for 1.10.2

### Expected behavior

- After building a Citizen's Hut, I my town hall should be increasing in maximum citizens.

### Actual behaviour

- Maximum citizen size has not increased at all.

### Steps to reproduce the problem

Simply proceed through the mod as usual, but once the citizen's hut is built, the maximum number does not increase.

**Comment by Kostronor** [comment]
You have to first fill the 4 citizens from the townhall

**Comment by lordseppe** [comment]
@reggaemuffin what do you mean? fill the 4 from townhall? you mean like the original 4? my citizen cap is at 25/25 now and also not increasing after building more houses. im looking for a fix.

**Comment by ravenbuilder934** [comment]
Do the research in the University to raise your citizen cap.
