### ISSUE TITLE
Farmer not working

### ISSUE THREAD

**Issue by George963** [Minecolonies/minecolonies#283]
Minecolonies version

curse 0.4.78

Expected behavior

- go tend fields and harvest the mature wheat

Actual behaviour

- Farmer keeps asking for seeds even though he has them in his inventory. In the meantime he keeps running from field to the farm and back. I can't make him stop. Atm playing on the official server, igm: GeorgeMalutan963

Steps to reproduce the problem

1. created farm
2. created BasicField from decorations
3. selected Seeds(wheat)
4. Gave Farmer hoe and 64 seeds, but keeps running between field and farm.
![farmer issue 1](https://cloud.githubusercontent.com/assets/23511030/20368751/0c868c84-ac5e-11e6-9a49-07e1d120d08f.jpg)
![farmer issue 2](https://cloud.githubusercontent.com/assets/23511030/20368752/0c890b6c-ac5e-11e6-90d7-a692f09a199e.jpg)
![farmer issue 3](https://cloud.githubusercontent.com/assets/23511030/20368753/0c9ae9ae-ac5e-11e6-8c16-d41e19a9ec76.jpg)

Don't know if the pictures help but I put them anyway. Maybe I made a mistake in setting the farm, so I do apology if this issue is because of my lack of experience.

**Comment by Raycoms** [comment]
Did you right click the scarecrow to set the field inside it?

2016-11-16 20:40 GMT-02:00 George963 <notifications@github.com>:

**Comment by George963** [comment]
yeah, selecting the seed, did that.

**Comment by George963** [comment]
If I may add, in the 100 range of my townhall there is a vanilla village, with a few fields, but still not that close to the farm.

**Comment by Raycoms** [comment]
The farmer only tries to plant fields where there is a scarecrow in the middle and the seed is set.
If he requests seeds just put them in his chest, he should resolve it automatically in the next run.

**Comment by George963** [comment]
tried that. Also I tried firing the farmer and then hiring again, tried recalling, but still didn't work.

Looking carefully at what the farmer does, when she returns at the chest, she puts the seeds back in chest, takes them again and runs to the field, returns and then repeats the cycle, by putting the seed back in chest, taking them and so on.
![seeds 1](https://cloud.githubusercontent.com/assets/23511030/20369879/3692eb70-ac64-11e6-8c7e-c0caaeffc521.jpg)
![seeds 2](https://cloud.githubusercontent.com/assets/23511030/20369880/3698e94e-ac64-11e6-913e-624f56d0e0b7.jpg)

**Comment by Raycoms** [comment]
That's very strange.

@Kostronor do you have an idea what that might be?

**Comment by George963** [comment]
@Raycoms , if you want to you can come see it, maybe you can figure out more. that is if you can contact me on the server.

**Comment by George963** [comment]
sooo, I made another field, and this time it worked perfectly... Now that i think about it, the first time i placed the scarecrow, i cut it down and replaced it. maybe it was that.

**Comment by b0bst3r** [comment]
I'm getting this too, have removed farm and rebuilt it and it seems to work for 1 growth run of the crops (wheat) then she stops and just runs back and forth from scarecrow to farm building over and over.

**Comment by Raycoms** [comment]
Currently the farmer is intended to only farm the field until it has been
farmed completely. this will be changed eventually.

2016-11-22 16:14 GMT-02:00 b0bst3r <notifications@github.com>:

**Comment by Raycoms** [comment]
We already have an issue for this.
