### ISSUE TITLE
Suggestions: Quite A Few

### ISSUE THREAD

**Issue by darkjediwarriorX** [Minecolonies/minecolonies#285]
[Suggestion #1: Portcullis/Drawbridge]

So what you do is use the Caliper to Select the Width and the Height for the Portcullis, and then choose the Style (Wooden Fences, or Iron Bars).  It would be like this
X = Iron Bar, Y = Stone Bricks, Z = Lever
Y Y Y Y Y
Z X X X Y
Y X X X Y
The Lever would make the Iron Bars go up and then back down.
Hopefull your could make them move smoothly.
As for the drawbridge, it would Rotate 90 Degrees Up and then Down. 

The Benefits Of This Are: It would be great for Walls and Moats.
--------------------------------------------------------------------------------------------------------------------
[Suggestion #2: Carriage]

They would have an inventory, and you could use the Delivery Man with them to ship goods to other colonies (or do it yourself). You back the horse into the carriage and they would latch on to it, and you could travel long distances with more space to carry things.

The Benefits Of This Are: It would be nice for travelling long distances with a lot to carry.
--------------------------------------------------------------------------------------------------------------------
[Suggestion #3: Delivery Men Travel Long Distances]

You'd right click him. Tell him what items to ship, and out of the existing colonies on a list, you choose it. Hey then goes on a route to it. And if he has trouble, like an Ocean in the way. He would warn you and you could go to him and help, or have him come back.

The Benefits Of This Are: It would make the mod more innovative with players.
--------------------------------------------------------------------------------------------------------------------
[Suggestion #4: Guard Actions]

You would right click on a guard, and they would have a tab called "Actions". In this tab you can choose the following, Follow Me, Guard Citizen, or Guard Building.

The Benefits Of This Are: It would make the guards better organized in their tasks. And workers would need some protection while working, especially the miner.
--------------------------------------------------------------------------------------------------------------------
Thank you for reading this. --darkjediwarriorX/Flash_Sentry_EG

**Comment by Kostronor** [comment]
Can you split them up into one issue per Suggestion?

**Comment by Kostronor** [comment]
Closing this in favor of #286 #287 #288 and #289
