### ISSUE TITLE
Suggestion: Portcullis

### ISSUE THREAD

**Issue by darkjediwarriorX** [Minecolonies/minecolonies#286]
So what you do is use the Caliper to Select the Width and the Height for the Portcullis, and then choose the Style (Wooden Fences, or Iron Bars). It would be like this
X = Iron Bar, Y = Stone Bricks, Z = Lever
Y Y Y Y Y
Z X X X Y
Y X X X Y
The Lever would make the Iron Bars go up and then back down.
Hopefull your could make them move smoothly.
As for the drawbridge, it would Rotate 90 Degrees Up and then Down.
The Benefits Of This Are: It would be great for Walls and Moats.

**Comment by Raycoms** [comment]
I'd say this one would be interesting following this:
Should be a block which spawns a certain amount of portcullis.
Citizens should recognize it and be able to path through it.
When citizens get close portcullis should go up.

**Comment by Asherslab** [comment]
I think that sounds absolutely epic!!!

**Comment by Wissi** [comment]
I think the Mechanics and details could be:
Gate block: (porticullis) can have a setting for: 
1.- a slot to place the block that will be used (as well as the amount required).
2.- a selectable "Width" and "Height" for the gate.
3.- a toggleable auto open/close for players. 
4.- a config option to specify the max width/height and list the allowable blocks to use for the gate (allowing other modded blocks to be added as well).

Bridge block: can have similar settings:
1.- a slot to place the block that will be used (as well as the amount required) for the floor.
2.- a slot to place the block that will be used (as well as the amount required) for the side railing.
2.- a selectable "Width" and "Length" for the bridge.
3.- a toggleable auto extend/retract for players.
4.- a config option to specify the max width/length and list the allowable blocks to use for the floor and railing (allowing other modded blocks to be added as well).

**Comment by Raycoms** [comment]
Nahh too much work, too complex. you will see how I am coding it, way
easier to make, configure and use =D

2018-02-26 0:33 GMT+00:00 Wissi <notifications@github.com>:
