### ISSUE TITLE
Suggestion: Carriage

### ISSUE THREAD

**Issue by darkjediwarriorX** [Minecolonies/minecolonies#287]
They would have an inventory, and you could use the Delivery Man with them to ship goods to other colonies (or do it yourself). You back the horse into the carriage and they would latch on to it, and you could travel long distances with more space to carry things.
The Benefits Of This Are: It would be nice for travelling long distances with a lot to carry.

**Comment by Raycoms** [comment]
I think for now I will close this, improbable we will make this in feasible time.
