### ISSUE TITLE
Suggestion: Colony Trading.

### ISSUE THREAD

**Issue by darkjediwarriorX** [Minecolonies/minecolonies#288]
You'd right click the Delivery Man. Tell him what items to ship, and out of the existing colonies on a list, you choose it. Hey then goes on a route to it. And if he has trouble, like an Ocean in the way. He would warn you and you could go to him and help, or have him come back.
The Benefits Of This Are: It would make the mod more innovative with players.

**Comment by Kostronor** [comment]
#81 is covering this imo. Maybe you add this onto that issue?
