### ISSUE TITLE
Suggestion: Guard Actions

### ISSUE THREAD

**Issue by darkjediwarriorX** [Minecolonies/minecolonies#289]
You would right click on a guard, and they would have a tab called "Actions". In this tab you can choose the following, Follow Me, Guard Citizen, or Guard Building.
The Benefits Of This Are: It would make the guards better organized in their tasks. And workers would need some protection while working, especially the miner.

**Comment by Kostronor** [comment]
#281 is covering this. Can you merge these two?

**Comment by Raycoms** [comment]
Yeah that's on my list.
