### ISSUE TITLE
Suggestion: Clothes

### ISSUE THREAD

**Issue by darkjediwarriorX** [Minecolonies/minecolonies#291]
This ties in with the Clother Suggestion.

Clothes are made using Cotton, Wool, Leather, and other various things. Citizens would require certain clothes for certain environments (Warm Coats, for when it snows, Rain Coats, allows them to work while it rains) this could also tie in with the Happiness Idea. and players could make and wear the clothes as well.

**Comment by Kostronor** [comment]
Related #290

**Comment by Raycoms** [comment]
I think for now I will close this, improbable we will make this in feasible time.
