### ISSUE TITLE
Protection Config

### ISSUE THREAD

**Issue by leglerm** [Minecolonies/minecolonies#292]
### Minecolonies version

version 0.4.1744

### Expected behavior

- Able to break/place blocks everywhere around my friend base (basically in the world)

### Actual behaviour

- Doesnt work as my friends colony protects the area

### Steps to reproduce the problem

Basically i would like to interact with the world even though there is a colony present. The colony itself protects a specific area around itself making other players unable to interact. 

I checked the config to disable protection but i couldnt find any.

We tried to add me as a "friend" of the colony which didnt helped. Only the "officer" permission made me able to interact in that area but it instantly gave me all achievments (i dont yet have a colony myself and hope i will still be able to)

Since we are playing on a small server without any need for protection it would be nice to disable colonies protection without the need to add each other as officers to the colonies.

**Comment by Baughn** [comment]
Concur. This would be very useful for my own server.

**Comment by xenoflot** [comment]
I would add to this that no protection system should ever prevent _operators_ from altering terrain.
I discovered today that despite being the server admin, I cannot affect anything within the protected radius. 

If there was a problem within the area, I would need to try deleting player data, or load up MC edit or something. Sorry to be blunt, but this is unacceptable. Please correct this ASAP.

**Comment by marvin-bitterlich** [comment]
@xenoflot we planned on using the forge permission system to add that functionality but for now no one got time to really finish permissions, sorry. We are always welcome to new devs trying to help out improve things. ASAP is sadly only possible if our work is payed and that is currently not the case.

**Comment by Raycoms** [comment]
I will soon add a command which allows operators to add themselves to
colonies to enable them editing the terrain.

Am Samstag, 24. Dezember 2016 schrieb Marvin Hofmann :

**Comment by Baughn** [comment]
Could you please just add an option to disable the entire codepath? We don't need protection, and the way it interferes with e.g. creepers is blocking me from even considering Minecolonies for a modpack.

Edit: Or point me in the approximate direction of the code, and I'll do it.

**Comment by Raycoms** [comment]
We will add an option but that might need a bit.
Our time and amount of coders are limited.

Am Samstag, 24. Dezember 2016 schrieb Svein Ove Aas :

**Comment by xenoflot** [comment]
@Kostronor Firstly, I'd like to say sorry for my tone. I know that modders are volunteers. I genuinely appreciate the work you do and your generosity in sharing it with us at no charge. I should have been more diplomatic. I sincerely apologise.

If I may offer my criticism more constructively, I think this situation is such a serious obstacle to server administrators that it should never have seen public release. That is, the terrain protection system should not have been enabled until the the proper permissions modules were place. With this current limitation, I cannot accept including Minecolonies in my server modpack. I feel that your team should consider this with the same importance as a game-crashing bug and prioritize it over development of other features.

@Raycoms I look forward to the command, thank you. Either solution, being able to add admins to the colony, or Baughn's suggestion of simply disabling the protection code for now, are acceptable. From a personal perspective, I think the latter is preferable.

Cheers

**Comment by Raycoms** [comment]
Okay.
I gave the system a little rework.
There should be a config option + command to become officer now.
Also containers inside the colony as well as the citizens should be
protected.
Tonight I'll upload it as a beta.
It does need some testing.
I don't have Internet at home atm.

Am Samstag, 24. Dezember 2016 schrieb xenoflot :

**Comment by xenoflot** [comment]
Righto. My players are testing our new modpack for stability at the moment so I'll be able to give it some testing. If you have some specific scenarios that you'd like us to test, make a note of them here and I'll report back. Otherwise we'll just continue in our haphazard way and I'll report what breaks :)

**Comment by Raycoms** [comment]
https://mods.curse.com/mc-mods/minecraft/245506-minecolonies#t1:other-downloads
Can you test this build here?
Just try out the things of the changelog =)

2016-12-24 13:34 GMT-02:00 xenoflot <notifications@github.com>:

**Comment by xenoflot** [comment]
edit: OK, had to delete playerdata as well.

---

Call me a stupid-head but how do I reset my colony data so I can place another? :-) I deleted world/minecolonies/colonies.dat and bounced the server, but it's still saying I have placed a town-hall previously.

**Comment by Raycoms** [comment]
./mc colony delete <colonyid|playername>

2016-12-24 21:48 GMT-02:00 xenoflot <notifications@github.com>:

**Comment by xenoflot** [comment]
OK, I dropped in the 2097.jar. Didn't change any configs. I *did* delete playerdata and world/minecolonies files because I didn't know about /mc delete :)

I can add myself as an officer and once an officer, I can alter terrain. Excellent, thank you.

Getting this non-fatal error when breaking blocks in a protected area: http://pastebin.com/GEtEjb6w

No other players online at the moment so can't test other bits.

**Comment by Raycoms** [comment]
Added config for that already.
