### ISSUE TITLE
Builder requests unsupported blocks for decorative builds

### ISSUE THREAD

**Issue by kedamono** [Minecolonies/minecolonies#295]
### Minecolonies version

version 0.4.1744

### Expected behavior

- Using the Build Tool with no hut blocks in your inventory, right click a patch of ground and select either the Simple Field or Bridge and the builder will build the structure.

### Actual behaviour

- For the field, the builder request the block "Field" and for the bridge, the item "Shrub".  Looking under the Bridge preview, there's a tuft of grass near the middle. It's easy to see if you use a clear area to build on.

### Steps to reproduce the problem

1. Create a mod folder for MC 1.10.2 that only has the Minecolonies mod in it.
2. Start Minecraft and create a new world. 
3. Start a new colony and build the builders hut.
4. Use the Build Tool to create a new, decorative build. Select Simple Field.

Result: Builder requests the block "Field".

**Comment by Kostronor** [comment]
Minecolonies provides a Field Block that is essential to the functioning of a field.

Don't know what a Shrub is but I think it is one of these gras things in Minecraft...

**Comment by kedamono** [comment]
Oh I see, it needs a specific Minecolonies block called "Field", similar to the various hut blocks. OK, thanks.

**Comment by Raycoms** [comment]
I rescanned the bridge, the shrub should be gone now.

2016-11-20 17:38 GMT-02:00 Marvin Hofmann <notifications@github.com>:

**Comment by kedamono** [comment]
Thanks Raycoms!
