### ISSUE TITLE
How to get more Citiziens?

### ISSUE THREAD

**Issue by sventx** [Minecolonies/minecolonies#296]
### Minecolonies version

minecolonies-universal-1.10.2-0.4.1776.jar
Forge: 1.10.2-forge1.10.2-12.18.2.2099

### Expected behavior

From the tutorial:
"...but you start with only 4 citizens! Now what? Well the next step after your 4 Citizens are “employed” and are working hard, is to plan and place the “Citizen’s hut”. This will give you 2 additional Citizens for each “Citizen’s Hut” ..."

### Actual behaviour
I created a colony with 2 builder huts, 1 mine, 1 town hall and 3 citizen huts. 
So I should have 10 citizens? According to town hall info I have 4 of 4.
How can i get more Citiziens?

Thanks for your help.

**Comment by Raycoms** [comment]
You can have 1 citizen per citizenHut level.
If you have 3 citizen huts they give home to 3 citizens.
In order to get more you need to build 5 citizen huts.
Or 2 citizen huts level 2 and 1 citizen hut level 1

2016-11-22 7:11 GMT-02:00 sventx <notifications@github.com>:

**Comment by sventx** [comment]
Hello,
thanks for your help. I understood your manual wrong.

Have a nice day.
