### ISSUE TITLE
Command for inactive colonies. [$15]

### ISSUE THREAD

**Issue by Raycoms** [Minecolonies/minecolonies#298]
The colony info command should have stored when the colony has last been loaded.
Might be useful to have a command which removes all colonies which have not seen a player in over a month?

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=39463507)](https://www.bountysource.com/issues/39463507-command-for-inactive-colonies?utm_source=39463507&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by marvin-bitterlich** [comment]
This should also have some config options for how long till it considers a colony abandoned. And have a list of colonies that are close to expiring. And at best delete them automatically (per config).

**Comment by Raycoms** [comment]
I actually wouldn't delete them automatically.
I would make it configurable how much time without owner/officer logging in and they will be shown in a list.
And you can do "flush list" (to delete all of them) or delete parts of them manually with the delete command.

**Comment by wesselOC** [comment]
I am busy making the changes for a PR as requested in the issue and found the word abandoned to be a long word to type. So was wondering if the word deserted might not be a better for the command.

**Comment by marvin-bitterlich** [comment]
@wesselOC This command won't be called often I guess. I'm fine with both, but I guess abandoned is more intuitive and their difference it not that much. We can always introduce aliases for power users later 😉 

@Raycoms we should make a command that flushes manually and a config option to check every hour or so automatically for servers that want that.

**Comment by marvin-bitterlich** [comment]
@wesselOC Since I can't comment on your proposal on bountysource I'll do it here:
Colony load times can be problematic, because all colonies can be loaded by explorers f.e.
So what we currently envision is storing last seen for each player (f.e. in login/logoff/other events) and then checking all members of a colony and taking the max of that.

Having a config option that automatically triggers the cleanup command would be nice to have too.

**Comment by Raycoms** [comment]
I'd say it should have an option to trigger in the config what is "outdated" like in weeks "20" weeks. and then you can execute the /mc colonies getAbandoned
which will display the whole list with a little "x" to remove them.
or you can /mc colonies flushAbandoned which remove all of them.

**Comment by marvin-bitterlich** [comment]
@wesselOC any news on your pr so far? Did you start working already?

**Comment by marvin-bitterlich** [comment]
@wesselOC I guess we can safely assume you won't work on this feature?

**Comment by wesselOC** [comment]
Hi Marvin.

Sorry got tied up at work heavily the last week. I am still planning on
working on the feature.  I have started but don't have a eta quite yet as I
am still finding my way round the current features.

Sorry about the delay.

**Comment by marvin-bitterlich** [comment]
@wesselOC alright, no problem :)
If you need any help with getting around the codebase, just ask.

**Comment by marchermans** [comment]
With regards to inactive colonies: Would it not also be a good idea to let them degrade?

**Comment by marvin-bitterlich** [comment]
That would be a good thing later on. And can be easily added on to the automatic cleanup from this issue

**Comment by wesselOC** [comment]
HI

A quick update.
What is done:
* getAbandoned and getSoonAbandoned calls.
* Configuration for the amount of weeks before a colony becomes abandoned
as well as the percentage of weeks to pass before a colony is soon
abandoned. I have added it to the category gameplay.


What I have left is:
* So what we currently envision is storing last seen for each player (f.e.
in login/logoff/other events) and then checking all members of a colony and
taking the max of that.
*  /mc colonies flushAbandoned
* Finish testing the new calls.

**Comment by marvin-bitterlich** [comment]
@wesselOC what is the status of this?

**Comment by Asherslab** [comment]
so interestingly enough i just did this

**Comment by Asherslab** [comment]
i can do a "soon to be deleted" if needed tho =D

**Comment by Raycoms** [comment]
Done that.
