### ISSUE TITLE
Suggestion: New Decorative Build type: Roads

### ISSUE THREAD

**Issue by kedamono** [Minecolonies/minecolonies#299]
### Minecolonies version

version Any Version

### Suggestion

Add a new block type: Roads

They would be 3 blocks wide and 16 blocks long. The build recipe would be wood planks surrounding a a block of gravel. The recipe makes four blocks. 

Torches or glowstone blocks are placed thusly:

  T                          
pppppppppppppppp
                 T
Torches should be 2 back from each end to allow for intersections

The different levels would be the following:

Level 1: The builder, with a shovel, creates the path block on grass or gravel on dirt, sand, or stone. (for stone, the builder will need a pickaxe.) Torches on wooden fence posts three high and one over the path: 
   T
F-F
F 
F
Level 2: Gravel path.

Level 3: Cobblestone path with torches on wooden fence posts on stone blocks:
   T
F-F
F 
S

Level 4: Cobblestone path with glowstone on stone fence posts:
S-S
S G
S
S

Level 5: Cobblestone path with glownstone on pillars

G
P
P
P

**Comment by Raycoms** [comment]
The newest update should contain some basic path decorations.
We can't upgrade roads, we can add different types though (Simple, Basic,
Great, Awesome)

2016-11-22 19:54 GMT-02:00 kedamono <notifications@github.com>:

**Comment by kedamono** [comment]
Cool, thanks for the update!
