### ISSUE TITLE
Citizens act slowly when far away from players

### ISSUE THREAD

**Issue by Johncjx** [Minecolonies/minecolonies#300]
### Minecolonies version

version 0.4.1796

### Expected behavior

- All the citizen should move and work as long as the chunks are loaded.

### Actual behaviour

- They move and work so slowly just about 10 blocks away from me.

### Steps to reproduce the problem

It's easy to reproduce.

**Comment by Raycoms** [comment]
Are you playing this on a server? With plugins?

2016-11-27 16:52 GMT-02:00 Johncjx <notifications@github.com>:

**Comment by Kostronor** [comment]
Sponge issue

**Comment by Raycoms** [comment]
Marvin, can you paste him the sponge config we added to change this? I
don't remember where it was.

2016-11-27 17:07 GMT-02:00 Marvin Hofmann <notifications@github.com>:

**Comment by Kostronor** [comment]
Sponge stops entites, there is a config to dump all entities and you 
jsut increase citizen everywhere, I think to 128 or more

**Comment by Johncjx** [comment]
Thx for your help! I just changed it. And they work well now.
