### ISSUE TITLE
Farmer not properly working

### ISSUE THREAD

**Issue by tomorrow4268** [Minecolonies/minecolonies#301]
### Minecolonies version

version X.X.1784

### Expected behavior

- when farming would replant seeds

### Actual behaviour

- when harvesting, the field is harvested, but the farmlandblock is replaced by dirt/grass
- farmers won't use hoe to regenerate it to farmland

### Steps to reproduce the problem

1. came after i uploaded that version

**Comment by tomorrow4268** [comment]
![2016-11-28_00 00 47](https://cloud.githubusercontent.com/assets/23143040/20652671/d4ce40ae-b4fd-11e6-87ee-51d9b5435b57.png)
seems like they are only using the hoe on the inner circle around the center
the building is level 4 so doesn't make sense

**Comment by Kostronor** [comment]
@Oggal

**Comment by tomorrow4268** [comment]
in fact they aren't using hoes anymore ;D

and planting is reduced.

**Comment by neadlak** [comment]
I think I am seeing some related shenanigans on my server, too.

In my game, they till their fill, plant it, and then run back and forth from their barn to the field, harvesting as wheat matures. They do not replant until the very last plant (wheat in mine) has matured and been harvested. They are replacing mature plants with a dirt block, untilled.

I understand why you do the untilled block (to have some kind of cost in materials for the hoe) but the behavior of waiting for the WORST OUTLIER plant growth is frustrating.

They also are not obeying the solid/water/airblock field boundaries that the wiki claims.

**Comment by forReason** [comment]
same here. running back and fourth, with an annoying clap fron the fence every time. Also not using the 5 stacks of bonemeal which I farmed *grrr* 😺 

![2017-01-14_19 36 25](https://cloud.githubusercontent.com/assets/12736950/21957160/ef51a32c-da90-11e6-9e16-dc692bdfc561.png)

**Comment by Raycoms** [comment]
Farmer will first gather all crops and then replant after that (will be
tweaked soon) and they don't use bonemeal at all.

2017-01-14 16:37 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by SulpherStaer** [comment]
I want to add to this issue, that I do not only expect the farmer to replant the crops (which they do after harvesting the entire field)

But also that they leave the farmland intact during harvesting, instead of destroying it and turning it into dirt.

**Comment by omega025** [comment]
Can confirm this is still an issue, and has been for me since 0.6.  My farmers will till and plant one to five blocks and then ... stop.  They will constantly walk back and forth between the field and the farmer's chest but not actually take seeds or do anything else even if they have a hoe and seeds in their inventory.

**Comment by Raycoms** [comment]
All done.
