### ISSUE TITLE
Client crash when cycling through builder's wand options

### ISSUE THREAD

**Issue by xenoflot** [Minecolonies/minecolonies#302]
### Minecolonies version

minecolonies-universal-1.10.2-0.4.1784
forge 2122
Full mod list: http://pastebin.com/m3K6ck9M

Crash log: http://pastebin.com/yCXGdD7w

### Expected behavior

- Years of endless button clicking in the build's wand GUI

### Actual behaviour

- CTD

### Steps to reproduce the problem

1. Open builder's wand GUI.
2. Hit buttons at random, about 2 or 3 per second, for about 10 seconds, trying to understand how to use the interface, and learning what things I can build.
3. Wait an agonising 20 seconds or so when the game freezes.
4. Watch in dismay as the client crashed to the desktop.

**Comment by Raycoms** [comment]
We're loading the styles from your hard drive. If you switch that fast
between decorations and huts back and forth the decorations cannot be fully
loaded and that might cause a crash.
I will do some testing later on, but I think it will be hard to avoid that.

2016-11-28 5:21 GMT-02:00 xenoflot <notifications@github.com>:

**Comment by xenoflot** [comment]
Perhaps you could discard/ignore additional clicks until the load from disk reports that its finished. Impatient users _will_ mash buttons quickly (watch people hitting the button at a crosswalk!) so it's best to prepare for that probable event.

**Comment by xenoflot** [comment]
FYI I updated to 1796 and unintentionally crashed the client again by over-clicking the builder wand buttons :) This time however, there was no problem accessing NPCs and chests after I restarted the client.

**Comment by Raycoms** [comment]
Got me! I created a fix. I will upload it when I update the guards =D

2016-11-28 21:47 GMT-02:00 xenoflot <notifications@github.com>:

**Comment by Raycoms** [comment]
fixed in the newest version.
