### ISSUE TITLE
[Suggestion] Various observations made while setting up a farm

### ISSUE THREAD

**Issue by xenoflot** [Minecolonies/minecolonies#303]
Hi,

I'm experimenting with 0.4.1784 today and I've a few suggestions relating to construction. 

Firstly, overall, I think it's really cool! I really enjoy the building system, providing materials, some custom NPCs, nicely designed buildings and so forth. Thank you very much for your hard work and generosity in sharing it with us. I think it will be a valuable and loved addition to our modpack.

1. The ghost images for decorations and huts (fountains, fields, etc.) are full opacity which makes it hard to see where things are going to be. I suggest dropping the opacity to 40% or so, to make it easier to see the terrain through the planned build.

2. I built 3 fields and then placed a farm block and told it to build. Apparently I placed the block too close to my farm because my builder proceeded to demolish parts of the fields she just worked so hard to make! Again, a transparent ghost image of the planned build, and a confirmation button, would've helped avoid this. Perhaps as a result of this, my builder is currently just walking back and forth between the site and the workshop with no forward progress.

3. Builder is ignoring construction materials that have been placed in the farm block inventory. I can see that the farm block is intended to hold seeds, but it would be helpful if it could also help the builder, and the builder check that one before she returns to the workshop.

4. If possible, have a Bill of Materials visible in the workshop and/or the current project box to indicate what the builder will need to complete the project. Ideally floating text in the way that RFTools machines display info. That way the player can get busy, rather than loitering around waiting to be told what to fetch next.

5. "Field" should be renamed to "Scarecrow". Farmer dialog is "Please select a type of seed to grow in the scarecrow. Looks like these two have had their names switched!

6. Builder with her hat is taller than a 2 block doorway!

7. Builder's dialog is very depressing :( Doesn't she know that it's her own livelihood that she's contributing to?

8. Fence gates on fields are north facing. Gap in fence of the farm is facing south. Perhaps check and reorient these depending on where they are in relation to each other?

9. Builder stands about 12 blocks away from the project she's building. Would be better if she stood closer. Perhaps 4 or 5 blocks.

10. It would be nice if we could rename our citizens.

11. My builder just completed farmer3. The last things she did was to place some buttons and then remove the row of planks they were sitting on. Now I have a couple of buttons floating in mid-air!
_(edit: floating buttons were no longer an issue by the time I'd upgraded to level 5, but definitely existed at the completion of level 3.)_

12. My farmer has planted pumpkin in the same way you'd plant wheat. i.e. on every available piece of farmland, leaving no room for the pumpkins to grow. Also, she's breaking existing pumpkin plants and planting new pumpkin seeds on the same patch.

13. I feel the farmer should do her best to put any items she doesn't need for this project in the workshop. That would save her a lot of running back and forth, I suspect!

14. Farm building has some oddly-placed orange wool blocks. They're not connected to anything.
_(edit: Orange wool blocks: http://i.imgur.com/hfUMTlX.png )_

15. Possible duping bug. I gave my builder just one cauldron for the farm building yet so far I've removed one from the workshop, one from the farm chest and one from her inventory. 
_(edit: definite dupe bug. I gave my farmer one diamond hoe. She still has that one (with some damage) but the farm chest now has two unused ones in it.)_

16. When the builder calls for a particular item, it would be helpful if she'd specify the desired quantity.

17. At the moment, I see the builder wand places the structure at the same rotation every time. The expectation set by many other mods is that the orientation is based on the direction the player is facing. I suggest for "intuitive" control, that you make it work in this way.

18. What are "birch blocks with tennis rackets" under a proposed build? Is that where the existing terrain goes? If so, I suggest you just leave those out as it's misleading. I was expecting the builder to place some blocks there. Players should be able to notice if they've positioned it such that they're floating. 

19. When the blocks of a proposed build are going to require existing blocks be removed, I suggest a red wireframe around those blocks, to indicate a conflict. At the moment it just shows the new block in its proper position and it's not clear that destruction will happen.

That's all I have for the moment. I hope you like this kind of feedback. If you'd prefer to go your own way, or to have separate issues for each idea, please let me know. I can shut up or post multiple issues as you desire :)

Cheers!

**Comment by Raycoms** [comment]
2016-11-28 9:32 GMT-02:00 xenoflot <notifications@github.com>:

> Hi,
>
> I'm experimenting with 0.4.1784 today and I've a few suggestions relating
> to construction.
>
> Firstly, overall, I think it's really cool! I really enjoy the building
> system, providing materials, some custom NPCs, nicely designed buildings
> and so forth. Thank you very much for your hard work and generosity in
> sharing it with us. I think it will be a valuable and loved addition to our
> modpack.
>
>    1.
>
>    The ghost images for decorations and huts (fountains, fields, etc.)
>    are full opacity which makes it hard to see where things are going to be. I
>    suggest dropping the opacity to 40% or so, to make it easier to see the
>    terrain through the planned build.
>
> -> We might see if that is possible without creating problems (lag etc)

>
>    1.
>    2.
>
>    I built 3 fields and then placed a farm block and told it to build.
>    Apparently I placed the block too close to my farm because my builder
>    proceeded to demolish parts of the fields she just worked so hard to make!
>    Again, a transparent ghost image of the planned build, and a confirmation
>    button, would've helped avoid this. Perhaps as a result of this, my builder
>    is currently just walking back and forth between the site and the workshop
>    with no forward progress.
>
> - We have farm decorations which should help you to avoid this.

>
>    1.
>    2.
>
>    Builder is ignoring construction materials that have been placed in
>    the farm block inventory. I can see that the farm block is intended to hold
>    seeds, but it would be helpful if it could also help the builder, and the
>    builder check that one before she returns to the workshop.
>
> - Yeah that's what we will add the deliveryman for in the future.

>
>    1.
>    2.
>
>    If possible, have a Bill of Materials visible in the workshop and/or
>    the current project box to indicate what the builder will need to complete
>    the project. Ideally floating text in the way that RFTools machines display
>    info. That way the player can get busy, rather than loitering around
>    waiting to be told what to fetch next.
>
> - Actually the newest version on curse (the mod not the modpack) contains
this kind of information in the builders GUI.

>
>    1.
>    2.
>
>    "Field" should be renamed to "Scarecrow". Farmer dialog is "Please
>    select a type of seed to grow in the scarecrow. Looks like these two have
>    had their names switched!
>
> - Field is the whole structure. (Blocks around it etc) the scarecrow is
just the block you place and you set the seeds.

>
>    1.
>    2.
>
>    Builder with her hat is taller than a 2 block doorway!
>
> - Yeah there is a price if you want nice models with hats =D

>
>    1.
>    2.
>
>    Builder's dialog is very depressing :( Doesn't she know that it's her
>    own livelihood that she's contributing to?
>
> - We're going to add new sounds for all the workers.

>
>    1.
>    2.
>
>    Fence gates on fields are north facing. Gap in fence of the farm is
>    facing south. Perhaps check and reorient these depending on where they are
>    in relation to each other?
>
>  - You actually should be able to rotate the field.

>
>    1.
>    2.
>
>    Builder stands about 12 blocks away from the project she's building.
>    Would be better if she stood closer. Perhaps 4 or 5 blocks.
>
> - We had that earlier, builder killed himself in the walls -> builder
stands away in max(length, width) of the building.

>
>    1.
>    2.
>
>    It would be nice if we could rename our citizens.
>
> - You can change that in the config options.

>
>    1.
>    2.
>
>    My builder just completed farmer3. The last things she did was to
>    place some buttons and then remove the row of planks they were sitting on.
>    Now I have a couple of buttons floating in mid-air!
>
> - Never saw that, that's strange.

>
>    1.
>    2.
>
>    My farmer has planted pumpkin in the same way you'd plant wheat. i.e.
>    on every available piece of farmland, leaving no room for the pumpkins to
>    grow. Also, she's breaking existing pumpkin plants and planting new pumpkin
>    seeds on the same patch.
>
> - Pumpkins and watermelons etc cannot be planted yet.

>
>    1.
>    2.
>
>    I feel the farmer should do her best to put any items she doesn't need
>    for this project in the workshop. That would save her a lot of running back
>    and forth, I suspect!
>
> - Farmer is work in progress atm.

>
>    1.
>    2.
>
>    Farm building has some oddly-placed orange wool blocks. They're not
>    connected to anything.
>
> - Scan failure will correct that soon.

>
>    1.
>    2.
>
>    Possible duping bug. I gave my builder just one cauldron for the farm
>    building yet so far I've removed one from the workshop, one from the farm
>    chest and one from her inventory.
>
> - Very strange will have to investigate that

>
>    1.
>    2.
>
>    When the builder calls for a particular item, it would be helpful if
>    she'd specify the desired quantity.
>
> - Will be added in the future.

>
>    1.
>    2.
>
>    At the moment, I see the builder wand places the structure at the same
>    rotation every time. The expectation set by many other mods is that the
>    orientation is based on the direction the player is facing. I suggest for
>    "intuitive" control, that you make it work in this way.
>
> - The builder wand has a "rotation" functionality.

>
>    1.
>    2.
>
>    What are "birch blocks with tennis rackets" under a proposed build? Is
>    that where the existing terrain goes? If so, I suggest you just leave those
>    out as it's misleading. I was expecting the builder to place some blocks
>    there. Players should be able to notice if they've positioned it such that
>    they're floating.
>
> - It's called waypoint and it's made out of substitution blocks. If you
place that workers will use it as an orientation to pass by that if
possible.
The substitution blocks are never placed, they will adapt to the block
which is already at that place.

>
>    1.
>    2.
>
>    When the blocks of a proposed build are going to require existing
>    blocks be removed, I suggest a red wireframe around those blocks, to
>    indicate a conflict. At the moment it just shows the new block in its
>    proper position and it's not clear that destruction will happen.
>
> - We reworked the whole build tool, but it's now harder to add this kind
of stuff.

**Comment by xenoflot** [comment]
Thanks very much for the comprehensive and detailed reply! My thoughts below.

2. Structure overlap & destruction
-> We have farm decorations which should help you to avoid this.
OK, that does help if you know it's there. However I expect a lot of players will just plop the block down and hit the Build button.

5. "Field" should be renamed to "Scarecrow".
-> Field is the whole structure. (Blocks around it etc) the scarecrow is just the block you place and you set the seeds.
OK in retrospect that explains the farmer's dialog but as of 0.4.1784, the scarecrow item in your inventory, and via TheOneProbe, is called "Field". I feel it should be called "Scarecrow".

8. Fence gates on fields are north facing.
-> You actually should be able to rotate the field.
OK. It'd be nice if it automatically rotated the building (since it knows where they are relative to it) but I can live with manual orientation.
Actually... is it possible to reorient the main farm building? Or just the fields? I actually built 3 fields before placing the farm block.

10. It would be nice if we could rename our citizens.
-> You can change that in the config options.
Good to know, but for server play, it would be nice if the players could personalise their own citizens.

17. Structure rotation
-> The builder wand has a "rotation" functionality.
I noticed that but since I work in UI design, I felt it worth mentioning. Users are trained by other programs to do certain things. E.g. move the mouse a certain way. Left-click to hit, right-click to activate. If a new program conforms to "the standard way of doing things" then users will perceive it as being "intuitive". If it requires a different technique, they'll feel it is complicated. You do have a way to rotate it, but it's not the standard face-to-orient, wrench to rotate way that countless mods have used over the years. Your way isn't wrong, but many users will feel it's "complex". Obviously it's your call. I just wanted to suggest it.

18. Tennis rackets
-> It's called waypoint and it's made out of substitution blocks...
So... NPC pathing? That's something the user probably doesn't need to know about, and presenting it visibly will result in confusion (as it did with me). Perhaps have a config option showWaypointBlocks=true for use in debugging?

Cheers!

**Comment by Raycoms** [comment]
2016-11-28 10:13 GMT-02:00 xenoflot <notifications@github.com>:

> Thanks very much for the comprehensive and detailed reply! My thoughts
> below.
>
>    1.
>
>    Structure overlap & destruction
>    -> We have farm decorations which should help you to avoid this.
>    OK, that does help if you know it's there. However I expect a lot of
>    players will just plop the block down and hit the Build button.
>
> - Yeah that's why we filled up the wiki, added achievements for the build
tool and videos. Probably adding more hints later.

>
>    1.
>    2.
>
>    "Field" should be renamed to "Scarecrow".
>    -> Field is the whole structure. (Blocks around it etc) the scarecrow
>    is just the block you place and you set the seeds.
>    OK in retrospect that explains the farmer's dialog but as of 0.4.1784,
>    the scarecrow item in your inventory, and via TheOneProbe, is called
>    "Field". I feel it should be called "Scarecrow".
>    3.
>
>    Fence gates on fields are north facing.
>    -> You actually should be able to rotate the field.
>    OK. It'd be nice if it automatically rotated the building (since it
>    knows where they are relative to it) but I can live with manual orientation.
>    Actually... is it possible to reorient the main farm building? Or just
>    the fields? I actually built 3 fields before placing the farm block.
>
> - You can rotate everything with the build tool.

>
>    1.
>    2.
>
>    It would be nice if we could rename our citizens.
>    -> You can change that in the config options.
>    Good to know, but for server play, it would be nice if the players
>    could personalise their own citizens.
>
> - We just want to avoid people giving "dirty" names to the citizens which
would fall back to our mod.

>
>    1.
>    2.
>
>    Structure rotation
>    -> The builder wand has a "rotation" functionality.
>    I noticed that but since I work in UI design, I felt it worth
>    mentioning. Users are trained by other programs to do certain things. E.g.
>    move the mouse a certain way. Left-click to hit, right-click to activate.
>    If a new program conforms to "the standard way of doing things" then users
>    will perceive it as being "intuitive". If it requires a different
>    technique, they'll feel it is complicated. You do have a way to rotate it,
>    but it's not the standard face-to-orient, wrench to rotate way that
>    countless mods have used over the years. Your way isn't wrong, but many
>    users will feel it's "complex". Obviously it's your call. I just wanted to
>    suggest it.
>
> -> If you want, we always need people doing programming work. Redesigning/
programming our interfaces and some of the functionalities would be
interesting as well.
There is an "apply for the team button" on our website if you're
interested.

>
>    1.
>    2.
>
>    Tennis rackets
>    -> It's called waypoint and it's made out of substitution blocks...
>    So... NPC pathing? That's something the user probably doesn't need to
>    know about, and presenting it visibly will result in confusion (as it did
>    with me). Perhaps have a config option showWaypointBlocks=true for use in
>    debugging?
>
> -> It's not just for debugging. Let's say you build a nice path to a
certain location but the workers just walk the shortest path to this
location. If you place these waypoint blocks on the path, they should
follow them in some sort.
We'll release some more details like guides and videos about that later on.

**Comment by xenoflot** [comment]
Thanks again for the responses. Unfortunately I'm an IT guy not a coder. I'm still having trouble figuring out decompworkspace. When I have a clue though, I might apply :)

**Comment by pmardle** [comment]
I built 3 fields and then placed a farm block and told it to build. Apparently I placed the block too close to my farm because my builder proceeded to demolish parts of the fields she just worked so hard to make! Again, a transparent ghost image of the planned build, and a confirmation button, would've helped avoid this. Perhaps as a result of this, my builder is currently just walking back and forth between the site and the workshop with no forward progress.

USE THE BUILD TOOL !!!

**Comment by pmardle** [comment]
> Fence gates on fields are north facing.
-> You actually should be able to rotate the field.
OK. It'd be nice if it automatically rotated the building (since it knows where they are relative to it) but I can live with manual orientation.
Actually... is it possible to reorient the main farm building? Or just the fields? I actually built 3 fields before placing the farm block.

USE THE BUILD TOOL ;)

**Comment by pmardle** [comment]
> The builder wand has a "rotation" functionality.
I noticed that but since I work in UI design, I felt it worth mentioning. Users are trained by other programs to do certain things. E.g. move the mouse a certain way. Left-click to hit, right-click to activate. If a new program conforms to "the standard way of doing things" then users will perceive it as being "intuitive". If it requires a different technique, they'll feel it is complicated. You do have a way to rotate it, but it's not the standard face-to-orient, wrench to rotate way that countless mods have used over the years. Your way isn't wrong, but many users will feel it's "complex". Obviously it's your call. I just wanted to suggest it.

Can you perhaps re-design the GUI interface to demonstrate what you mean?

**Comment by xenoflot** [comment]
(Sorry for the wall of text that follows but what I mean is not demonstrable with a simple image!)

To clarify/condense/expand on what I've said above... the less a user needs to RTFM, the quicker they can be productive and the happier they are. Users should be able to figure out most functions of a piece of software by just playing with it for a while. Sure, for some advanced stuff they might need to refer to the documentation, but the basics should be easily discoverable. A keyword there is _easily_. 

The way to achieve that is to employ modes of interaction that users are already familiar with. For example, pick up almost any piece of software on any computer and any platform. The basic tools (mouse, keyboard and screen) work the same way. They all provide a menu in more or less the same place and you can find Open/Save/Load/Print in similar places. Not teaching anyone to suck eggs here, just providing the background that puts the next bit in context.

Minecraft uses a first-person-perspective, manipulative interaction paradigm. That is, "you do stuff as if you were there in person". GUIs break that paradigm. Were I the product manager, I would remove as many functions from GUIs as I could, and replace them with in-world manipulation.  To stay true to the MC paradigm, placing a "build a farm plot here" flag is more suitable than clicking some buttons. Other mods use wrenches, wireframes and translucent ghost images to show users where things will be and allow them to manipulate the mod blocks. By employing a different way of interacting, you're not making use of the player's existing familiarity with "the way things work".

Also, complex GUIs are often overwhelming. I felt the builder's wand GUI to be that way. Too many buttons and too big (I run in 1600x1200 with a medium UI scale. Not sure if the wand GUI auto-scales but I felt it was too big.)

Similarly, iconography should be as instructive as possible. For example, I feel the "tennis rackets" motif on the waypoints doesn't suggest its function very well. A transparent wire-frame with a "walking feet" motif would more clearly suggest what it does.

With regards to the construction process, I would...

* I'd add a new block type to the game, a Builder Block. Perhaps it looks like a banner sitting on a stone brick (and there's your recipe!) This functions as a focus point for the AI to construct the structure, and as a manipulation point for the player. The Builder Block would be destroyed as the last step of the construction process. You'd probably need one for each category of structure. Perhaps _"Functional Buildings"_ like the Town Hall, Workshop, NPC housing, Player housing, _"Resource Structures"_ like the Farm, and _"Decorative Structures"_ like fountains, roads and bridges.
* When you place the Construction Marker, a low opacity ghost will appear. Floating text can hover over the block to clearly label what you're going to build. It will be the first on a list of structures that this type of block can produce. If the categories are sufficiently fine, the list shouldn't be too long. A left-click with the builder's wand will loop the block through the list, displaying each of the possible ghosts.
* Have the structure (and it's ghost) oriented with the front (doorway, fencegate, etc.) facing towards the player. By right-clicking any face of the block with the builder's wand, the block will rotate the front of the structure towards that direction. As simple as that. Right clicks on the top or bottom will be ignored unless you have structures for which Up/Down is a valid "front".
* When the player is happy with the orientation, they shift-left click on any face to commence construction. I don't think separate confirmation is required if it's done this way.

Let's get even more _immersive!_   Rather than crafting a Construction Marker, the player right clicks on their Builder NPC. No GUI pops up. Instead, the Builder engages the player in a dialog. 

---

Hi Xenoflot, how can I help? Build Something / Go Home / You're fired!

Sure, what would you like me to build? Building / Resource / Decoration

OK, what kind of building would you like? Farm / Workshop / House / Tavern

OK, Place this marker where you want the tavern built. (Drops a marker on the ground) When you're happy with the placement and orientation, hit it with a builder wand while sneaking, and I'll get onto it.

---

Sadly I can't code very well. I was serious when I said that setupDecompWorkspace is giving me trouble :) Your team application made it quite clear that you were looking for coders, not advisers so I didn't put in an app. If you _are_ interested in non-coding team members, I'm happy to sign up and see where I can help.

**Comment by xenoflot** [comment]
Hi guys, testing again with the latest version again.

Users hate reading manuals and will only do so as a last resort. That's a simple fact of life. Accordingly, some in-game helpers would work towards making the process more friendly. 

* One that occurred to me just now is that it's not intuitive that you need to make a builder's hut *after* you place the town hall. Surely logic would have you create the builder's hut first. I'm sure that's for programmatic reasons so for player experience reasons, I suggest after placing the town hall block, a console message pops up to say *"Use the Builder's Wand to create a Builder's Hut. The Town Hall will be constructed after you hire a builder!"* Perhaps also this could be a prominent message on the Town Hall GUI.

* I note that in your tutorial you instruct players to use the building wand to place the town hall so as to take advantage of the placement preview. May I suggest that you enforce that by making the town hall block unplaceable (or an item)? When the user attempts to place or use the item, they can get a console message like *"Use the Builder's Wand to place the <itemname>!"*

Cheers!

**Comment by marvin-bitterlich** [comment]
Hey @xenoflot if you want to contribute to ideas, commenting on github issues helps a lot! Also having someone look at useability is a good thing.

Currently our focus is not on adding more tutorial, because we want features first and our team is too small to work on both. We are long time planning an interactive guide book that will help you.

**Comment by xenoflot** [comment]
Cool :) Get #350 fixed and I'll get back to playtesting and commenting :)

**Comment by Raycoms** [comment]
Should be done as well.
