### ISSUE TITLE
[Suggestion] Farmer

### ISSUE THREAD

**Issue by Inaeo** [Minecolonies/minecolonies#304]
I know Farmers are still WIP, but I propose having them harvest plants with a right-click (seeing as that's a Vanilla mechanic now) rather than breaking the plant and replanting the crop.  Not only will this lead to more effective farms (due to inconsistent seed drop rates), but it would improve the overall mod compatibility (Pam's Harvestcraft crops drop vegetables rather than seeds, so no replanting is going to happen).

Thanks for your time and hard work.

**Comment by kedamono** [comment]
Yes, please add right-click to harvest!

**Comment by Raycoms** [comment]
they right click to harvest for all harvestcraft crops.

2016-11-28 16:14 GMT-02:00 kedamono <notifications@github.com>:

**Comment by kedamono** [comment]
Is this in the current build? Because my Farmer is breaking the corn crops still.

**Comment by Raycoms** [comment]
It should be @oggal.

2016-11-28 16:31 GMT-02:00 kedamono <notifications@github.com>:

**Comment by kedamono** [comment]
OK, I'll double check. I was busy with other issues.

**Comment by kedamono** [comment]
Ok, one of the fields I have planted in Pam's Corn. And the farmer broke them. I'm running minecolonies-universal-1.10.2-0.4.1796.jar on Minecraft 1.10.2.

**Comment by Raycoms** [comment]
Should be done.
