### ISSUE TITLE
[Suggestion] Woodcutter range limits

### ISSUE THREAD

**Issue by Baughn** [Minecolonies/minecolonies#305]
It would be good if the woodcutter could be stopped from cutting down every tree he can reach, e.g. the trees planted on top of my hobbit burrow, or the fruit trees outside.

In general I'd just like to have a predictable range, but... perhaps fences can be used as landmarks?

**Comment by pmardle** [comment]
I think you might be able to place a block of cobble under the trunk - this should stop the Lumberjack cutting it (assuming we added that as part of our tree check!)
