### ISSUE TITLE
1.8.9-0.2.113 - Builder Things

### ISSUE THREAD

**Issue by pmardle** [Minecolonies/minecolonies#31]
Ok,

1) - Please can we have a confirmation on Firing a worker.. I fired my builder half way through building the builders hut accidentally.  Hired the same citizen back as the builder, who then proceeded to ask for an axe, and then demolished the whole builders hut that was built to start the level 1 hut again :package:

**Comment by cltnschlosser** [comment]
Yea, thats known I was against that change, but marvin said he was going to save this information in the Job. This would also happen if the server restarted.

**Comment by Kostronor** [comment]
We are currently saving that in the job like you suggested. I remember giving in to you 😜

Am 17.08.2016 02:39 schrieb Colton Schlosser <notifications@github.com>:

Yea, thats known I was against that change, but marvin said he was going to save this information in the Job. This would also happen if the server restarted.

**Comment by cltnschlosser** [comment]
Are we saving it? I remember the conversation, but I don't remember the change ever being implemented

**Comment by Kostronor** [comment]
We are definitely saving some state! @Raycoms could explain more

**Comment by cltnschlosser** [comment]
@Raycoms Fixed this in #54
