### ISSUE TITLE
New Decorations: City Walls

### ISSUE THREAD

**Issue by kedamono** [Minecolonies/minecolonies#310]
### Minecolonies version

All future versions 

### Suggestion

As this mod progresses, being able to build walls around the village would be important. We could have a couple of styles: Wood palisades made up of logs and wooden planks, Cobblestone Walls, and Stone Brick Walls. They would have a walkway one block down so Archers can walk along them. 

The wall section would be the same length as a path and tall enough so that a spider cannot climb over. Guard towers would form the corners, though on the inside of the walls.

I'd also add a gate, same length as a wall, consisting of two towers and a double door gate. The wooden and cobblestone versions, the doors are made of wood. At the Stone Brick level, the doors are made of iron and uses stone buttons to open.

**Comment by pmardle** [comment]
Guard towers are already designed to allow walls to come off from either side..

I will be adding complimentary walls into the decorations (I was waiting for the coders to implement a new section in the build tool specifically for walls :) ) soon that will allow you to get the builder to build wall sections. :)

**Comment by kedamono** [comment]
But will they let the guard tower be a corner tower? I can see how it would work for side tower, but wouldn't the wall block the entrance into the tower when it's at a corner?

And thanks for all your hard work on this! This has really put me back on my game with Minecraft.

**Comment by pmardle** [comment]
yeah corner towers are a pain :P

**Comment by Raycoms** [comment]
the entrance could be through the wall section.
why don't you make a path inside the wall as well?

2016-12-01 8:44 GMT-02:00 pmardle <notifications@github.com>:

**Comment by kedamono** [comment]
I'd have to see how the walls work first before commenting. Right now I'm having a hard time getting my paths to line up, I'm not so sure it how the walls will line up.

**Comment by Raycoms** [comment]
Added a lot of them. I think we can close this.
