### ISSUE TITLE
Suggestion: Trader NPC

### ISSUE THREAD

**Issue by kedamono** [Minecolonies/minecolonies#311]
### Minecolonies version

Future version.

### Suggestion

On a multiplayer server where the players have their own colonies, having a means of trade would be important. So for this we need a Trader NPC. 

Their hut would be built next to the Storage Hut and uses that inventory to trade with.

You get a number of Traders equal to the Trade hut level, and that are available from a Citizen's hut. The Trade hut has the Master Trader who doesn't travel, but stays in place making deals. 

The other traders travel to other colonies that have Trader huts with goods for trade. 

The GUI for the Traders hut let's specify one item that you absolutely have to have and a priority for that item, from 1 for highest, to 4 for lowest. You can also set up to four items you're willing to trade for that item and how many of each item.

When a trader with the item is encountered, they use a simple bidding system of offering an item, one at a time, until the other trader's want level is hit, or fails. 

The Master Trader keeps a journal that you can look at to see how different trades have gone. 

At Level 1 and 2, the traveling traders walk to the other colonies, placing a torch as a breadcrumb every 16 blocks. So with a stack of 64 torches, they can travel up to 1,024 blocks, though realistically I'd set the maximum distance to 512 blocks. They will not cross mountains and try to find away around it within their range. If they cannot, they will let you know.

Level 3 and 4, the traveling traders can ride horses, and the Trade hut now has a set of stables and leads to keep the horses in place. 

At level 5 they can ride mine carts to the destination.

**Comment by pmardle** [comment]
Markets and inter colony trading is planned and the detail of this has been sketched out - currently available to our Patreons to read and comment on ;)

**Comment by kedamono** [comment]
Ah, a sly dig to join the Patreon. :) 

Sure, I want to support this project!

**Comment by pmardle** [comment]
We treat our Patreons as sounding boards for initial concepts and designs, to get some user feedback before we send too much time designing/coding a system..  one of their perks I suppose :)

**Comment by kedamono** [comment]
I've joined, so I'll take a dip in the community and see what's up!

**Comment by pmardle** [comment]
Have you e-mailed me your website name so I can give you the resultant access?

**Comment by kedamono** [comment]
I have several websites and I didn't know I had to email one to you. Do you mean my Minecraft username? It's JohnReiher.

**Comment by pmardle** [comment]
No, your Enjin username (www.minecolonies.com) - so I can give you the
relevant tag there so you can acces the Patreon part of the website (and
forum)

Did your "welcome" e-mail from Patreon not ask you to send that info to
me..?

**Comment by kedamono** [comment]
Ah, well I kept it simple, JohnReiher is also my Enjin name as well.

**Comment by Raycoms** [comment]
We have an issue for that already.
