### ISSUE TITLE
Pathing AI Gridlock on Guard Towers

### ISSUE THREAD

**Issue by neadlak** [Minecolonies/minecolonies#312]
### Minecolonies version

version 0..4.1796 (minecolonies testpack 0.483 with mods added)

### Expected behavior

- Per patch notes, colonists use hut blocks as pathfinding waypoints. This should improve colonist pathing through the town.

### Actual behaviour

- Multiple colonists attempt to route through a guard tower hut block and create gridlock, pushing each other off the ladder with neither able to go down. Guard is stuck on tower, as well as colonist.

### Steps to reproduce the problem

1. Build level 1 guard tower
2. Build other structure nearby (in my case, miner hut)
3. Wait for nightfall/dawn when colonists go home and leave home
4. If guard tower is selected as waypoint, colonist climbs tower to touch the hut block.
5. If the guard or another colonist are present, they may jam up the ladder.
6. Now your miner isn't working and your guard cannot patrol.

![2016-12-02_17 34 13](https://cloud.githubusercontent.com/assets/16522197/20856245/cdb090d0-b8b6-11e6-9b87-e1c0d57088fb.png)

**Comment by neadlak** [comment]
Simplest fix would be to exclude guard towers from waypoints for the time being?

**Comment by Raycoms** [comment]
Thanks for the support, they actually shouldn't get up at all.
We'll have to fix this.

2016-12-03 0:44 GMT-02:00 neadlak <notifications@github.com>:

**Comment by neadlak** [comment]
For the time being, I'm able to get my colonists routing around the towers by using waypoints nearby.

**Comment by Raycoms** [comment]
should be solved with our new tower design
