### ISSUE TITLE
Modded Tools, Tinker's Tools, Modifiers, and Enchantments.  Also a View.

### ISSUE THREAD

**Issue by HeavyDeception** [Minecolonies/minecolonies#315]
### Minecolonies version

version 1.10.2-v0.5v18 on curse v7.2.6181.8953 alpha

Can the NPCs use modded tools like the AIOT form actually additions or the Drill from IC2, Actually Additions, and Immersive Engineering. someway for them to be like oh the power on this is low If I put it in this chest or this block I can got it back at full power. Or give us a way to tell them that if its low were to put it or they can put it back into there huts box.

This is more of a question I have tinkers installed and was wondering if some of the tool ability's could work for the colony workers like the lumber ax cutting a full trees down or a hammer mining a 3x3 tunnel. Also do enchants or Modifiers on tools in Tcon or Vanilla work with the NPCs

Now to the final question or suggestion is or could there be away to see the building before you place it. like how big its going to be. then the builder is going to build it or can you use the building wand for that too?

Sorry for the wall of text.

**Comment by HeavyDeception** [comment]
I now see how the building wand works

**Comment by Raycoms** [comment]
Our workers will use all tools which derive from the minecraft vanilla
tools.

They work well with tinkers, but probably don't work with the IC2 or
similar tools.

2016-12-03 14:06 GMT-02:00 HeavyDeception <notifications@github.com>:

**Comment by HeavyDeception** [comment]
@Raycoms thank you. do enchants work?

**Comment by Raycoms** [comment]
they do.

2016-12-03 23:31 GMT-02:00 HeavyDeception <notifications@github.com>:

**Comment by HeavyDeception** [comment]
@Raycoms Also dose the farmer work with modded plants? Because Right now it doesn't look like it.

**Comment by Raycoms** [comment]
he should. he might be  slow. will fix it soon.

2016-12-03 23:50 GMT-02:00 HeavyDeception <notifications@github.com>:

**Comment by HeavyDeception** [comment]
@Raycoms Thank It also seems like the builder uses tools really slow will do some more test to see if its just the bronze tools.

**Comment by Raycoms** [comment]
he starts off really slow and improves while he levels.

2016-12-04 0:07 GMT-02:00 HeavyDeception <notifications@github.com>:

**Comment by HeavyDeception** [comment]
Ok thats a lvl thing my bad I'm still reading the wiki

**Comment by HeavyDeception** [comment]
Oh so if I add silk touch to a toll form Tinker's it doesn't work.

**Comment by HeavyDeception** [comment]
This is just a thing that bugs me but the table in the builders hut is turned the wrong way is there away to fix that?

**Comment by HeavyDeception** [comment]
@Raycoms The Frarmer Dose not see the Mattock as a hoe from Tcon (The mattock is a Hoe, Shovel, and axe.

**Comment by HeavyDeception** [comment]
@Raycoms I would love to help make some of the builds for you guys if you want the help?

**Comment by Raycoms** [comment]
Yeah the mattack is not a hoe, it's a new tool introduced by tinkers,
that's why it isn't recognized.
We have a scan tool.
Feel welcome to create your own style and upload it to the forums!

And no, for the time being the builders hut faces that way =(

2016-12-04 14:19 GMT-02:00 HeavyDeception <notifications@github.com>:

**Comment by HeavyDeception** [comment]
@Raycoms Ok I will do that and this should be the last think Do you guys pla on making it were the NPCs use the chests in there area because that would be great. thanks.

**Comment by Raycoms** [comment]
We will create a deliveryman which will deliver the stuff from a warehouse
to the workers.

2016-12-05 8:53 GMT-02:00 HeavyDeception <notifications@github.com>:

**Comment by ffuentesm** [comment]
For some reason, it does not recognize Silent Gear tools. 
I am playing on 1.17 and the NPC did not recognize the shovel that I gave it when it was requested. 
It asked for a wood/gold shovel to build the builder's hut, I gave a silent gear wood shovel. 
It did not work.
