### ISSUE TITLE
Wierd Behavior

### ISSUE THREAD

**Issue by drago87** [Minecolonies/minecolonies#318]
### Minecolonies version

version 0.1.1870

### Expected behavior

Using energy tools drain energy when mining (dracon evulotion's tools the only one tested)

Recall button off miner recalling the miner to the "chest"

### Actual behaviour

Tools have infinite durability

Recall button off miner dont recall the miner after having 100+ nodes on level 12

### Steps to reproduce the problem

1. Giv a miner a Draconic tool with energy

This error is what i get from the MultiMC Console window when i press the Recall button for the miner.
The Builder still works
[Minecolony error.txt](https://github.com/Minecolonies/minecolonies/files/629922/Minecolony.error.txt)

**Comment by Raycoms** [comment]
Yeah we would have to add a draconic tool compatability for the miner.
Since these tools probably only recognize players as valid users and don't
use the classic damage tool methods.
The miner should still be recalled that's a strange problem. Try to
"fire/rehire" him.

2016-12-04 21:48 GMT-02:00 drago87 <notifications@github.com>:

**Comment by drago87** [comment]
well i manage to get the miner out of the mine by fire him but as soon as i hired him agen he went right back down and got stuck in a corner. is there a setting/log i sould include to make it easier for you? and the recall buton still spams the log.

**Comment by Raycoms** [comment]
what happens if you click recall?

2016-12-05 13:41 GMT-02:00 drago87 <notifications@github.com>:

**Comment by drago87** [comment]
Nothing in game. the Log is spaming what i posten in the first post

**Comment by Raycoms** [comment]
Could you try to make space next to the miner hut block, it seems like your
miner can't find a proper point to spawn next to the hut block.

2016-12-05 14:20 GMT-02:00 drago87 <notifications@github.com>:

**Comment by drago87** [comment]
that was it. had put some chest on eather side of it

**Comment by Raycoms** [comment]
other thing. We have some problems due to the minecraft pathfinding with
pathing with too many nodes underground. you might have to set him mining
on a higher level in that case.
We will fix that eventually though.

2016-12-05 14:39 GMT-02:00 drago87 <notifications@github.com>:
