### ISSUE TITLE
Farmer to harvest up to 4 crops per plot.

### ISSUE THREAD

**Issue by Wissi** [Minecolonies/minecolonies#319]
I think a good enhancement is to have the "field" block able to handle up to 4 different crops per plot. Since the plot is a max of 11 x 11 and there are already 6 "vanilla" harvestable crops plus sugar canes and cactus not to mention all the modded crops available (for example: pam's harvest has 36+ crops).

If 1 crop - 100% of the plot will be used per crop.  (120 blocks max)
If 2 crops - 50% / 50% of the plot will be used per crop.  (60 blocks max each)
If 3 crops - 33% / 33% / 33% of the plot will be used per crop.  (40 blocks max each)
If 4 crops - 25% / 25% / 25% / 25%  of the plot will be used per crop.  (30 blocks max each)

Level 1 Farmer hut, farmer will only be able to harvest a max of 4 crops.
Level 2 Farmer hut, farmer will only be able to harvest a max of 8 crops.
Level 3 - 5 Farmer hut, farmer will only be able to harvest a max of 12 crops.

**Comment by pmardle** [comment]
No.. This is part of the design that a farmer can only handle a maximum of 4 crops really.. (you can build as many fields as you want and "crop rotate" the fields the farmer works on of course ;)

Realistically you will need several farmers in the future to handle a medium/large size colonies food requirements..

**Comment by Wissi** [comment]
Does this mean that a Farmer hut level 5 will have 4 "fields" he can take care of? Currently it is only 3 "fields".

**Comment by Raycoms** [comment]
Yes. Eventually xD

2016-12-06 20:28 GMT-02:00 Wissi <notifications@github.com>:
