### ISSUE TITLE
1.8.9-0.2.113 - Builder Chest

### ISSUE THREAD

**Issue by pmardle** [Minecolonies/minecolonies#32]
Ok, When a builder needs an item.. If it is in his chest he will take it and use it..  If it is not in his chest, he will stand by the chest.  Give the item/block directly to the Builder (throw it at him, or manually place in his inventory) and he will use it.  Put it in his chest.... and he can't see it !!

I can replicate test this by making him build something and when he needs say Oak Planks..  put a stack in  his chest and he ignores..  Then give him 1 or 2 blocks manually..  he will go and use those 2 blocks, then come back to his chest to collect the rest..

So I guess there is no period re-check of the builders chest contents after an initial check as soon as he needs something.  This needs to be fixed as he currently wouldn't see any deliveries to his chest by the delivery man.

**Comment by cltnschlosser** [comment]
When was this fixed?

**Comment by Raycoms** [comment]
I fixed that in: 3310b5d0c3fea215642375143abc8b41b69937f3
