### ISSUE TITLE
Anti-Griefing System

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#5]
We need to have colonies protected from Griefing - I do not want people to have to rely on a 3rd party world protection system.

In tandem with the permissions system, if someone is Neutral or lower to a colony, they should not be able to place or break any blocks within someone else's colony boundary... This could be as simple as effectively setting them to Adventure Mode when they cross the boundary for now.. but we also need to consider the following.
- How to stop Static TNT or TNT from Cannons damaging the colony within the boundary
- How to stop flowing water or Lava entering and damaging/affecting the colony
- How to stop fire propagation across a boundary

Subtasks:
- [ ] Handle permissions for general colony interactions (Opening GUIs and inventories)
- [ ] Handle block and fluid placement inside the colony.
- [ ] Handle picking up blocks or opening normal chests inside the colony.
- [ ] Handle attacking entities inside or from outside the colony (Arrow, sword)
- [ ] Handle explosions from inside/outside (tnt cannons, nukes, creepers)
- [ ] Toggle warefare (allow certain war interactions in certain cases)
- [ ] Colony should be protected from y = 0 until y = 250? 
- [ ] Control messages, client messages must be checked (Most of them are)
- [ ] Players maybe should even be unable to drop stuff (Fill citizen inventory to block him)
- [ ] Mod interactions, magical placement, computer craft placement etc?

**Comment by pmardle** [comment]
1st thing to do is trigger/force Adventure mode for anyone who is not a server OP upon entering the colony boundary if they are not a Friend or Above in the Colony. (and also revert back again upon leaving.

That will probably do as a start and we can figure the other bits out over time.

**Comment by Kostronor** [comment]
That sounds like a great idea! We would have to remember the gamemode though or always switch back to default mode upon leave

**Comment by cltnschlosser** [comment]
I think we are probably better off using forge events.
Also I see this as being pretty low priority, obviously its only useful once we have more server content, but also its not common for mods to have grief protection

**Comment by Raycoms** [comment]
Pretty often severs come with their own grief protection they can activiate
for player colonies as well.

2016-08-27 22:39 GMT-03:00 Colton Schlosser <notifications@github.com>:

**Comment by pmardle** [comment]
Not many mods have grief protection because they don't need to.  Standard
server grief protections aren't going to cut it for us if we want PvP
server play with minecolonies..

**Comment by Kostronor** [comment]
Mods like towns have grief protection build in and I think minecolonies should too.

**Comment by pmardle** [comment]
It definitely needs something yes.

**Comment by Isfirs** [comment]
- BlockEvent.PlaceEvent
- BlockEvent.BreakEvent
- PlayerInteractEvent
- AttackEntityEvent
- LivingAttackEvent
- ItemTossEvent
- EntityItemPickupEvent
