### ISSUE TITLE
Clean up old code

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#50]
Since some areas of the code are at least subpar, we should go over them and clean that up.

Currently worked on by @Isfirs in discussion with @Kostronor

**Comment by Isfirs** [comment]
https://github.com/Minecolonies/minecolonies/wiki/Classes-&-Interfaces

Please check

**Comment by Isfirs** [comment]
https://github.com/Minecolonies/minecolonies/wiki/Methods

Please check

**Comment by Raycoms** [comment]
We will need this issue @Kostronor ?

**Comment by Kostronor** [comment]
We have the formatter so for now we should be fine. The wiki needs work though...
