### ISSUE TITLE
Translation And Bugs

### ISSUE THREAD

**Issue by EnderT5** [Minecolonies/minecolonies#67]
### Minecolonies version
MineColonies 1.8.9 0.3.472
### Expected behavior
1. Translated Achievements Menu (Turkish)
2. Some Alerts Should Translated
3. POEditor Should Have All Words in MineColonies (like WorkOrders)
4. Builder Shouldn't Be Stuck

### Actual behaviour

1. Untranslated Achievements Menu (English Achievements but Game Is Turkish)
2. Some Alerts Just Pops Out Code-Like Words (While in Turkish)
3. POEditor Hasn't Got WorkOrders word for translation.
4. Builder Stucks A While When He/She Builds His/Hers Hut.

### Steps to reproduce the problem
Just Look At This Pictures: http://imgur.com/a/7vQEs

**Comment by Kostronor** [comment]
So you need to add translations? The keys com.minecolonies.aaa are missing translations for your language.

@Raycoms needs to update the strings on POEditor

**Comment by EnderT5** [comment]
Not only that, i translated achievements but translation not added to the game. And my latest translations  not added to the mod.
