### ISSUE TITLE
Change schematica

### ISSUE THREAD

**Issue by JoseluGames** [Minecolonies/minecolonies#69]
Change schematica to JoseluGames's aproach to preview structures

**Comment by JoseluGames** [comment]
Should I change schematica in favor of this? @cltnschlosser

**Comment by Isfirs** [comment]
How is the management done later?

Some kind of `/resourcepacks` like `/schemapacks` where you can upload a structure of schemas inside a zip file?

**Comment by JoseluGames** [comment]
The structure files (.nbt format) are stored inside assets/MODID/structures/STRUCTUREPATH_NAME, I'm not sure if it can be overwritten with resource packs like textures and sounds, most probably yes @Isfirs

**Comment by Isfirs** [comment]
Would be great to deliver the old `classic` pack and have a drop-in for new stuff in a way already exists.

- `ressourcepacks` uses it
- `shaderspack` uses it
- doing it the same way we show we follow systems that exists already

I could help on the structure validation and reading. I worked with `ZipEntry` already and would like to get some new ideas when doing this loader ;)
