### ISSUE TITLE
Build tool sometimes places huts facing into the wrong direction.

### ISSUE THREAD

**Issue by Raycoms** [Minecolonies/minecolonies#71]
### Minecolonies version
Newest
### Expected behavior
Rotate and place the hut facing the wanted direction.
### Actual behaviour
Sometimes faces opposite direction.
### Steps to reproduce the problem
Place a hut using the build tool, probably citizen hut at east or west will work.

**Comment by DarVillous** [comment]
Steps to reproduce-

1. Use the build tool
2. Rotate the hut
3. Press Esc to close the build tool
4. Use the build tool and cancel the placement with the cancel button
5. Use the build to place a hut
6. Confirm the building
7. The preview rotation and the way it is built will not match.
