### ISSUE TITLE
Players can kill citizens if pvp=false

### ISSUE THREAD

**Issue by Isfirs** [Minecolonies/minecolonies#74]
### Minecolonies version

I guess `any`.
### Expected behavior

Citizens can't be killed when PVP is turned off.
### Actual behaviour

Players can still kill Citizens.
### Steps to reproduce the problem

Kill a Citizen if `pvp=off` on server

**Comment by Raycoms** [comment]
I made it impossible with the anti griefing to attack citizens if friend or lower.
