### ISSUE TITLE
Miner does not build shafts on SMP

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#76]
### Minecolonies version 
0.3.472

### Expected behavior
He should build shafts.
### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/644950/18120772/8661f60e-6f61-11e6-8263-47e16352a1b4.png)
He builds tunnels but no shafts
### Steps to reproduce the problem
Try it on the main server

**Comment by Kostronor** [comment]
Seems to be fixed with a restart...

**Comment by Kostronor** [comment]
Reopening as it seems a restart only temporary fixes this...

**Comment by matthijs186** [comment]
Can confirm no wooden structures are placed and restarts are a temporary solution.
