### ISSUE TITLE
Citizen Huts and Worker Levels

### ISSUE THREAD

**Issue by pmardle** [Minecolonies/minecolonies#78]
Can we add a new system that limits a workers level (0-50) based on the level of the citizen hut.  This gives a reason/need to upgrade the citizen huts as currently there is no reason to at all.

Therefore at citizen hut level 1, a worker should max out at Level 10
2 = 20
3 = 30 etc..

If we have 5 levels that lets us get up to the 50 mark :)

workers living in the TH should go from the TH level until they move to a Citizen Hut (so need to think how to handle a level 30 worker moving to a level 1 citizen hut.

**Comment by tomorrow4268** [comment]
i'd rather prefer adding only 1 citizen per hut  and reaching level 3 of the bulding will add an additional citizen

**Comment by Raycoms** [comment]
We did something like this already. Done.
