### ISSUE TITLE
Notification System based on achievement system

### ISSUE THREAD

**Issue by Isfirs** [Minecolonies/minecolonies#80]
### Minecolonies version

Any new
### Expected behavior

Show notifications instead of plain chat texts
### Actual behaviour

Chat is spammed by workers.
### Steps to reproduce the problem

Make a worker have needs.
### Related to
#79
### Reference

http://jabelarminecraft.blogspot.de/p/minecraft-forge-creating-custom.html

In reference to the link and the issue, I create a notification API on the client side to **not** trigger achievements for the purpose of notifications.
The persistence of those notifications will be handled later (Blackboard **at** each worker hut(signs)?)

**Comment by Kostronor** [comment]
Nice :)

**Comment by nojo121** [comment]
i give up xD

**Comment by marvin-bitterlich** [comment]
Closing this in favor of other systems
