### ISSUE TITLE
Builder needs 'Wooden Slabs'

### ISSUE THREAD

**Issue by Warrof** [Minecolonies/minecolonies#87]
![2016-09-02_16 15 44](https://cloud.githubusercontent.com/assets/21962742/18220614/b7dd1bdc-7128-11e6-91e7-6f2449305fab.png)
![2016-09-02_16 19 36](https://cloud.githubusercontent.com/assets/21962742/18220662/1140829a-7129-11e6-99e3-7da953a0744c.png)

### Minecolonies version
1.8.9 0.3.472

### Expected behavior
Builder should be using Oak Wood slabs on the roof of the Townhall Classic

### Actual behaviour
She wants 'Wooden Slabs' to finish it out.

### Steps to reproduce the problem
Build the Townhall classic using the Modpack on the server without using infinite resources.

BTW I am currently on the server.

**Comment by Warrof** [comment]
I reset the Job and my builder finished out the job.

**Comment by Kostronor** [comment]
Seems to have resolved itself, closing this for now.
