### ISSUE TITLE
Fully implement flower pots for the builder

### ISSUE THREAD

**Issue by cltnschlosser** [Minecolonies/minecolonies#93]
When the builder builds a flower pot, he should place both the pot and the flower, and should request and use both resources.

**Comment by Kostronor** [comment]
@cltnschlosser is this still an issue? If yes, can you elaborate what currently happens?

**Comment by Raycoms** [comment]
Still an issue. Builder just builds the flower pots with the content and
does not request the flowers/saplings.

2016-11-01 14:06 GMT-02:00 Marvin Hofmann <notifications@github.com>:

**Comment by TheStrato** [comment]
Per v49 Now the builder will request the pots and the flowers but will only place the pots. 

Here is my building seen in the background done with an upgrade and no flowers in the pots
![image](https://user-images.githubusercontent.com/34151516/48966956-3acaae00-ef9f-11e8-819e-b05e8b1bc301.png)
