### ISSUE TITLE
No new farmer for me...

### ISSUE THREAD

**Issue by SACavendish** [Minecolonies/minecolonies#96]
### Minecolonies version
0.3.613
### Expected behavior
I expected to see the new farmer as presented in the new video, also the new scarecrow.
### Actual behaviour
I am still seeing the old farmer building and I cannot see any scarecrow in the creative mode items menu.
### Steps to reproduce the problem
I deleted the old minecolonies java file from my mods folder and added the new one then started the game. Have I not downloaded the correct version or is it because of other mods? Thank you in advance!

**Comment by Kostronor** [comment]
The farmer is not in that release. We will increment the version number to 0.4 once it is included.

The video was sadly inaccurate as the farmer still has a few bugs. But you can help test him with this version: https://minecraft.curseforge.com/projects/minecolonies/files/2328398
