### ISSUE TITLE
Miner gets stuck in loop with nearby lava

### ISSUE THREAD

**Issue by matthijs186** [Minecolonies/minecolonies#97]
### Minecolonies version
0.3.472 (SMP)

### Expected behavior
Not sure what the intended behaviour would be, a simple suggestion would be blocking off the lava with cobblestone so he can continue working on shafts.

### Actual behaviour
The Miner mines to the lava (pool) and automatically places cobblestone near the lava and him. This process is repeated until he retreats to the townhall before night. Also see the video sample below.

### [Video](https://www.youtube.com/watch?v=-gQb9pjSPBI)
Notes: The wood he is standing in did not cause, or seems to be affecting the behaviour. He placed it during the time I wanted to record it.

### Steps to reproduce the problem
Wait until the miner "finds" nearby lava while digging shafts or materials.

**Comment by Kostronor** [comment]
There are currently some bugs with the miner and his general behavior. He should place safety cobble on the lava and it seems that is currently not working.

I think this is related to #76
