### ISSUE TITLE
lumberjack gets stuck when a tree spawns inside him :(

### ISSUE THREAD

**Issue by Thomasdavid097** [Minecolonies/minecolonies#98]
### Minecolonies version
0.3.472

### Expected behavior
lumberjack gets stuck when a tree spawns inside him, no idea if this has been fixed/reported (sorry if it has)

### Actual behaviour
gets stuck when a tree spawns inside him, see picture here: https://puu.sh/r0PCI/80ed26cfbd.png

### Steps to reproduce the problem

maybe have it notice when something spawns inside him, no idea. 

again, sorry if this has been reported, I didn't see any posts on this.

**Comment by Kostronor** [comment]
It seems to be nighttime? Then he won't break the leaves as he wants to go back to his townhall.

Once it is day again he "should" break free from the tree by breaking leaves. Can you test this?

**Comment by Thomasdavid097** [comment]
I left minecraft open for a few hours with him stuck in a tree: https://puu.sh/r1sLz/e7a880a50b.png he didn't try and get out.
